### ISSUE TITLE
NetBeans stopped working properly with Lombok

### ISSUE THREAD

**Issue by ePortfel** [apache/netbeans#6937] opened 2024-01-09 16:57 UTC
### Apache NetBeans version

Apache NetBeans 20

### What happened

In previous versions of NetBeans, the code editor did not mark Lombok-generated methods as not existing. Currently, the code still compiles, but methods are marked red in the editor and the IDE highlights "errors".

### How to reproduce

Open provided project.
[mavenproject1.zip](https://github.com/apache/netbeans/files/13876702/mavenproject1.zip)

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Windows 11

### JDK

15.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment] 2024-01-09 17:02
Duplicate of #6802 and #6893

Update Lombok, or stop using it!

**Closed by neilcsmith-net** 2024-01-09 17:02 UTC
Labels: kind:bug, needs:triage
