### ISSUE TITLE
I cant copy and paset

### ISSUE THREAD

**Issue by AYMEN-ATIYA** [apache/netbeans#6795] opened 2023-12-05 08:02 UTC
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

I cannot copy, paste, or add an external file to the project

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

21

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment] 2023-12-05 12:17
Duplicate of #3962

**Closed by neilcsmith-net** 2023-12-05 12:17 UTC
Labels: kind:bug, needs:triage
