### ISSUE TITLE
Renaming Gradle app creates errors.

### ISSUE THREAD

**Issue by wiegleyj** [apache/netbeans#3595] opened 2022-02-12 18:40 UTC
### Apache NetBeans version

Latest release

### What happened

When you create a new Gradle app you get your initial source code class called "app.java". When you try to rename it you get incorrect results.

Renaming app.java to MyDriver.java for instance produces:
public classMyDriverp 
So it matched and replaced " Ap" with the rename instead of "App".

Please focus on actually getting gradle truly supported. Why is gradle all of the sudden creating multi-project oriented projects? Why don't you get to choose the name of the initial project? Why is there no way to add/delete/modify sub-projects? Why is there no "Run" configuration ability in the project properties? I would not consider gradle to be "supported", it's been difficult to use and buggy and 12.6 didn't improve it as much as it made it even more confusing to use.

### How to reproduce

Make a new gradle project. Rename the App class file.

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

Windows 11

### JDK

java 17.0.2 2022-01-18 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Happens every time.

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by neilcsmith-net** [comment] 2022-02-15 15:56
The changes in 12.6 _were_ about moving to Gradle being better supported. The project wizard changed to use `gradle init` in #3084 so that's why you see the different structure to before. I think there could be an option to enable single project structure - feel free to open a feature request on that one.

I cannot reproduce your rename issues.  Given other problems, and that you're using JDK 17, have you migrated settings from earlier versions of NetBeans? If so, check what your default Gradle version is in Tools / Options. Have noticed an issue with older versions carried forward that don't support JDK 17.

**Comment by lkishalmi** [comment] 2022-02-20 15:54
Cannot reproduce. Rename is working as it should. Tested in 13-rc4

**Comment by matthiasblaesing** [comment] 2022-03-10 20:33
No further reply in 2 weeks.

**Closed by matthiasblaesing** 2022-03-10 20:33 UTC
Labels: kind:bug, pending-response
