### ISSUE TITLE
Gradle project becomes unloadable with some attached plugins

### ISSUE THREAD

**Issue by makiam** [apache/netbeans#4779] opened 2022-10-12 10:18 UTC
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

Some gradle plugins becomes project unloadable and show error

### How to reproduce

I create minimal gradle project with only build.gradle file and sources folder exist
Only plugins section and description is defined in build script
```
plugins {
	id 'java'   
        id "edu.sc.seis.launch4j" version "2.5.3"
}

description = 'MyApplication'
```
Opening this project shows  Cannot Load Project popup and project properties dialog shows Project Unloadable arning

Once I comment launch4j plugin the errors disappears

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Windows 10

### JDK

JDK 18.0.2

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by lkishalmi** [comment] 2022-10-17 03:37
Does launch4j support Java 18?

**Comment by makiam** [comment] 2022-10-17 08:02
My IDE successfully compiles project and creates exe file with JDK 18 but shows this load error

**Comment by makiam** [comment] 2022-10-17 08:13
Issue reproduced also with old JDK9

**Comment by makiam** [comment] 2023-05-31 17:47
I just compile netbeans build with more verbose logging and see that toggling launch4j plugin in build gives stackoverflow exception inside gradle tooling module.
See attached trace.txt
Hope this helps
[trace.txt](https://github.com/apache/netbeans/files/11617381/trace.txt)

**Comment by TetraTheta** [comment] 2023-08-05 04:29
I have same problem with these:

* Windows 11 22H2 (OS build: 22621.2070)
* openjdk 17.0.7 2023-04-18  
  OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)  
  OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
* Apache NetBeans IDE 18
* `id 'edu.sc.seis.launch4j' version '3.0.4'`

If I comment launch4j plugin, NetBeans loads Gradle project without any issue. But if I uncomment that single line, NetBeans throws me either one of these error message:

* `Could not run build action using connection to Gradle installation <path_to_gradle_installation_dir_under_%GRADLE_USER_HOME%>`  
* `Could not run build action using connection to Gradle distribution <url_of_services.gradle.org>`  
  Only when I removed everything under `%GRADLE_USER_HOME%` and open the project

**Comment by victorwss** [comment] 2023-10-03 05:33
Due to this bug, Spotbugs is unusable in NetBeans with Gradle at this moment.

**Comment by victorwss** [comment] 2023-10-12 06:46
Trying to build a gradle project that uses the spotbugs plugin in Netbeans makes Netbeans fail the build with an empty message error and mark the project as unloadable and fallbacking to Java 5 (yikes!).

Netbeans 19 (but it also happened in older versions)
Java 21 (but I also tested with 20)
Gradle 8.4 (but I also tested with 8.3)
Spotbugs gradle plugin 6.0.0-beta4
Spotbugs 4.7.3

Since it runs perfectly when running Gradle on CMD an it only goes nuts in Netbeans, It fails to load giving a blank error message and fallbacks to Java 5 (a very unfortunate choice for a fallback, since this spuriously makes about everything in the code being marked as an error).

I created a minimal Hello World with a minimal gradle with spotbugs file to show the problem: https://github.com/victorwss/min-spotbugs-gradle

It seems that as soon as I add `id("com.github.spotbugs") version "6.0.0-beta.4"` in the gradle build script, Netbeans go nuts.

Running it in the console:

```
C:\Projects\min-spotbugs-gradle>gradle build

BUILD SUCCESSFUL in 657ms
6 actionable tasks: 6 up-to-date
C:\Projects\min-spotbugs-gradle>gradle run

> Task :run
Hello World

BUILD SUCCESSFUL in 732ms
2 actionable tasks: 1 executed, 1 up-to-date
```

Opening it in Netbeans 19:

![image](https://github.com/apache/netbeans/assets/4574568/5ed6394c-5292-4e3e-9bfa-8933129d1815)
![image](https://github.com/apache/netbeans/assets/4574568/1f9bc72a-78c3-4443-b261-1417579e6ac5)

I don't know for sure about other plugins, but I think that the cause is the same.

**Closed** 2023-12-04 07:36 UTC
Labels: kind:bug, Gradle, needs:triage
