### ISSUE TITLE
the autocomplete is crashing because of a project

### ISSUE THREAD

**Issue by mdarweash** [apache/netbeans#8041] opened 2024-12-12 08:49 UTC
### Apache NetBeans version

Apache NetBeans 24 release candidate

### What happened

on startup, the netbeans crashes due to parsing error .

this happend on 23, and also in 24 RC

### Language / Project Type / NetBeans Component

Java Maven

### How to reproduce
```

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/springframework/Repository.java to edit this template
 */
package tech.hexio.HexAiEngine.dal.mysql.repo;

import org.springframework.data.jpa.repository.JpaRepository;


/**
 *
 * @author mdarweash
 */
public interface HipCompanyRepo extends JpaRepository<Hip, Integer> {
    
}

----- Classpath: ---------------------------------------------
bootPath: nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.base/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.compiler/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.datatransfer/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.desktop/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.instrument/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.logging/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.management/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.management.rmi/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.naming/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.net.http/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.prefs/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.rmi/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.scripting/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.se/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.security.jgss/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.security.sasl/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.smartcardio/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.sql/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.sql.rowset/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.transaction.xa/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.xml/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/java.xml.crypto/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.accessibility/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.attach/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.charsets/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.compiler/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.crypto.cryptoki/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.crypto.ec/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.dynalink/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.editpad/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.hotspot.agent/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.httpserver/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.incubator.vector/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.internal.ed/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.internal.jvmstat/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.internal.le/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.internal.opt/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.internal.vm.ci/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.internal.vm.compiler/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.internal.vm.compiler.management/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jartool/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.javadoc/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jcmd/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jconsole/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jdeps/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jdi/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jdwp.agent/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jfr/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jlink/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jpackage/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jshell/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jsobject/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.jstatd/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.localedata/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.management/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.management.agent/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.management.jfr/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.naming.dns/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.naming.rmi/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.net/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.nio.mapmode/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.random/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.sctp/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.security.auth/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.security.jgss/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.unsupported/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.unsupported.desktop/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.xml.dom/:nbjrt:file:/usr/lib/jvm/java-21-openjdk-amd64/!/modules/jdk.zipfs/
classPath: /home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/3.4.0/spring-boot-starter-actuator-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter/3.4.0/spring-boot-starter-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.4.0/spring-boot-starter-logging-3.4.0.jar:/home/mdarweash/.m2/repository/ch/qos/logback/logback-classic/1.5.12/logback-classic-1.5.12.jar:/home/mdarweash/.m2/repository/ch/qos/logback/logback-core/1.5.12/logback-core-1.5.12.jar:/home/mdarweash/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.24.1/log4j-to-slf4j-2.24.1.jar:/home/mdarweash/.m2/repository/org/apache/logging/log4j/log4j-api/2.24.1/log4j-api-2.24.1.jar:/home/mdarweash/.m2/repository/org/slf4j/jul-to-slf4j/2.0.16/jul-to-slf4j-2.0.16.jar:/home/mdarweash/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/home/mdarweash/.m2/repository/org/yaml/snakeyaml/2.3/snakeyaml-2.3.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/3.4.0/spring-boot-actuator-autoconfigure-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-actuator/3.4.0/spring-boot-actuator-3.4.0.jar:/home/mdarweash/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.18.1/jackson-databind-2.18.1.jar:/home/mdarweash/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.18.1/jackson-annotations-2.18.1.jar:/home/mdarweash/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.18.1/jackson-core-2.18.1.jar:/home/mdarweash/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.18.1/jackson-datatype-jsr310-2.18.1.jar:/home/mdarweash/.m2/repository/io/micrometer/micrometer-observation/1.14.1/micrometer-observation-1.14.1.jar:/home/mdarweash/.m2/repository/io/micrometer/micrometer-commons/1.14.1/micrometer-commons-1.14.1.jar:/home/mdarweash/.m2/repository/io/micrometer/micrometer-jakarta9/1.14.1/micrometer-jakarta9-1.14.1.jar:/home/mdarweash/.m2/repository/io/micrometer/micrometer-core/1.14.1/micrometer-core-1.14.1.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-security/3.4.0/spring-boot-starter-security-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-aop/6.2.0/spring-aop-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-beans/6.2.0/spring-beans-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/security/spring-security-config/6.4.1/spring-security-config-6.4.1.jar:/home/mdarweash/.m2/repository/org/springframework/spring-context/6.2.0/spring-context-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/security/spring-security-web/6.4.1/spring-security-web-6.4.1.jar:/home/mdarweash/.m2/repository/org/springframework/spring-expression/6.2.0/spring-expression-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.4.0/spring-boot-starter-web-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.4.0/spring-boot-starter-json-3.4.0.jar:/home/mdarweash/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.18.1/jackson-datatype-jdk8-2.18.1.jar:/home/mdarweash/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.18.1/jackson-module-parameter-names-2.18.1.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.4.0/spring-boot-starter-tomcat-3.4.0.jar:/home/mdarweash/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.33/tomcat-embed-core-10.1.33.jar:/home/mdarweash/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.33/tomcat-embed-websocket-10.1.33.jar:/home/mdarweash/.m2/repository/org/springframework/spring-web/6.2.0/spring-web-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-webmvc/6.2.0/spring-webmvc-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot/3.4.0/spring-boot-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.4.0/spring-boot-autoconfigure-3.4.0.jar:/home/mdarweash/.m2/repository/org/slf4j/slf4j-api/2.0.16/slf4j-api-2.0.16.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-configuration-processor/3.4.0/spring-boot-configuration-processor-3.4.0.jar:/home/mdarweash/.m2/repository/org/projectlombok/lombok/1.18.36/lombok-1.18.36.jar:/home/mdarweash/.m2/repository/org/springframework/spring-core/6.2.0/spring-core-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-jcl/6.2.0/spring-jcl-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/security/spring-security-core/6.4.1/spring-security-core-6.4.1.jar:/home/mdarweash/.m2/repository/org/springframework/security/spring-security-crypto/6.4.1/spring-security-crypto-6.4.1.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/3.4.0/spring-boot-starter-data-jpa-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/3.4.0/spring-boot-starter-jdbc-3.4.0.jar:/home/mdarweash/.m2/repository/com/zaxxer/HikariCP/5.1.0/HikariCP-5.1.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-jdbc/6.2.0/spring-jdbc-6.2.0.jar:/home/mdarweash/.m2/repository/org/hibernate/orm/hibernate-core/6.6.2.Final/hibernate-core-6.6.2.Final.jar:/home/mdarweash/.m2/repository/jakarta/persistence/jakarta.persistence-api/3.1.0/jakarta.persistence-api-3.1.0.jar:/home/mdarweash/.m2/repository/jakarta/transaction/jakarta.transaction-api/2.0.1/jakarta.transaction-api-2.0.1.jar:/home/mdarweash/.m2/repository/org/jboss/logging/jboss-logging/3.6.1.Final/jboss-logging-3.6.1.Final.jar:/home/mdarweash/.m2/repository/com/fasterxml/classmate/1.7.0/classmate-1.7.0.jar:/home/mdarweash/.m2/repository/org/antlr/antlr4-runtime/4.13.0/antlr4-runtime-4.13.0.jar:/home/mdarweash/.m2/repository/org/springframework/data/spring-data-jpa/3.4.0/spring-data-jpa-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/data/spring-data-commons/3.4.0/spring-data-commons-3.4.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-orm/6.2.0/spring-orm-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-tx/6.2.0/spring-tx-6.2.0.jar:/home/mdarweash/.m2/repository/org/springframework/spring-aspects/6.2.0/spring-aspects-6.2.0.jar:/home/mdarweash/.m2/repository/org/aspectj/aspectjweaver/1.9.22.1/aspectjweaver-1.9.22.1.jar:/home/mdarweash/.m2/repository/org/springframework/boot/spring-boot-starter-validation/3.4.0/spring-boot-starter-validation-3.4.0.jar:/home/mdarweash/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.33/tomcat-embed-el-10.1.33.jar:/home/mdarweash/.m2/repository/org/hibernate/validator/hibernate-validator/8.0.1.Final/hibernate-validator-8.0.1.Final.jar:/home/mdarweash/.m2/repository/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.jar:/home/mdarweash/Qoudra/projects/HEXiot/products/HalalGPT/SW/HipService/target/classes
sourcePath: /home/mdarweash/Qoudra/projects/HEXiot/products/HalalGPT/SW/HipService/src/main/java:/home/mdarweash/Qoudra/projects/HEXiot/products/HalalGPT/SW/HipService/src/main/resources:/home/mdarweash/Qoudra/projects/HEXiot/products/HalalGPT/SW/HipService/src/main/resources
----- Original exception ---------------------------------------------
java.lang.IllegalArgumentException: version can neither be null, empty nor blank
	at org.apache.maven.artifact.ArtifactUtils.notBlank(ArtifactUtils.java:95)
	at org.apache.maven.artifact.ArtifactUtils.toSnapshotVersion(ArtifactUtils.java:53)
	at org.apache.maven.artifact.DefaultArtifact.setBaseVersionInternal(DefaultArtifact.java:354)
	at org.apache.maven.artifact.DefaultArtifact.selectVersion(DefaultArtifact.java:443)
	at org.apache.maven.artifact.DefaultArtifact.selectVersionFromNewRangeIfAvailable(DefaultArtifact.java:434)
	at org.apache.maven.artifact.DefaultArtifact.<init>(DefaultArtifact.java:126)
	at org.apache.maven.artifact.DefaultArtifact.<init>(DefaultArtifact.java:88)
	at org.netbeans.modules.maven.api.PluginPropertyUtils.getPluginPathProperty(PluginPropertyUtils.java:839)
	at org.netbeans.modules.maven.classpath.AnnotationProcClassPathImpl.getCompileArtifacts(AnnotationProcClassPathImpl.java:91)
	at org.netbeans.modules.maven.classpath.AnnotationProcClassPathImpl.createPath(AnnotationProcClassPathImpl.java:66)
	at org.netbeans.modules.maven.classpath.AbstractProjectClassPathImpl.getPath(AbstractProjectClassPathImpl.java:153)
	at org.netbeans.modules.maven.classpath.AbstractProjectClassPathImpl.getResources(AbstractProjectClassPathImpl.java:144)
	at org.netbeans.api.java.classpath.ClassPath.entries(ClassPath.java:363)
	at org.netbeans.modules.maven.classpath.ClassPathProviderImpl$AnnotationPathSelector.getActiveClassPath(ClassPathProviderImpl.java:685)
	at org.netbeans.spi.java.classpath.support.MuxClassPathImplementation.getActiveClassPath(MuxClassPathImplementation.java:156)
	at org.netbeans.spi.java.classpath.support.MuxClassPathImplementation.getResources(MuxClassPathImplementation.java:89)
	at org.netbeans.api.java.classpath.ClassPath.entries(ClassPath.java:363)
	at org.netbeans.api.java.classpath.ClassPath.getRoots(ClassPath.java:248)
	at org.netbeans.modules.java.source.indexing.APTUtils.listenOnProcessorPath(APTUtils.java:343)
	at org.netbeans.modules.java.source.indexing.APTUtils.listen(APTUtils.java:329)
	at org.netbeans.modules.java.source.indexing.APTUtils.create(APTUtils.java:234)
	at org.netbeans.modules.java.source.indexing.APTUtils.get(APTUtils.java:181)
	at org.netbeans.modules.java.source.parsing.JavacParser.createJavacTask(JavacParser.java:897)
	at org.netbeans.modules.java.source.parsing.CompilationInfoImpl.getJavacTask(CompilationInfoImpl.java:460)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:659)
	at org.netbeans.modules.java.source.parsing.CompilationInfoImpl.toPhase(CompilationInfoImpl.java:426)
	at org.netbeans.api.java.source.CompilationController.toPhase(CompilationController.java:90)
	at org.netbeans.modules.java.JavaNode$IconTask$SourceIcon.lambda$computeIcon$0(JavaNode.java:682)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:197)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:180)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:454)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.java.JavaNode$IconTask$SourceIcon.computeIcon(JavaNode.java:681)
	at org.netbeans.modules.java.JavaNode$IconTask.run(JavaNode.java:643)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)

```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 24.04

### JDK

JDK21

### Apache NetBeans packaging

Other

### Anything else

I'm using the deb Installation

extra info

i'm using this plugin to initiate projects
https://plugins.netbeans.apache.org/catalogue/?id=4

which is working pretty well. last generated project was 1 week ago. was complicated with SpringAi. and it worked without a problem

I mention that because I believe the problem is coming from this POM

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.0</version>
        <relativePath/> 
    </parent>
    <groupId>tech.hexio.hip</groupId>
    <artifactId>hipService</artifactId>
    <version>1.0.0</version>
    <name>HipService</name>
    <description>Hip Service</description>
  
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.6.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <type>jar</type>
        </dependency>
        
        
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.core</artifactId>
            <version>2.7.12</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.asm</artifactId>
            <version>9.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.antlr</artifactId>
            <version>2.7.12</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.jpa</artifactId>
            <version>2.7.12</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.jpa.jpql</artifactId>
            <version>2.7.12</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.moxy</artifactId>
            <version>2.7.12</version>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
        </dependency>

        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>jakarta.persistence</artifactId>
            <version>2.2.3</version>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-devtools</artifactId>
                <version>3.4.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        
        <plugins>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.6</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/target/classes/public</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/webapp</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>hexio-gitlab-maven</id>
            <url>ssh://git@git.hexio.tech/api/v4/packages/maven/</url>
        </repository>

    </repositories>

</project>
 

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment] 2024-12-14 10:08
Probably a duplicate of #7664

**Comment by matthiasblaesing** [comment] 2024-12-15 09:50
The classpath resolution code is missing quering the DependencyManagment for the plugin version that is correctedin #8057. Please test the nightly build [Checks page](https://github.com/apache/netbeans/pull/8057/checks) [direct link](https://github.com/apache/netbeans/suites/32072296742/artifacts/2321761897).

**Closed** 2024-12-22 15:00 UTC
Labels: kind:bug, Java, Maven, needs:triage, pending-response

**Comment by sysmat** [comment] 2025-01-23 04:55
Annotation Processor in NB 24 is not working

**Comment by sysmat** [comment] 2025-01-23 09:49
Apache is destroying NetBeans, every new version is worse and worse

**Comment by matthiasblaesing** [comment] 2025-01-23 18:13
@sysmat please don't highjack issues. If you have a problem, create a minimal, runnable reproducer, open an issue, provide steps to reproduce.
