### ISSUE TITLE
Windows install fails remote versioning issues

### ISSUE THREAD

**Issue by patsummit** [apache/netbeans#7626] opened 2024-08-01 11:53 UTC
### Apache NetBeans version

Apache NetBeans 22

### What happened

 I get the following error message in a dialog.  Removing and reinstalling does not fix the problem.  I have netbeans 18 installed on this computer and the install used jdk 19. 

Warning - could not install some modules: Versioning to Remote Bridge API - None of the modules providing the capability org.netbeans.modules.remotefs.versioning could be installed. Versioning to Remote Bridge API - The module named org.netbeans.modules.versioning.util was needed and not found. Remote Mercurial - The module named org.netbeans.modules.versioning.util was needed and not found. Remote Subversion - The module named org.netbeans.modules.versioning.util was needed and not found. Remote Git - The module named org.netbeans.modules.versioning.util was needed and not found. 7 further modules could not be installed due to the above problems.

### How to reproduce

I do not know how to reproduce and the installed worked on one computer a few days and failed today. 

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Windows 11 currently updated.

### JDK

C:\Users\PATGI>java --version java 19 2022-09-20 Java(TM) SE Runtime Environment (build 19+36-2238) Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2024-08-01 17:51
This sounds as if you installed NB22 into the same directory that NB18 was installed into. If so, this is a duplicate of #7495.

If that is not the case, please provide the message.log

**Closed by matthiasblaesing** 2024-08-01 17:51 UTC
Labels: kind:bug, needs:triage

**Comment by patsummit** [comment] 2024-08-01 18:35
While I did not install in the same directory it seems to work if I uninstall netbeans 22 and then manually remove the appdata/netbeans/22 directory.
