### ISSUE TITLE
Maven compile on save not working

### ISSUE THREAD

**Issue by quantrpeter** [apache/netbeans#5872] opened 2023-04-23 13:12 UTC
### Apache NetBeans version

Apache NetBeans 17

### What happened

Saving the file won't auto compile

### How to reproduce

just save the file

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac latest

### JDK

java version "17.0.6" 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment] 2023-04-24 16:33
Duplicate of #5839 ?

**Closed by neilcsmith-net** 2023-04-24 16:33 UTC
Labels: kind:bug, needs:triage
