### ISSUE TITLE
Unable to create empty Maven POM project

### ISSUE THREAD

**Issue by iajn** [apache/netbeans#3809] opened 2022-03-18 20:07 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

Trying to create a new Maven POM Project results in an empty directory with no pom.xml, project wizard shows a warning icon and an exception is logged.

### How to reproduce

1. New Project
2. Java with Maven -> POM Project
3. Finish wizard with defaults

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 10

### JDK

Eclipse Adoptium 11.0.13.8-hotspot

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

This also happens when adding a new empty POM module to an existing project. Maven Java Application, NetBeans Module, NetBeans Application and Project from Archetype seem to work fine.
```
INFO [org.netbeans.ui.metrics.maven]: USG_PROJECT_CREATE_MAVEN
INFO [org.openide.WizardDescriptor]
msg
Caused: java.io.SyncFailedException: C:\Users\iajn\Documents\NetBeansProjects\mavenproject1
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.createData(FolderObj.java:377)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.createDataImpl(FolderObj.java:324)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj$1.call(FolderObj.java:290)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj$1.call(FolderObj.java:288)
	at org.netbeans.modules.masterfs.filebasedfs.FileBasedFileSystem.runAsInconsistent(FileBasedFileSystem.java:97)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FolderObj.createData(FolderObj.java:293)
	at org.netbeans.api.templates.CreateFromTemplateImpl.defaultCreate(CreateFromTemplateImpl.java:334)
	at org.netbeans.api.templates.CreateFromTemplateImpl.build(CreateFromTemplateImpl.java:151)
	at org.netbeans.api.templates.CreateFromTemplateImpl.lambda$build$0(CreateFromTemplateImpl.java:86)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.netbeans.api.templates.CreateFromTemplateImpl.build(CreateFromTemplateImpl.java:84)
	at org.netbeans.api.templates.FileBuilder.build(FileBuilder.java:267)
	at org.netbeans.modules.maven.newproject.idenative.IDENativeMavenWizardIterator.instantiate(IDENativeMavenWizardIterator.java:85)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1048)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.netbeans.modules.project.ui.NewProjectWizard.handleInstantiate(NewProjectWizard.java:51)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:228)
	at org.openide.loaders.TemplateWizardIteratorWrapper$ProgressInstantiatingIterator.instantiate(TemplateWizardIteratorWrapper.java:155)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1602)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
ALL [null]: Cannot create file mavenproject1 in folder C:/Users/iajn/Documents/NetBeansProjects.
```
![pom-project](https://user-images.githubusercontent.com/10802138/159075519-e5886bbe-fae7-4caa-be46-bda39ecb24aa.png)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by bradh** [comment] 2022-03-28 02:33
I also see this problem with Netbeans 13 on Ubuntu (from Snap packages). It seems like the maven template may have been modified to create a `.java` file (for at least the Java Application project type - which is a regression IMHO, but it does work and is easy to delete), but this doesn't breaks for the POM project type.

**Comment by FerhatSavci** [comment] 2022-04-18 13:54
Same here, both snap install and install from shell script downloaded from Apache behave the same for v13, using OpenJDK "11.0.14.1" on Ubuntu 20.04.4 LTS.

**Comment by jre95001** [comment] 2022-04-26 13:31
Same here.  My install is from the flatpak on Linux Mint.

**Comment by mbien** [comment] 2022-06-19 02:12
should be fixed in NB 14

**Closed by mbien** 2022-06-19 02:12 UTC
Labels: kind:bug, Maven

**Comment by bradh** [comment] 2022-06-19 06:44
Confirm it works for me with NB 14 on Ubuntu (from Snap packages).
