### ISSUE TITLE
java refactoring with array declaration

### ISSUE THREAD

**Issue by vraoulinfr** [apache/netbeans#5883] opened 2023-04-25 08:39 UTC
### Apache NetBeans version

Apache NetBeans 17

### What happened

Refactoring an array field or array variable declared with non array field put the array tag [] after the field type, which is an error. This bug late from first version of netbeans, so boring after version 17...

### How to reproduce

double anArray[],v,w;

after refactoring  anArray as toArray:

double[] toArray,v,w;

while vow are not arrays.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

osx, linux

### JDK

17.0.4.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by Nesrinasan** [comment] 2023-06-21 20:14
hi,
I want to examine this issue. Could you assign me ? @neilcsmith-net

**Comment by mbien** [comment] 2024-11-22 21:39
closing as duplicate of https://github.com/apache/netbeans/issues/4765

**Closed by mbien** 2024-11-22 21:39 UTC
Labels: kind:bug, Java, Contribution welcome
