### ISSUE TITLE
NetBeans Code Completion in JSF page xhtml

### ISSUE THREAD

**Issue by roabol** [apache/netbeans#7488] opened 2024-06-16 13:47 UTC
### Apache NetBeans version

Apache NetBeans 22

### What happened

when opening auto completion the JSF options do not appear

![image](https://github.com/apache/netbeans/assets/2237805/588495fc-68dc-46ad-8ac8-bfd88ef86578)

### Language / Project Type / NetBeans Component

Java JSF Primefaces

### How to reproduce

ctrl + space

### Did this work correctly in an earlier version?

Apache NetBeans 21

### Operating System

Windows 11

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2024-06-16 13:52
Most probably duplicate of #7449, #7436 and #7354. Fixed by https://github.com/apache/netbeans/pull/7464

**Closed by matthiasblaesing** 2024-06-16 13:52 UTC
Labels: kind:bug, needs:triage
