### ISSUE TITLE
Find In Projects: Reload button overwrites with newer search

### ISSUE THREAD

**Issue by headbank** [apache/netbeans#3772] opened 2022-03-13 00:37 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

In a PHP project, using the Find In Projects tool. After running one search and then another, it's impossible to re-run the original search, because when clicking the Reload button, the dialog that comes up contains the parameters of the subsequent search. If one clicks Find, the original tab becomes a clone of the second search.

### How to reproduce

1. Perform a Find In Projects search.
2. Perform a different Find In Projects search.
3. Return to the tab of the first search, and click Reload button.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Gentoo Linux on AMD64

### JDK

OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment] 2022-03-13 00:44
already fixed in master, duplicate of #3737

**Closed by mbien** 2022-03-13 00:44 UTC
Labels: kind:bug, needs:triage
