### ISSUE TITLE
Profiler does not work on Apple Silicon

### ISSUE THREAD

**Issue by santiontanon** [apache/netbeans#4524] opened 2022-08-21 21:44 UTC
### Apache NetBeans version

Apache NetBeans 14

### What happened

Profiler cannot start on Apple Silicon. The first time it tries to start, it needs to run a calibration. For this, the console displays that Netbeans is running the following command:

```/Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/bin/java -agentpath:/Applications/NetBeans/Apache NetBeans 14.app/Contents/Resources/NetBeans/netbeans/profiler/lib/deployed/jdk16/mac/libprofilerinterface.jnilib -Xbootclasspath/a:/Applications/NetBeans/Apache NetBeans 14.app/Contents/Resources/NetBeans/netbeans/profiler/lib/jfluid-server.jar:/Applications/NetBeans/Apache NetBeans 14.app/Contents/Resources/NetBeans/netbeans/profiler/lib/jfluid-server-15.jar org.netbeans.lib.profiler.server.ProfilerServer /Applications/NetBeans/Apache NetBeans 14.app/Contents/Resources/NetBeans/netbeans/profiler/lib/deployed/jdk16/mac 5141 10 ____Profiler+Calibration+Run____```

And hungs there forever.

Trying to run that command manually on the command line reveals that the command fails with the following error:

```Error occurred during initialization of VM Could not find agent library /Applications/NetBeans/Apache NetBeans 14.app/Contents/Resources/NetBeans/netbeans/profiler/lib/deployed/jdk16/mac/libprofilerinterface.jnilib in absolute path, with error: dlopen(/Applications/NetBeans/Apache NetBeans 14.app/Contents/Resources/NetBeans/netbeans/profiler/lib/deployed/jdk16/mac/libprofilerinterface.jnilib, 0x0001): tried: '/Applications/NetBeans/Apache NetBeans 14.app/Contents/Resources/NetBeans/netbeans/profiler/lib/deployed/jdk16/mac/libprofilerinterface.jnilib' (fat file, but missing compatible architecture (have 'unknown,i386,unknown,x86_64', need 'arm64e')), '/usr/lib/libprofilerinterface.jnilib' (no such file)```

So, it seems that the "libprofilerinterface.jnilib" file is only provided for intel processors, but not for Arm, and hence it cannot be run on Apple Silicon. I wonder if there is any way to generate an Apple Silicon version of this file.

### How to reproduce

Just try to profile any Java project, and this will occur.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

MacOS 12.2 Monterey on Apple Silicon

### JDK

java 18.0.2.1 2022-08-18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This problem occurs every time.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by twolf2919** [comment] 2023-02-23 19:10
I can confirm getting the same results with Netbeans 16 on JDK 17.05 on an Apple Silicon Mac.  The same identical project with same JDK and same version of Netbeans works on an x86-based Mac.

**Comment by jepsar** [comment] 2023-04-11 13:16
Same for me on NB17: (fat file, but missing compatible architecture (have 'unknown,i386,unknown,x86_64', need 'arm64'))

**Comment by gwegner** [comment] 2023-04-15 10:02
Same here. Any solutions yet?

**Comment by gwegner** [comment] 2023-08-15 16:01
The first report was over one year ago. Is there any solution in the mean time?

**Comment by neilcsmith-net** [comment] 2023-09-25 14:32
@sroeper the universal macOS installer for NB19 should have addressed the libjnidispatch issue. If you're still seeing that, please open another issue.

Unfortunately, the profiler issue isn't fixed yet. It's a shame that M1/M2 is still not fully supported yet - not enough developers using that architecture I guess.

**Comment by sroeper** [comment] 2023-09-25 15:04
@neilcsmith-net Thank you for the hint, I didn't realised that the Apache-NetBeans-19.pkg is the installer for Mac. I used the Binary (Plattform Independent) netbeans-19-bin.zip, which seems not so platform independent :-)

And yes, I can confirm that the issue with libjnidispatch-nb.jnilib is not present with the installer package, and the issue with the profiler is still not fixed in NB19.

You might be right that not enough developers are using Netbeans on the M1/M2 architecture. I am the last one I know but the architecture itself is used by more than 80% of the developers I work with (and all use Intelij).
So I think the Netbeans IDE is not very attractive to these developers. Even if they would try Netbeans they would be disappointed and go for an alternative. So we can assume that there wouldn't be an higher count of developers who use Netbeans on Apple Silicon in the future which in turn will lead to even worse support for the platform.

Never the less I had a lot of lucky years  with Netbeans, so a big thank you to all contributors!

**Comment by neilcsmith-net** [comment] 2023-09-25 17:24
@sroeper the zip is platform independent, but not code signed!  That is why you see that issue unless you bypass quarantine protections.

It's not about developers using NetBeans on M1/M2 architecture, but developers _contributing_ to NetBeans who do.

**Comment by sroeper** [comment] 2023-09-25 17:32
Ok, may be it's time to give something back. Fixing the profiler is pretty easy, but I have no clue how to make a push request.

So here it comes:
The profiler lib is build by a shell script: 
netbeans/profiler/lib.profiler/native/scripts/buildnative-mac.sh

This file seems to be a little bit too old. The author didn't know at that time how to build a universal library for arm64 and x86_64. The build produces a library with support for i386, ppc, ppc64 and x86_64. Because Apple drop the support for ppc and i386 we should not longer support them (no chance to update the code).

As a result we can focus on building a library for x86_64 and arm64. This is what I have done. I tested the library with NB19 with success (even if I am not totally clear why there is a jdk16 dependency...).

New build file is attached. If someone would be so kind to integrate that into the right repository it would be fixed for the next build. Even better would be of course if someone with more knowledge checks if the jdk15/jdk16 thing is still ok.

Here is the build file:
[buildnative-mac.sh.zip](https://github.com/apache/netbeans/files/12717969/buildnative-mac.sh.zip)

**Comment by sroeper** [comment] 2023-09-25 17:39
@neilcsmith-net That's all I can do, hopefully I am bit closer now to what you expect.

**Comment by santiontanon** [comment] 2023-09-25 22:22
Oh, thanks a lot sroeper! I might try to run your script as a work around, but it'd be awesome to have a version of this integrated into the next build :)

**Comment by sroeper** [comment] 2023-09-26 13:45
I tried my very best to make a pull request from the change, see https://github.com/apache/netbeans/pull/6494

**Comment by gwegner** [comment] 2023-09-29 13:21
Thanks so much, @sroeper !

**Comment by neilcsmith-net** [comment] 2023-10-14 16:59
Should be fixed in NB20.  A release candidate should be available next week.  Please help testing that.

**Closed by neilcsmith-net** 2023-10-14 16:59 UTC
Labels: kind:bug, os:macos

**Comment by michaelajr** [comment] 2023-11-26 14:42
I just downloaded 20-rc3 (binary zip) and Terminal works on my M1. So hoping when the `pkg` installer is released with v20  it will be fixed.

**Comment by jepsar** [comment] 2023-12-14 10:39
Terminal is working again for me as well in 20.
