### ISSUE TITLE
Issue: failed to install nodejs 

### ISSUE THREAD

**Issue by vertigo1983** [apache/netbeans#7954] opened 2024-11-11 16:30 UTC
### Apache NetBeans version

Apache NetBeans 23

### What happened

```
java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemProperties starting from ModuleCL@4ee25dee[org.netbeans.libs.commons_compress] with possible defining loaders null and declared parents [ModuleCL@5c328a2d[org.apache.commons.commons_io]]
Caused: java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemProperties
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.normalizeFileName(TarArchiveEntry.java:231)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.setName(TarArchiveEntry.java:1871)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:452)
	at org.netbeans.modules.javascript.nodejs.util.FileUtils.decompressTarGz(FileUtils.java:398)
	at org.netbeans.modules.javascript.nodejs.util.FileUtils.downloadNodeSources(FileUtils.java:313)
	at org.netbeans.modules.javascript.nodejs.ui.NodeJsPathPanel$3.run(NodeJsPathPanel.java:281)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)
[messages.log](https://github.com/user-attachments/files/17705625/messages.log)
```

### How to reproduce

trying to install nodejs via the download-button in the references

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 11

### JDK

23

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by vertigo1983** [comment] 2024-11-11 16:30
[messages.log](https://github.com/user-attachments/files/17705643/messages.log)

**Comment by matthiasblaesing** [comment] 2024-11-11 17:45
Duplicate of #7814. Please check the latest RC for NB24: https://github.com/apache/netbeans/discussions/7898

**Closed by matthiasblaesing** 2024-11-11 17:45 UTC
Labels: kind:bug, needs:triage
