### ISSUE TITLE
Slowness detected

### ISSUE THREAD

**Issue by LadyCailin** [apache/netbeans#3694] opened 2022-03-04 19:15 UTC
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

Ctrl+Clicking on a class to go to declaration. The class I clicked on didn't have its import yet, but the IDE had not yet figured out that out yet, and wasn't (yet) highlighting it red, so that may or may not be related. After a few seconds, the "Lengthy operation" window popped up. I waited for a bit and I tried clicking cancel, but that wasn't responsive either, but that also might be required to reproduce. Eventually after about 30 seconds, response returned.

Also, the bug report tool directed me to JIRA, not here, though the default issue gave me the correct link.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 10

### JDK

Adoptium JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

[CrashLog.txt](https://github.com/apache/netbeans/files/8188260/CrashLog.txt)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by kjmclaws** [comment] 2022-03-04 21:28
Also it is painfully slow to add a library folder. I think it has to do with parsing the directories or something. (I'm a newb)

**Comment by mbien** [comment] 2022-03-05 11:07
this is going to be difficult to resolve if there is no reproducer provided.

(Issues like this can be influenced by so many factors that they will be usually closed after a while due to inactivity)

**Comment by LadyCailin** [comment] 2022-03-05 12:57
¯\_(ツ)_/¯ I was just reporting the bug like the IDE instructed me to.

**Comment by Chris2011** [comment] 2022-03-05 22:32
> ¯\_(ツ)_/¯ I was just reporting the bug like the IDE instructed me to.

That is totally fine and we appreciates it and also, we need more info to reproduce, you know? How can we reproduce the problem if we not have a code example for example? Which project did you create? Was it maven, gradle, ant? If possible please share the project or the file and explicit steps to reproduce, for example:

* Open file...
* Do ctrl + click in line x onto class y
* ...

**Comment by LadyCailin** [comment] 2022-03-06 23:01
The project I had open was here: https://github.com/EngineHub/CommandHelper

I actually can't get it to reproduce right now, so perhaps the actionable item is to put more information into the logs that would be useful for nailing down what the problem is, to figure out what combination of problems causes it.

**Comment by Chris2011** [comment] 2022-03-08 21:25
Sure, putting more into the log is always a good idea and for now we don't have this info, unfortunately. What we can have is more info from you. Also you didn't tell us the file that you opened and the codepart where tried to navigate to w/o having an import. So in which file did you get this problem? Was it a self written file? Then you can share the file with us. etc.

**Comment by LadyCailin** [comment] 2022-03-08 21:47
Ah, yes, sorry. This was an exception that I was clicking (the throws declaration on a function definition). I was adding the "ConfigCompileGroupException" to this line: https://github.com/EngineHub/CommandHelper/blob/declarative-prefilters/src/main/java/com/laytonsmith/core/functions/AbstractFunction.java#L228. I did try it more than once though, on a different file, and the slowness happened there too, so I don't think it was something specific about the file. I'm not sure what you mean by self-written file, but hopefully the link answers your question.

**Comment by LadyCailin** [comment] 2022-03-08 21:50
Actually, now I'm second guessing myself, it could have been the interface that I was editing at the time, not the abstract class. It was definitely the ConfigCompileGroupException though, in either this file or the one previously linked. https://github.com/EngineHub/CommandHelper/blob/a83b6495747dc484a73cc2a365261200f2e3891b/src/main/java/com/laytonsmith/core/Optimizable.java#L182

**Comment by Chris2011** [comment] 2022-03-08 21:54
Thx for the info, I will check this the days :).

**Comment by Chris2011** [comment] 2022-04-22 15:23
Unfortunately I can't reproduce it, I tried ctrl + click in the AbstractFunction and also in the Optimizable. So if it is possible please observe it and try to reproduce it and please give more information. I know that "It works on my machine" is not nice, but we need as much information as possible to try to reproduce it.

**Comment by lkishalmi** [comment] 2022-09-11 15:09
Closing as this was not-reproducible and abandoned.

**Closed by lkishalmi** 2022-09-11 15:09 UTC
Labels: kind:bug
