### ISSUE TITLE
php editor : infinte semicolon while autocomplet on "return"

### ISSUE THREAD

**Issue by eglic** [apache/netbeans#3805] opened 2022-03-18 07:45 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

from version 12.6 to 13.0: 

1. create or open any php file
2. input "ret" anywhere
3. wait autocomplete menu popuped
4. press "Enter" to select only option "return ...  Language Construct"
5. netbeans insert "return ;;;;;;;;"
6. the character ";"  will auto append infinity until press any key

### How to reproduce

1. create or open any php file
2. input "ret" anywhere
3. wait autocomplete menu popuped
4. press "Enter" to select only option "return ...  Language Construct"
5. netbeans insert "return ;;;;;;;;"
6. the character ";"  will auto append infinity until press any key

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

microsoft windows 11

### JDK

jdk-17.0.2 -x64

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by fpiccinali** [comment] 2022-03-27 08:35
Issue comfirmed also on Kubuntu 20.04. 

```
Product Version: Apache NetBeans IDE 12.6
Java: 11.0.14; OpenJDK 64-Bit Server VM 11.0.14+9-Ubuntu-0ubuntu2.20.04
Runtime: OpenJDK Runtime Environment 11.0.14+9-Ubuntu-0ubuntu2.20.04
System: Linux version 5.4.0-105-generic running on amd64; UTF-8; fr_FR (nb)
```

**Comment by Chris2011** [comment] 2022-04-22 14:52
Yeah but for me it happened with this steps:

* Type ret, wait for code completion
* Hit enter on ret
* return; will be inserted
* code completion pops up again and still shows return
* hit enter will return another return with ; because the word before will be deleted, but not the semicolon after it.

**Comment by Chris2011** [comment] 2022-04-22 14:56
If you look closer there is this in the code completion "return ;" so there is a space between return and the last semicolon. I believe that there is somehow a problem that after the space the code completion comes up again to write the correct return value but the space will not added. Just guessing.

**Comment by junichi11** [comment] 2022-05-27 06:52
Reproducible. Thank you for reporting it.

**Comment by junichi11** [comment] 2022-05-27 13:06
Related to this: https://github.com/apache/netbeans/pull/3290

@mbien Could you please have a look at this?

**Comment by mbien** [comment] 2022-05-27 13:10
@junichi11 i can try, but i don't know a lot about the PHP editor.

**Comment by junichi11** [comment] 2022-05-27 13:20
@mbien Maybe, I don't think this is related to the PHP editor although I could be wrong. It seems that CC is invoked infinitely with #3290.

**Comment by mbien** [comment] 2022-05-27 13:34
@junichi11 as I said, I take a look but all the PR did was to show the completion again under certain conditions. It reverted parts of https://github.com/apache/netbeans/commit/a9871c5085106f1ffd6c1c7ec594774185cf69d6. The question is: why is ";" a valid completion?

**Comment by mbien** [comment] 2022-05-27 13:50
what is the expected behavior? it should complete `ret` into `return`? With or without semicolon?

**Comment by junichi11** [comment] 2022-05-27 13:54
> The question is: why is ";" a valid completion?

Because CC item uses the following template:
https://github.com/apache/netbeans/blob/ea62da490f933d1a4d51abd53dcbf9956035ecaf/php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCompletionItem.java#L2013-L2033

I realized another problem. Maybe this case is also invoked CC again.
This problem also doesn't occur after I comment-out that change.
![netbeans-3805-cc](https://user-images.githubusercontent.com/738383/170712707-849ac3b2-0c80-4c63-8c21-48d6ad4a16cd.gif)

```php
interface A {}
class Something implements A{
}
```

**Comment by junichi11** [comment] 2022-05-27 14:02
> what is the expected behavior? it should complete `ret` into `return`? With or without semicolon?

Exprected:
With semicolon(`return^;`) :`^` means the caret
![netbeans-gh-3805-correct](https://user-images.githubusercontent.com/738383/170714530-a7761fff-dbae-4e47-8e58-7d9f00064b18.gif)

Actual:
![netbeans-gh-3805-incorrect](https://user-images.githubusercontent.com/738383/170714604-6ba5b471-1d09-47e6-9f92-ac59ad4637ff.gif)

**Comment by mbien** [comment] 2022-05-27 14:21
`return;` is inserted, after that, the next completion is ";" for some reason. Since its the only completion it is automatically inserted without showing the menu, right after `return`, this never ends since the situation does not change.

You can replicate the same issue without #3290, just keep pressing `ctrl+space`, it will keep inserting ";".

some thoughts:
 is the cursor position correct? should it be before the semicolon? The java editor places it behind the semicolon if there is no parameter, if there is a return paramenter, it does not set the semicolon, just a space after `return`. Both situations "finish" completions and don't cause infinite loops.

**Comment by junichi11** [comment] 2022-05-27 14:30
> is the cursor position correct?

Correct. User may return a value: `return $somethig;`

**Comment by mbien** [comment] 2022-05-27 14:41
in that case it should not add the semicolon yet, just a space after return. If there is no param it should add "return;" and put the cursor behind ";", otherwise the cycle won't end.

The problem here is that the completion does not change the situation, you can keep pressing ctrl+space and get the same completion automatically inserted since the semicolon is on the right side of the cursor and does not affect the result.

**Comment by junichi11** [comment] 2022-05-27 14:58
> The problem here is that the completion does not change the situation, you can keep pressing `ctrl+space` and get the same completion automatically inserted since the semicolon is on the right side of the cursor and does not affect the result.

It's a user's behavior. I think the problem is CC is invoked automatically again...

@tmysik What do you think?

**Comment by tmysik** [comment] 2022-05-27 15:45
Uff, really hard to say... will try to look into this problem a bit later.

**Comment by junichi11** [comment] 2022-05-28 00:10
PHP is not Java... 
```php
// the following function may return a value or may not return anything
// PHP can declare the function without return types
function foo() {
    return 1;
    // return;
}
```
I don't think NetBeans is IDE for only Java... 
We should fix the editor without breaking the existing behavior of other languages.

**Comment by mbien** [comment] 2022-05-28 11:17
> PHP is not Java...

indeed, but we can try to learn from it. PHP functions don't contain sufficient information in the declaration to allow the IDE to fully complete the return statement. An incomplete return statement is just like the bar method https://github.com/apache/netbeans/issues/3805#issuecomment-1139684802, (just without the space since the IDE can't guess that for PHP). The java editor does not add the semicolon there, the PHP editor probably shouldn't either. 
Maybe there should be two completion items for the `return` keyword. 
- One for `return;${cursor}` 
- and one for `return ${invokeCompletion}`.

But that is just an idea, as i mentioned twice already, I have limited knowledge of the PHP editor.

> I don't think NetBeans is IDE for only Java...

correct. Who claimed anything else?

> We should fix the editor without breaking the existing behavior of other languages.

i have a draft pr pending which mitigates the symptom a bit in situations when completions are not behaving well (e.g if they keep looping when pressing ctrl+space). But i have to test a bit more to make sure it doesn't affect other languages (yes, other than PHP and Java ;)) and more complex templates. Essentially having to test that the behavior of NB <12.2  is still there and also that #2519 works (without causing the regression added by the same PR).

**Comment by junichi11** [comment] 2022-05-30 02:21
I hope that this problem is fixed by the Editor.
It has worked for a long time as the expected behavior in the PHP editor until that change is included.

> The java editor does not add the semicolon there, the PHP editor probably shouldn't either.

"PHP is not Java..." and "I don't think NetBeans is IDE for only Java..." mean this...
Please imagine, when I fix something for the PHP feature in the Editor, the Java editor feature is broken. What do you think if I say "The PHP editor does not ... , the Java editor shouldn't ...."?

**Comment by tmysik** [comment] 2022-05-30 14:46
@junichi11 @mbien 

I just read all the comments here, and I think that you both are right. I mean, the change in the editor caused this unwanted behavior in the PHP support, however, perhaps the PHP CC could be improved (but we have no idea, how many other plugins could be also _broken_ by this change; personally, I expect not many).

Junichi, I quite like this idea:

> Maybe there should be two completion items for the return keyword.
>
> One for return;${cursor}
> and one for return ${invokeCompletion}

What do you think? Do you see any possible problem if we change it?

**Comment by junichi11** [comment] 2022-05-31 04:09
> how many other plugins could be also _broken_ by this change

My concern is this. Invoking CC infinitely is risky, I think... The client-side does not know anything about whether the template has a problem. 
So, we can use unexpected templates for the current implementation of the editor accidentally easily.  

@mbien I guess we should handle it in the Java editor. The Java editor should know the context. So, please try to invoke CC again from the Java editor if needed instead of fixing the editor.

> What do you think? Do you see any possible problem if we change it?

Probably, there is no problem with this case(return), I suppose. 
However, at least, we have a problem other than this case(return). (The popup window is not hidden until we press the ESC key.)
We have to investigate the other cases whether it works correctly. I want to avoid it...
As I wrote above, maybe this editor's change is risky because the template usage is restricted.

**Comment by mbien** [comment] 2022-05-31 11:54
you can help testing #4165 if you want.

**Comment by junichi11** [comment] 2022-06-02 06:09
I was misunderstanding. I thought @mbien is fixing a Java issue, sorry.

**Comment by junichi11** [comment] 2022-06-03 06:16
I've verified this doesn't occur with #4165.

**Comment by mbien** [comment] 2022-06-18 17:59
going to merge the PR soon which will automatically close this issue too since they were linked. 

This won't fix the php completion for "return" itself (if you keep pressing ctrl+space the editor will keep inserting ";".  It basically removes the main symptom which automated that loop :) The remaining issue is probably fairly minor - I don't think many users will notice.

**Closed** 2022-06-18 18:00 UTC
Labels: kind:bug, PHP, Editor
