### ISSUE TITLE
Netbeans 14 java.lang.NoClassDefFoundError exception

### ISSUE THREAD

**Issue by searles1250** [apache/netbeans#4538] opened 2022-08-26 00:57 UTC
### Apache NetBeans version

Apache NetBeans 14

### What happened

Netbeans 14 generates the error during startup. This does not occur with a parallel Netbeans 13 installation. Changing permissions on the designated jna file does not fix the issue.

java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: C:\Users\searl\AppData\Local\Temp\jna-109310665\jna4494228203172769567.dll: Access is denied [in thread "On Start/Stop"]
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:1979)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1019)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at org.netbeans.modules.masterfs.watcher.windows.WindowsNotifier.<clinit>(WindowsNotifier.java:107)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341)
	at java.base/java.lang.Class.newInstance(Class.java:677)
	at org.openide.util.lookup.implspi.SharedClassObjectBridge.newInstance(SharedClassObjectBridge.java:41)
	at org.openide.util.lookup.MetaInfServicesLookup$Item.getInstance(MetaInfServicesLookup.java:490)
	at org.netbeans.modules.masterfs.watcher.Watcher.getNotifierForPlatform(Watcher.java:456)
	at org.netbeans.modules.masterfs.watcher.Watcher.<init>(Watcher.java:66)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341)
	at java.base/java.lang.Class.newInstance(Class.java:677)
	at org.openide.util.lookup.implspi.SharedClassObjectBridge.newInstance(SharedClassObjectBridge.java:41)
	at org.openide.util.lookup.MetaInfServicesLookup$Item.getInstance(MetaInfServicesLookup.java:490)
	at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:397)
	at org.openide.util.lookup.ProxyLookup.lookup(ProxyLookup.java:281)
	at org.netbeans.modules.masterfs.watcher.Watcher.ext(Watcher.java:70)
	at org.netbeans.modules.masterfs.watcher.Watcher.isEnabled(Watcher.java:76)
	at org.netbeans.modules.masterfs.Installer.run(Installer.java:31)
Caused: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.Structure.setAlignType(Structure.java:291)
	at com.sun.jna.Structure.<init>(Structure.java:208)
	at com.sun.jna.Structure.<init>(Structure.java:204)
	at com.sun.jna.Structure.<init>(Structure.java:191)
	at com.sun.jna.Structure.<init>(Structure.java:183)
	at org.netbeans.core.network.proxy.windows.WindowsNetworkProxyLibrary$ProxyConfig.<init>(WindowsNetworkProxyLibrary.java:36)
	at org.netbeans.core.network.proxy.windows.WindowsNetworkProxyLibrary$ProxyConfig$ByReference.<init>(WindowsNetworkProxyLibrary.java:37)
	at org.netbeans.core.network.proxy.windows.WindowsNetworkProxy.getNetworkProxySettings(WindowsNetworkProxy.java:47)
	at org.netbeans.core.network.proxy.NetworkProxyReloader.reloadNetworkProxy(NetworkProxyReloader.java:68)
	at org.netbeans.core.network.proxy.NbProxySelector.lambda$new$0(NbProxySelector.java:58)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### How to reproduce

All I need to do to reproduce the error is to restart the IDE
[messages.log](https://github.com/apache/netbeans/files/9428972/messages.log)
.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 10 Pro Build 19044.1889

### JDK

jdk18.0.2.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

This happens every time Netbeans 14 is launched.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by searles1250** [comment] 2022-09-03 02:17
I resolved the error by resetting my operating system after identifying the issue as a serious permissions conflict.

**Comment by neilcsmith-net** [comment] 2022-09-03 08:40
Still seems slightly odd that it failed on loading an extracted JNA library - cc. @matthiasblaesing

**Comment by matthiasblaesing** [comment] 2022-09-03 17:08
Indeed for NetBeans this codepath should not be hit. If permissions were somehow messed with though, the file might indeed be unreadable and thus explain why the "load from classpath" route is taken. Why that fails I can't explain, though if permissions are wrong enough, extraction to temp might also prevent reading the file. For Linux the explanation would be easy if execution folder and java temp dir are mounted noexec.

Closing this as @searles1250 indicated, that the problem is solved.

**Closed by matthiasblaesing** 2022-09-03 17:08 UTC
Labels: kind:bug, needs:triage
