### ISSUE TITLE
@bottom-center in html style not recognized

### ISSUE THREAD

**Issue by fcorneli** [apache/netbeans#3606] opened 2022-02-14 21:10 UTC
### Apache NetBeans version

Latest release

### What happened

NetBeans 12.6 editor gives a red warning on `@bottom-center` within the following HTML file:
```html
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style>
            @page {
                @top-center {
                    content: element(top);
                }
                @bottom-center {
                    content: element(bottom);
                }
            }
        </style>
        <title>test</title>
    </head>
    <body></body>
</html>
```
with the error message detail: `Unexpected token BOTTOMCENTER_SYM not found.`

### How to reproduce

Open the above file within NetBeans.

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Mac OS 12.2

### JDK

17.0.1+12-LTS-39

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Would be nice if someone could push a fix for this in 13...

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment] 2022-02-15 06:15
I can confirm, that the parser bails out when parsing the construct (even when not embedded into HTML).

13 is already in the process to being released and only open for release critical fixes, this is not a regression and CSS for print is not the main use-case. Sorry, but this feature won't be supported in 13. If anyone wants to look at this for 14, the right place to start is `ide/css.lib`. The grammar is in the `Css3.g` file in the `org.netbeans.modules.css.lib` package. After changing the grammar, the lexer and parser have to be regenerated (see the `build.xml` of that module for that).

A trivial test is:

```java
    public void testX() {
        assertParses(" @page {\n" +
"                @top-center {\n" +
"                    content: element(top);\n" +
"                }\n" +
"                @bottom-center {\n" +
"                    content: element(bottom);\n" +
"                }\n" +
"            }", true);
    }
```

**Comment by matthiasblaesing** [comment] 2022-02-15 19:36
I rechecked the grammar - it already supports the syntax, errors are generated from the CSS verifier. The CSS Generated Content module was extended by the element function, which is not yet supported.

**Comment by matthiasblaesing** [comment] 2022-02-17 18:36
@fcorneli please point to a real use-case. https://caniuse.com/?search=element gives me some vague support in firefox, but overall it seems to be unsupported. You can reduce the error reporting if you fix the grammar to:

```
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style>
            @page {
                @top-center {
                    content: element(top);
                };
                @bottom-center {
                    content: element(bottom);
                }
            }
        </style>
        <title>test</title>
    </head>
    <body></body>
</html>
```

Without a real specification it is discussable, whether or not, if that is correct. I'm inclined to close this issue as "not a bug".

**Comment by fcorneli** [comment] 2022-02-17 19:12
We use this as part of a template to be processed by:
https://www.thymeleaf.org
and
https://github.com/danfickle/openhtmltopdf
to generate a PDF.

The ";" indeed removes the warning, and keeps openhtmltopdf happy. Thanks!

**Comment by matthiasblaesing** [comment] 2022-02-19 17:31
@fcorneli please have a look at the PR #3642. It does not fix all issues, but should make parsing of the contents of @page declarations more stable. There is still no support for "content: element(...)", but at least to parse now works and you just get warnings.

If you need a prebuild binary, you can download it here: https://doppel-helix.eu/NetBeans-dev-dev-293093d9e96fa3d0bcfb238a5d16228138678062-release.zip

**Closed** 2022-02-26 13:36 UTC
Labels: kind:feature, Contribution welcome
