### ISSUE TITLE
New Servlet template still uses Javax instead of Jakarta

### ISSUE THREAD

**Issue by ekotze** [apache/netbeans#6156] opened 2023-07-05 19:29 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

The following code gets generated when creating a new servlet with javax in. 
The fix is to change it to jakarta.

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

### How to reproduce

New FIle - Web - Servlet
Choose package and continue.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10 version 22H2

### JDK

jdk-17.0.7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

https://tomee.apache.org/javax-to-jakarta.html
From javax to jakarta namespace

### Are you willing to submit a pull request?

No

**Comment by javierllorente** [comment] 2023-08-06 10:09
Duplicate of #4828

**Comment by matthiasblaesing** [comment] 2024-01-23 18:59
Please see referenced PR for a suggested change. Please test the nightly build available from the checkspage of the PR and report back here:

https://github.com/apache/netbeans/actions/runs/7629925346

or directly:

https://github.com/apache/netbeans/actions/runs/7629925346/artifacts/1189554828

The build is available for the next 5 days.

**Closed** 2024-02-24 11:07 UTC
Labels: kind:bug, Java EE/Jakarta EE, needs:triage
