### ISSUE TITLE
Displayed a Warning After Attempting to Run Apache Netbeans From Gnome-Terminal (Ubuntu 24.04)

### ISSUE THREAD

**Issue by EaganFarlin** [apache/netbeans#7695] opened 2024-08-25 13:02 UTC
### Apache NetBeans version

Apache NetBeans 22

### What happened

The following is my terminal's console logs. It showed a WARNING and stated I should consider reporting this to the maintainers. Perhaps this is a minor issue the developers already know about, but I decided to report it just in case this was something substantial.

$ /usr/bin/netbeans
WARNING: package com.apple.eio not in java.desktop
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package com.apple.laf not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/usr/lib/apache-netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

### Language / Project Type / NetBeans Component

Apache Netbeans Ubuntu/Debian Apt-Get Application Running From Terminal

### How to reproduce

$ /usr/bin/netbeans

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 24.04 LTS x86_64 GNOME 46.0

### JDK

21.0.4

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by JoachimRohde** [comment] 2024-08-25 15:46
Duplicate of https://github.com/apache/netbeans/issues/5747

**Closed** 2024-08-25 20:01 UTC
Labels: kind:bug, needs:triage

**Comment by EaganFarlin** [comment] 2024-08-26 04:16
I see, thank you for letting me know. I should have searched it up before creating a duplicate report.
