### ISSUE TITLE
Problea con supuestamente la verison 

### ISSUE THREAD

**Issue by davd211** [apache/netbeans#7373] opened 2024-05-10 18:51 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

cada vez que quiero agregar por ejemplo un main, le pongo el titulo y le doy a finish y no me carga el archivo se me queda todo en gris y me sale un mensaje de error. este en concreto. you can try to resolve the issue by reporting it, including a copy of the messages.log file as an attachment. The messages.log file is located in a specific folder.
[messages.log](https://github.com/apache/netbeans/files/15278841/messages.log)

### How to reproduce

![image](https://github.com/apache/netbeans/assets/149159001/c6d18c36-5e4d-4480-bc0b-087a4ecc30c6)

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 

### JDK

22

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment] 2024-05-10 18:57
Duplicate of #7245. TL;DR: NetBeans 21 is not compatible with JDK 22, please use JDK 21 with NB21.

Please use english for communication here.

**Closed by matthiasblaesing** 2024-05-10 18:57 UTC
Labels: kind:bug, needs:triage
