### ISSUE TITLE
Copy/Paste failure in Windows

### ISSUE THREAD

**Issue by omniprof** [apache/netbeans#7396] opened 2024-05-22 22:50 UTC
### Apache NetBeans version

Apache NetBeans 22 release candidate

### What happened

When text is selected from a source file in NetBeans it can be successfully pasted into a Windows program such as NotePad++ or Microsoft Word. A second selection of text copied from the source file in NetBeans and pasted into NotePad++ or Word will fail. There is a rare occasional situation where you may be able to paste one or two more times into Notepad++ or Word but it will always stop pasting after 3 pastes. The text that cannot be pasted into NotePad++ or Word can be pasted back into a source file in the NetBeans editor.

Further testing has uncovered that copying from Word and pasting into the NetBeans editor works. But when you copy from NetBeans into Word such that paste fails then you can no longer copy from Word into NetBeans. It pastes the last successful paste. 

### Language / Project Type / NetBeans Component

I assume this issue occurs in all project types as it relates to the editor. 

### How to reproduce

When text is selected from a source file in NetBeans it can be successfully pasted into a NotePad++ or Word document. A second selection of text from the source file in NetBeans to NotePad++ or Word may or may not be successful but will eventually fail. You must make a new selection each time and not paste the same selection more than once. You can always paste within NetBeans.

Close and reopen NetBeans, NotePad++ and Word for each test. Restarting NetBeans allows for at least a single paste from NetBeans into another application. Subsequent pasting will always fail eventually though more often happening when you select new text and try to paste it.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Windows 64 bit - IMPLEMENTOR="Oracle Corporation" JAVA_RUNTIME_VERSION="21.0.3+7-LTS-152" JAVA_VERSION="21.0.3" JAVA_VERSION_DATE="2024-04-16" LIBC="default"

### Apache NetBeans packaging

Own source build

### Anything else

I have run multiple tests and this behaviour is consistent. One fix/hack that did work in NetBeans 20 was to add:
-J-Dnetbeans.slow.system.clipboard.hack=false to the netbeans_default_options.
However, this no longer works in NetBeans 22 rc4.

This issue is significant as it makes using NetBeans to prepare class material extremely difficult. Needing to restart NetBeans to get a single paste into Word to work makes using NetBeans in this setting untenable.

Source Code Build Environment:

Version of java used to compile:
IMPLEMENTOR="Oracle Corporation"
JAVA_RUNTIME_VERSION="21.0.3+7-LTS-152"
JAVA_VERSION="21.0.3"
JAVA_VERSION_DATE="2024-04-16"
LIBC="default"

Version of ant used to build:
1.10.14

Version of NetBeans compiled:
22-rc4

BUILD SUCCESSFUL
Total time: 16 minutes 10 seconds

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2024-05-23 06:20
duplicate of https://github.com/apache/netbeans/issues/3962

**Closed by mbien** 2024-05-23 06:20 UTC
Labels: kind:bug, duplicate, UI, os:windows

**Comment by omniprof** [comment] 2024-05-23 13:10
Hi,

I am baffled at how this Windows issue remains opened yet without a path to
resolution. If the options fix continued to work it would be fine. It no
longer does. While it may duplicate a problem first discovered, in NB 13,
that the fix/hack no longer works makes this a new problem. I will have to
abandon NetBeans as most of what I do is preparing presentations or write
about programming.

I would be happy to look into this matter. I just need to know where in the
Editor's code Select/Copy/Paste/Cut is handled. Or, is the default
behaviour of Java exclusively responsible for these operations and
therefore there is no dedicated code? Has an update defeated or disabled
the fix/hack? There must be an event where this disconnects from Windows
and subsequently only works within the editor that could be identified.

Now a short story. A few years ago I had some issues with Arquillian when
teaching server side programming. I knew the developers at RedHat and they
made numerous suggestions. Eventually I resolved the issue. In a casual
discussion with these developers they revealed that they did not have a
single Windows machine in their office. They had never observed Arquillian
running on Windows. So, may I ask, is anyone who is a committer to NetBeans
working on Windows rather than Linux or MacOS?

I will now crawl back under my rock,

Ken Fogel

**Comment by geertjanw** [comment] 2024-05-23 13:14
You've been pointed to the equivalent issue for IntelliJ IDEA in the past. Are you baffled there, too? Or do you think it's something that the tools can't solve since it's more likely a JDK-level thing, given that the issue is present in two Java Swing based IDEs?

**Comment by neilcsmith-net** [comment] 2024-05-23 13:22
Also, of the committers who do use or have access to Windows (which includes me) no-one can reproduce it!  It affects _some_ Windows users, but what makes this a problem for some and not for others remains a mystery.

**Comment by mbien** [comment] 2024-05-23 14:11
> So, may I ask, is anyone who is a committer to NetBeans working on Windows rather than Linux or MacOS?

speaking for myself: I do avoid windows whenever I can. It still is the worst platform for sw development, file path limitations, [process arg length limitations](https://github.com/apache/netbeans/pull/7237/commits/15cbc0a4c17fa3621597b53dba9b8c184df1edf3) slow file systems in general etc. Not to mention that I had to press 11 times "no you can't have my data" the last time I installed it in vbox (the recent news there likely will be ads in the start menu doesn't help either).

So I have no plans to investigate a race condition on windows in my free time which I can't reproduce (yes i tried on win 10 and 11) and which could be influenced by any combination of antivirus or other addware which ships with a typical windows box.

But anyone is welcome to contribute, the linked issue has 36 participants with a severe lack of PRs.

**Comment by neilcsmith-net** [comment] 2024-05-23 17:42
Incidentally, quick search at the latest on the IntelliJ comparable issue found this https://github.com/JetBrains/JetBrainsRuntime/commit/16257c3de7e858c8da3e453548f290e33718372d  Which does point to it being a JDK bug.  Unfortunately, we're not in a position to patch our own JDK!

@omniprof once that change hits a release, try running NetBeans on top of the JetBrains Runtime JDK.  If that also addresses the issue in NetBeans, maybe we have the start of trying to find a workaround or pushing for a fix upstream.

**Comment by omniprof** [comment] 2024-05-23 17:50
I have discovered that it is possible to make copy/paste on Windows work after it fails if you have a second tab open in the editor. I am working out a consistent procedure to get copy/paste to work after it fails without restarting NetBeans. It is interesting that copy/paste in NetBeans between tabs never fails, even if it failed when copied outside of NetBeans.

Ken

________________________________

**Comment by wumpz** [comment] 2024-05-24 05:35
If this is a JDK bug, so why is only Netbeans Platform affected and no other Java program on my machine. And yes: all using the same Java installation (JDK 17 Temurin). 
Other programs with reliable Copy Paste:
* DBeaver
* JEdit
* some Java Swing Software of my own
* ... 

I did not try IntelliJ or Eclipse. 

However, all my Netbeans platform applications have the same problem.

**Comment by mbien** [comment] 2024-05-24 06:17
possibly for the same reason why I can't reproduce it at all

**Comment by wumpz** [comment] 2024-05-24 06:41
@mbien Possible. Maybe it's time to start writing this thing from scratch instead of poking into the existing implementation.

**Comment by neilcsmith-net** [comment] 2024-05-24 08:28
@wumpz sure, feel free to work on it! No-one currently contributing to this project can reproduce, so none of them is likely to _volunteer_ their time to chasing shadows.

Or you could try running with JBR as mentioned above and see if the issue is still reproducible or not. That JetBrains felt that they had to patch their JDK to fix a similar issue means that should at least be considered here.

**Comment by wumpz** [comment] 2024-05-27 12:07
@neilcsmith-net That's unfortunate, that nobody with an Apache Netbeans implementation expertise does experience this one.  Maybe you could at least someone willing to contribute with enough know how a good starting point, like classes, where to start, maybe ideas so far, ...     or maybe there is already something like that and I missed it.
