### ISSUE TITLE
Imports of records removed on file save

### ISSUE THREAD

**Issue by michael-rhoese** [apache/netbeans#3494] opened 2022-01-23 21:22 UTC
### Apache NetBeans version

Latest release

### What happened

I created 2 records and imported them in a class that is not located in the same package. Both imports are removed on file save automatically.
If I change the classes to a normal classes, the imports are not removed.

### How to reproduce

First record:
```java
public record Vertex(boolean start, Class<? extends Enum<?>> state, List<Link> outgoingLinks) {

    public static Vertex of(boolean start, Class<? extends Enum<?>> state) {
        return new Vertex(start, state, new LinkedList<>());
    }
}
```
Second record:
```java
public record Link(Enum<?> event, Vertex from, Vertex to, Method stateChangeFunction) {

    public static Link of(Enum<?> event, Vertex from, Vertex to, Method stateChangeFunction) {
        return new Link(event, from, to, stateChangeFunction);
    }
}
```

Add both (or one) as attributes to another class, that is not in the same package, and save the file.
```java
public class AnotherClazz{

    private Vertex vertex;

    private Link link;
}
```

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Windows 10 Pro 21H2

### JDK

OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment] 2022-01-24 09:35
reproducible in master (~13 rc 2).

some observations:
 - right click -> fix imports does work (by not removing anything)
 - refactor -> inspect/transform -> Unused imports does work (by not removing anything)
 - refactor -> inspect/transform -> Organize imports causes the issue
 - issue seems to be not caused by the on-save action itself

**Comment by mbien** [comment] 2022-01-24 10:00
i think i found the issue. PR in progress.

**Comment by neilcsmith-net** [comment] 2022-01-26 15:45
Thanks @mbien Fix is in rc2.  @michael-rhoese please give that a try https://lists.apache.org/thread/pg3ho8o8s2tfh3ys6705tt9bmkvwxfh6

Closing - GH seems to not be picking up this has made its way to master now.

**Closed by neilcsmith-net** 2022-01-26 15:45 UTC
Labels: kind:bug, Java
