### ISSUE TITLE
Module-info.java already exists.

### ISSUE THREAD

**Issue by JavacoderBrian** [apache/netbeans#4628] opened 2022-09-12 12:07 UTC
### Apache NetBeans version

Apache NetBeans 15

### What happened

In the process of creating a module-info.java in an existing project, the wizard stops at the end saying, The file module-info.java already exists.
![image](https://user-images.githubusercontent.com/2698503/189648619-a1122cbd-1c55-4c68-a1b2-e944301cf9d2.png)

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 11 Pro Version 10.0.22000 Build 22000

### JDK

OpenJDK 18.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Everytime

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-09-15 15:31
Well, that's annoying!  Can replicate.  The file does at least seem to be created correctly, even if you have to cancel the wizard to get to it.

**Comment by neilcsmith-net** [comment] 2022-09-15 15:42
Stack trace of the exception thrown -

```
WARNING [org.openide.WizardDescriptor]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.sun.tools.javac.util.List.get(List.java:490)
	at org.netbeans.modules.java.project.ui.NewJavaFileWizardIterator$AddRequiresDirective.run(NewJavaFileWizardIterator.java:265)
	at org.netbeans.modules.java.project.ui.NewJavaFileWizardIterator$AddRequiresDirective.run(NewJavaFileWizardIterator.java:254)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:675)
	at org.netbeans.api.java.source.JavaSource$1.run(JavaSource.java:665)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:454)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.api.java.source.JavaSource.runModificationTask(JavaSource.java:686)
	at org.netbeans.modules.java.project.ui.NewJavaFileWizardIterator.addRequires(NewJavaFileWizardIterator.java:249)
	at org.netbeans.modules.java.project.ui.NewJavaFileWizardIterator.instantiate(NewJavaFileWizardIterator.java:356)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1050)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:223)
	at org.openide.loaders.TemplateWizardIteratorWrapper.instantiate(TemplateWizardIteratorWrapper.java:135)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1605)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by neilcsmith-net** [comment] 2022-10-11 17:45
OK, this is caused by changes in javac.  I've got a fix for this and will post a PR tomorrow.

**Closed** 2022-10-15 16:24 UTC
Labels: kind:bug, Java, priority:high, Regression
