### ISSUE TITLE
Apache Netbeans 18 is damaged and can't be opened Ventura 13.4 intel

### ISSUE THREAD

**Issue by datb-com** [apache/netbeans#6052] opened 2023-06-07 09:49 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

Installing Apache Netbeans 18 from the dmg.  Installed fine on two mac M1 systems, but got a signing error, from the same dmg, on two mac Intel systems.   All running mac os Ventura 13.4.

<img width="260" alt="2023-06-07_10-45-15" src="https://github.com/apache/netbeans/assets/48554223/688c8045-8e5e-487d-89db-493a4114bf61">

### How to reproduce

Presumably get the Netbean 18 dmg: Apache-NetBeans-18-bin-macosx.dmg
My experience over 4 macs indicates that this might be an Intel vs M1 issue, so use an Intel mac for this test. 
Check the shasum 512 hash:
shasum -a 512 Apache-NetBeans-18-bin-macosx.dmg 
45ae189936973612cdaefca127f7664257081a3794c84c28213d395f5e3cf46910bafb6f1d89a0e2466c5dc35481a9acde1be4506cf55ff356a0404052529cdd  Apache-NetBeans-18-bin-macosx.dmg

Run the installer (works fine).
Run the resulting 'Apache NetBeans 18.app'

Get the error about it being damaged. 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

mac os Ventura 13.4

### JDK

ava version "17.0.5" 2022-10-18 LTS Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191) Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Repeatable. 

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment] 2023-06-07 11:09
Could you check if the community installer at https://www.codelerity.com/netbeans/ has the same issue.  That's built and signed using NBPackage, which we might also consider for the non-JDK bundling installer in NetBeans 19.

**Comment by uurazzle** [comment] 2023-06-21 15:52
Hi:

I don't believe this is an issue with distribution via .dmg. A .dmg file is a disk image file format commonly associated with macOS and don't see issues with other applications distributed using a disk image file, but probably an error during signing or software update process.

For reference, see the following Apple Developer documentation:

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues

`codesign -vvv --deep --strict /path/to/Apache\ NetBeans\ 18.app 
/path/to/Apache NetBeans 18.app: a sealed resource is missing or invalid
`

Or using GUI tool, [Apparency](https://mothersruin.com/software/Apparency/)

![image](https://github.com/apache/netbeans/assets/6226458/ecb6fe1c-2511-4845-9669-d3a59ea4ef9a)

The application or component appears to have been corrupted or tampered with since being signed. As such, the identity implied by the signing certificate is not reliable. This could be a result of the application being compromised at the point of download. Or it could simply be the result of errors occurring during signing, or in a software update process — the latter is depressingly common, even and especially for built-in macOS apps.

**Comment by uurazzle** [comment] 2023-06-22 17:14
Hi @neilcsmith-net,

Ok, I downloaded the "Apache-NetBeans-18.pkg" installer package.

And it appears it doesn't have the same signing issues as the distributed disk image.

For example...

```
codesign -vvv --deep --strict /Applications/Apache\ NetBeans.app 
/Applications/Apache NetBeans.app: valid on disk
/Applications/Apache NetBeans.app: satisfies its Designated Requirement
```

For example, with the GUI tool, [Apparency](https://mothersruin.com/software/Apparency/)

![image](https://github.com/apache/netbeans/assets/6226458/4f125f8a-e508-4a4b-8992-e34b8a8da49f)

**Comment by neilcsmith-net** [comment] 2023-06-23 13:38
Thanks @uurazzle - that's good to know.  I also downloaded Apparency and verified the two on my M1 test machine.

The NBPackage app bundle task and the scripts in the main repository have a different approach to finding libraries (inc. those bundled in JARs) to sign.  NBPackage also uses the hardened runtime.

https://github.com/apache/netbeans-nbpackage/blob/master/src/main/java/org/apache/netbeans/nbpackage/macos/MacOS.java
https://github.com/apache/netbeans-nbpackage/blob/master/src/main/java/org/apache/netbeans/nbpackage/macos/AppBundleTask.java

vs

https://github.com/apache/netbeans/blob/master/nbbuild/installer/mac/newbuild/commonfiles/signNativeBinaries.sh

I wondered if something had changed in the list of files, particularly if something just on x86_64, but that doesn't seem to be the case as far as I can tell.  Anyway, Apache NetBeans 17 also reports the same issue after installation.

It's curious that everything is passing notarization anyway.  Another potential issue in the ASF installer is the `populate_caches` script -

https://github.com/apache/netbeans/blob/master/nbbuild/installer/mac/newbuild/commonfiles/postinstall/populate_caches.sh

This seems to be trying to launch from the wrong location, and then writing to a file called `exiting` in the root of the app.  That might be breaking the signature?

> If the application bundle remained constant you can create your own package installer and it simply updates the previous version since the name/path is the same vs having to add additional scripting/workflow to remove the previous version name.

Yes, all the Codelerity installers are set to do in-place upgrades.  It seems the more sensible option now we're releasing every 3 months.

> Let me know if you need me to test anything else.

Thanks!  I'm going to check about using NBPackage to build a macOS bundle without JDK, and some testing of that would be useful.  If that works, this is another reason to consider using that for NetBeans 19.

**Comment by uurazzle** [comment] 2023-06-23 15:31
Hi @neilcsmith-net,

Ok, sounds good. Let me know if you want me to test anything when its ready.

**Comment by uurazzle** [comment] 2023-06-23 16:08
Hi @neilcsmith-net:

One other question, there appear two builds "Intel" and "Apple Silicon", but it appears that the "Apple Silicon" is a "Universal" build and can run on either architecture (i.e. "Intel" or "Apple Silicon").

If the build really is "Universal" then I would recommend changing the naming to "Universal" vs" Apple Silicon".

Then in environments with both system architectures, could just distribute that version to simplify management by only distributing one installer package vs two.

**Comment by neilcsmith-net** [comment] 2023-06-23 16:20
@uurazzle in which installer?  The community installers is currently limited to "Intel" because of the bundled JDK.  Actually, NBPackage needs to be updated to also support aarch64.  But we'll need different behaviour depending on whether there is a bundled JDK, and what architecture it is.  I'm not sure if there's a source of universal JDK?

**Comment by uurazzle** [comment] 2023-06-23 16:28
Hi @neilcsmith-net:

Sorry, you are correct this disk image is intel only. Nevermind, but would be nice to have it universal.

https://www.apache.org/dyn/closer.cgi/netbeans/netbeans-installers/18/Apache-NetBeans-18-bin-macosx.dmg

**Comment by geertjanw** [comment] 2023-06-23 16:48
Works for me in this context:

Product Version: Apache NetBeans IDE 18
Java: 20.0.1; OpenJDK 64-Bit Server VM 20.0.1+9
Runtime: OpenJDK Runtime Environment 20.0.1+9
System: Mac OS X version 13.4 running on x86_64; UTF-8; en_NL (nb)

**Comment by neilcsmith-net** [comment] 2023-06-29 15:42
@uurazzle just tried using NBPackage to build an installer without JDK - see https://github.com/codelerity/netbeans-installers/releases/tag/v18-test1

It's under a different app bundle ID for testing, and signed and notarized with Codelerity certificate still.  This might be a possibility for Apache installers for NB19 if it works better.

NBPackage needs an update to use universal architecture for the Swift launcher when there is no runtime, which I can take a look at if this seems a good way forward.

**Comment by uurazzle** [comment] 2023-06-29 16:43
Hi @datb-com:

Once you do the workaround for the damaged application (FInder -> CTRL+click select open)I believe it adds it to the privacy database on macOS.

You can try using the `tccutil` command to reset the database to get the prompt again for testing purposes.

`tccutil reset All <app.identifier>`

I haven't had time to test this myself, but an idea.

**Comment by datb-com** [comment] 2023-06-29 16:57
Update!  My colleage (on an M1) just had the same issue. 
The problem is I think when we copy the downloaded .dmg to Box, and then download it from Box it ends up presumably with different hidden flags.
The file downloaded from Box still passes the shasum check, so the actual file is not altered.   Presumably macOS applies some flags to the .app that gets installed from the .dmg ?

**Comment by neilcsmith-net** [comment] 2023-06-29 18:30
@datb-com could you also see if the installer linked in my previous comment fixes that issue for you?

**Comment by uurazzle** [comment] 2023-06-29 18:31
How about using the installer vs DMG? IMHO, the issue is the application signature as part of the backend application build process used to create the disk images NOT modifications of the disk images. I manage a ton of applications distributed via disk images and haven't seen this type of application signature due to using disk images vs other methods like installer package, etc.

**Comment by neilcsmith-net** [comment] 2023-07-01 09:47
I'm taking a look at updating NBPackage to build the Swift launcher with the architecture of the bundled JDK, and universal architecture if there is none.

I've updated the previously linked download - https://github.com/codelerity/netbeans-installers/releases/tag/v18-test1

It doesn't look like anyone downloaded the previous one, and there's been no feedback.  The ASF installer for NetBeans 19 _will not_ have this issue fixed unless we get some feedback on whether this works OK and is addressing the problem!

**Comment by datb-com** [comment] 2023-07-04 11:08
[Apache-NetBeans-18-universal.pkg](https://github.com/codelerity/netbeans-installers/releases/download/v18-test1/Apache-NetBeans-18-universal.pkg)
This worked on an M1 mac in which the published DMG didn't work.   And, my theory about it relating to having uploaded/downloaded the DMG to Box is proved incorrect.

**Comment by neilcsmith-net** [comment] 2023-07-04 17:54
@datb-com thanks for the feedback.  I've started a thread on dev@ list about this too.

**Comment by neilcsmith-net** [comment] 2023-08-10 13:20
I've just uploaded an ASF signed package of 19-rc4 to https://nightlies.apache.org/netbeans/candidate/installers/ Please help verify this before we move to this packaging for the NetBeans 19 release. Thanks!

**Comment by neilcsmith-net** [comment] 2023-08-30 11:32
This is hopefully resolved in NetBeans 19.  Please comment here if you see the problem again.

**Closed by neilcsmith-net** 2023-08-30 11:32 UTC
Labels: kind:bug, os:macos

**Comment by michaelajr** [comment] 2023-11-25 15:02
So what is the best way to install NetBeans 19 on Apple Silicon? I tried the community x86_64 installer - and white it does work on Apple silicon - NetBeans seems slow to start up (load modules) and initialize projects compared to the **Binaries (Platform Independent)** zip. Does that seem right, or am I just imagining it?

**Comment by michaelajr** [comment] 2023-11-25 15:24
Ah nvm... the .`pkg` installer seems to work fine.
