### ISSUE TITLE
Fail to Stop tomcat

### ISSUE THREAD

**Issue by doitsexy** [apache/netbeans#5746] opened 2023-03-30 07:20 UTC
### Apache NetBeans version

Apache NetBeans 17

### What happened

I want to restart tomcat in netbeans , but it  fails to stop, i must kill the background process with taskexplorer.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 专业版 22h2

### JDK

netbeans default JDK, tomcat JDK1.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by prushforth** [comment] 2023-06-01 23:59
I have this problem too!  I set my timeout to 10 seconds, so it doesn't go on and on, but it's an annoyance.

**Comment by asbachb** [comment] 2023-07-08 20:51
@doitsexy @Jaswindermehta @prushforth could you verify if this happens still in NetBeans 18? Which tomcat version you're using?

Could not reproduce this with NetBeans 18, Linux, tried tomcat 10.1.10 on Java 17 and tomcat 8.5.90 on Java 1.8

**Comment by prushforth** [comment] 2023-07-08 20:55
I upgraded to NB 18, tomcat 9.0.76, and no longer have the problem, java 11.

**Comment by mbien** [comment] 2023-07-09 18:55
sounds good. closing.

**Closed by mbien** 2023-07-09 18:55 UTC
Labels: kind:bug, Java EE/Jakarta EE, needs:triage

**Comment by MichaelCropper** [comment] 2023-12-12 00:16
It's clearly a quirky compatibility issue - Here's how I resolved it, by moving from Apache Tomcat 10 to Apache Tomcat 9 - https://stackoverflow.com/questions/77636590/apache-netbeans-19-cannot-stop-start-apache-tomcat-10-server-on-windows

The documentation is clearly lacking with this stuff, it's rather annoying. 

My specific example was with Apache NetBeans 19 and Apache Tomcat 10 (which didn't work...) then Apache Tomcat 9 (which did work).
