### ISSUE TITLE
Warning: package com.apple.eio not in java.desktop, terminally depreciated method in java.lang.System called

### ISSUE THREAD

**Issue by anongithub** [apache/netbeans#5967] opened 2023-05-19 18:34 UTC
### Apache NetBeans version

Apache NetBeans 17

### What happened

Installed NetBeans 17 using:
wget https://dlcdn.apache.org/netbeans/netbeans-installers/17/apache-netbeans_17-1_all.deb
sudo apt install ./apache-netbeans_17-1_all.deb

Running netbeans produces the following warning every time: 
WARNING: package com.apple.eio not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.netbeans.TopSecurityManager (file:/usr/lib/apache-netbeans/platform/lib/boot.jar)
WARNING: Please consider reporting this to the maintainers of org.netbeans.TopSecurityManager
WARNING: System::setSecurityManager will be removed in a future release

Given the instruction to consider reporting it, consider it reported.  

Setup:
Product Version: Apache NetBeans IDE 17
Java: 17.0.7; OpenJDK 64-Bit Server VM 17.0.7+7-Ubuntu-0ubuntu122.04.2
Runtime: OpenJDK Runtime Environment 17.0.7+7-Ubuntu-0ubuntu122.04.2
System: Linux version 5.15.90.1-microsoft-standard-WSL2 running on amd64; UTF-8; en (nb) (Windows 11 Pro on XPS15 9520)

### How to reproduce

Get XPS15 9520 with Windows 11 Pro
Install wsl2 Ubuntu 22.04.2
Install Java: 17.0.7; OpenJDK 64-Bit Server VM 17.0.7+7-Ubuntu-0ubuntu122.04.2
Install Netbeans 17:
wget https://dlcdn.apache.org/netbeans/netbeans-installers/17/apache-netbeans_17-1_all.deb
sudo apt install ./apache-netbeans_17-1_all.deb
execute: netbeans 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Linux version 5.15.90.1-microsoft-standard-WSL2 running on amd64; UTF-8; en (nb) [Windows 11 Pro 22H2 build: 22621.1485]

### JDK

 Java: 17.0.7; OpenJDK 64-Bit Server VM 17.0.7+7-Ubuntu-0ubuntu122.04.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

No.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2023-05-19 19:51
Duplicate of #5747

**Closed by matthiasblaesing** 2023-05-19 19:51 UTC
Labels: kind:bug, duplicate
