### ISSUE TITLE
java.lang.IllegalArgumentException: Key contains code point U+0000

### ISSUE THREAD

**Issue by maryam-yousefi-Canada** [apache/netbeans#6076] opened 2023-06-14 13:35 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

When I build the  java project, the process bar keeps ongoing and does not finish. There is an error message beside it. 
[messages.log](https://github.com/apache/netbeans/files/11746271/messages.log)

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

since yesterday it occurs every time I build the project 

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2023-06-15 08:11
```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.apache.tools.ant.module.bridge.impl.BridgeImpl$PostRun
java.lang.IllegalArgumentException: Key contains code point U+0000
	at java.prefs/java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:296)
	at org.apache.tools.ant.module.api.IntrospectedInfo$3.load(IntrospectedInfo.java:681)
	at org.apache.tools.ant.module.AntSettings.getCustomDefs(AntSettings.java:119)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl$PostRun.run(BridgeImpl.java:443)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
```
duplicate of #5147, #5633

**Comment by mbien** [comment] 2023-06-15 09:05
all reported issues, including this old one are on windows:
https://bz.apache.org/netbeans/show_bug.cgi?id=271652

**Comment by mbien** [comment] 2023-06-15 09:15
reading @lkishalmi [comment](https://issues.apache.org/jira/browse/NETBEANS-3284?focusedCommentId=16961075&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16961075) makes me think we should change the config importer to only import "recent" configs. E.g N-2, 

I think this would have avoided several issues by now if we would have restricted it a while ago.

**Comment by mbien** [comment] 2023-06-15 09:16
here the JDK change: https://bugs.openjdk.org/browse/JDK-8075156

**Comment by FernandoY2203** [comment] 2023-06-15 16:37
I had the same problem and this question on stack helped me: 
https://stackoverflow.com/questions/51244824/exception-creating-new-maven-project-in-apache-netbeans9
I found a .properties file in that path
C:\Users\[your username]\AppData\Roaming\NetBeans\16\config\Preferences\org\apache\tools\ant\module
containing lines full of \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000
So I removed the file, restarted netbeans and the error was resolved.

**Comment by mbien** [comment] 2023-06-19 06:31
@maryam-yousefi-Canada It would be good to know if there are more corrupted properties files in your config. Could you run this utility which scans all property files of your netbeans configs for invalid code points?

You can simply paste it into a maven project and run it on JDK 11+, thanks!

```java
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

public class NbConfigScanner {

    public static void main(String[] args) throws IOException {
        System.out.println(Runtime.version());
        Path path = Path.of("C:\\Users\\myousefi\\AppData\\Roaming\\NetBeans");
        try (Stream<Path> configs = Files.list(path)) {
            configs.filter(Files::isDirectory)
                   .sorted()
                   .forEach(NbConfigScanner::check);
        }
    }

    private static void check(Path config) {
        System.out.println("checking: "+config);
        try (Stream<Path> stream = Files.walk(config)) {
            stream.filter(path -> path.getFileName().toString().endsWith(".properties"))
                  .forEach(path -> {
                        try {
                            if (Files.readString(path).indexOf('\u0000') != -1) {
                                System.out.println("WARNING: "+path+" contains invalid code points");
                            }
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        }
                  });
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
```

**Closed** 2023-07-04 16:24 UTC
Labels: kind:bug, os:windows, Ant
