### ISSUE TITLE
It's impossible to start GlassFish 6.2.5 from the Services tab of NetBeans

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#4841] opened 2022-10-22 09:02 UTC
### Apache NetBeans version

Apache NetBeans 16 release candidate

### What happened

Right-click on GlassFish entry > Start.
I got the message "Error: Could not find or load main class Eclipse\glassfish6.2.5\glassfish6\glassfish.lib.grizzly-npn-api.jar
Caused by: java.lang.ClassNotFoundException: Eclipse\glassfish6.2.5\glassfish6\glassfish.lib.grizzly-npn-api.jar" 

If I start GlassFish with asadmin outside NetBeans. Then, in NetBeans I can open the GlassFish entry and see the log and the admin console of the server.
Then, if I launch a run of a Web application  from NetBeans, it stops GlassFish. Very annoying if I want to deploy a new version of the application from NetBeans (with Run).

### How to reproduce

Just "Add server" with GlassFish 6.2.5 in the Services tab of NetBeans.
In the context menu of the new server, choose "Start".

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Family 64-bit, version 21H2

### JDK

11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment] 2023-01-14 12:47
I can't reproduce this with NB16 GA.
 - I registered a new GF 6.25 server (downloaded via wizard)
 - started via right click
 - no exception occurred

**Comment by richard-grin** [comment] 2023-01-14 13:13
Did you registered the "platform" version or the "web profile" version?

**Comment by richard-grin** [comment] 2023-01-14 13:19
I have just tried and I get the same error message with GlassFish 6.2.5, Web profile version, and this configuration:
Product Version: Apache NetBeans IDE 16
Java: 11.0.16.1; OpenJDK 64-Bit Server VM 11.0.16.1+1
Runtime: OpenJDK Runtime Environment 11.0.16.1+1
System: Windows 11 version 10.0 running on amd64; Cp1252; fr_FR (nb)
User directory: C:\Users\grin\AppData\Roaming\NetBeans\16
Cache directory: C:\Users\grin\AppData\Local\NetBeans\Cache\16

**Comment by mbien** [comment] 2023-01-14 13:27
NetBeans downloads the platform version which is the full version looks like. I just registered gf 6.2.5 web profile manually and it worked too.

```
Launching GlassFish on Felix platform
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@4b9ae2e9 in service registry.
#!## LogManagerService.postConstruct : rootFolder=/home/mbien/dev/servers/glassfish_6_25_web/glassfish
#!## LogManagerService.postConstruct : templateDir=/home/mbien/dev/servers/glassfish_6_25_web/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/home/mbien/dev/servers/glassfish_6_25_web/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/home/mbien/dev/servers/glassfish_6_25_web/glassfish/domains/domain1/config/logging.properties
  Running GlassFish Version: Eclipse GlassFish  6.2.5  (build 6.x-b66-g0159b68 2022-02-12T17:39:59+0000)|#]
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter|#]
  Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.|#]
  Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.|#]
  Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.|#]
  Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry|#]
  Authorization Service has successfully initialized.|#]
  Grizzly Framework 3.0.1 started in: 12ms - bound to [/0.0.0.0:8080]|#]
  Grizzly Framework 3.0.1 started in: 2ms - bound to [/0.0.0.0:8181]|#]
  Grizzly Framework 3.0.1 started in: 1ms - bound to [/0.0.0.0:4848]|#]
  Grizzly Framework 3.0.1 started in: 1ms - bound to [/0.0.0.0:3700]|#]
  Eclipse GlassFish  6.2.5  (6.x-b66-g0159b68 2022-02-12T17:39:59+0000) startup time : Felix (1,070ms), startup services(521ms), total(1,591ms)|#]
  Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@344b8190 as OSGi service registration: org.apache.felix.framework.ServiceRegistrationImpl@6a078481.|#]
  Skipping registration of inhabitant for service reference [org.osgi.service.metatype.MetaTypeProvider] as the service object could not be obtained.|#]
  JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://longbow:8686/jndi/rmi://longbow:8686/jmxrmi|#]
  HV000001: Hibernate Validator 7.0.2.Final|#]
  Grizzly Framework 3.0.1 started in: 7ms - bound to [/0.0.0.0:8080]|#]
  Grizzly Framework 3.0.1 started in: 0ms - bound to [/0.0.0.0:8181]|#]
  Grizzly Framework 3.0.1 started in: 22ms - bound to [/0.0.0.0:8181]|#]
  Grizzly Framework 3.0.1 started in: 1ms - bound to [/0.0.0.0:8080]|#]
  visiting unvisited references|#]
  Created HTTP listener http-listener-1 on host/port 0.0.0.0:8080|#]
  Created HTTP listener http-listener-2 on host/port 0.0.0.0:8181|#]
  Created HTTP listener admin-listener on host/port 0.0.0.0:4848|#]
  Created virtual server server|#]
  Created virtual server __asadmin|#]
  Setting JAAS app name glassfish-web|#]
  Virtual server server loaded default web module |#]
  Java security manager is disabled.|#]
  Entering Security Startup Service.|#]
  Loading policy provider org.glassfish.exousia.modules.locked.SimplePolicyProvider.|#]
  Security Service(s) started successfully.|#]
  visiting unvisited references|#]
  visiting unvisited references|#]
  visiting unvisited references|#]
  Listening to REST requests at context: /management/domain.|#]
  Initializing Mojarra 3.0.1 for context ''|#]
  Loading application [__admingui] at [/]|#]
  Loading application __admingui done in 2,394 ms|#]
  Context path from ServletContext:  differs from path from bundle: /|#]

```

**Comment by richard-grin** [comment] 2023-01-14 13:50
OK perfect. I will reload NetBeans 16 and GlassFish 6.2.5 (perhaps something have changed since I installed them some time ago) and I hope it will work, else I will keep you informed.
Thanks mbien.

**Comment by mbien** [comment] 2023-01-14 13:58
going to close this. feel free to reopen if it happens again.

**Closed by mbien** 2023-01-14 13:58 UTC
Labels: kind:bug, Java EE/Jakarta EE, needs:triage
