### ISSUE TITLE
Apache NetBeans 18 macOS Will NOT Properly Launch Due to App Signing Issue

### ISSUE THREAD

**Issue by uurazzle** [apache/netbeans#6104] opened 2023-06-20 19:58 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

On macOS Apache NetBeans 18 and previous versions like 17.x will display the following error:

"Apace NetBeans XX" is damaged and can't be opened.

You can work around the issue but CTL+click, but needs to be fixed

### How to reproduce

Try running the macOS version for a new user or new installed system and you will see error if you didn't using the CTRL click workaround.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS 13.4

### JDK

openjdk 11.0.8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The app or component appears to have been corrupted or tampered with since being signed. As such, the identity implied by the signing certificate is not reliable. This could be a result of the app being compromised at the point of download. Or it could simply be the result of errors occurring during signing, or in a software update process — the latter is depressingly common, even and especially for built-in macOS apps.

You need an fully functional  Apple developer account. Then you can follow this information: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

The above link is the global procedure, but there is a specific topic with clean illustrated how to at the following URL: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW2

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2023-06-21 09:14
duplicate of #6052, please take a look at @neilcsmith-net's comment there.

**Closed** 2023-09-07 10:39 UTC
Labels: kind:bug, duplicate, os:macos
