### ISSUE TITLE
Rename refactoring fails occasionally

### ISSUE THREAD

**Issue by swpalmer** [apache/netbeans#5496] opened 2023-02-15 04:39 UTC
### Apache NetBeans version

Apache NetBeans 16

### What happened

I attempted to rename a method and the following error appeared:

Module Java Refactoring threw java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null. Please report a bug against Java Refactoring module and attach your var/log/messages.log.

[messages.log](https://github.com/apache/netbeans/files/10739295/messages.log)

### How to reproduce

This doesn't always happen and I don't know how to trigger it.

### Did this work correctly in an earlier version?

Apache NetBeans 16

### Operating System

macOS 13.2.1

### JDK

JDK 17.0.6

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by swpalmer** [comment] 2023-02-16 01:51
Another message that happens when rename refactoring fails:

"The original element being refactored is not available. It was deleted or significantly changed. Usages cannot be collected."

That is a lie.

**Comment by mbien** [comment] 2023-02-17 10:51
looking at the log:
```
java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null
	at com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1576)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1799)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:447)
	at com.sun.tools.javac.tree.TreeScanner.visitExec(TreeScanner.java:219)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1586)
	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:447)
...
```
might be a duplicate of #3725

**Closed** 2024-04-11 08:37 UTC
Labels: kind:bug, duplicate, Java, nb-javac
