### ISSUE TITLE
Netbeans freeze on file save

### ISSUE THREAD

**Issue by llakazs** [apache/netbeans#4515] opened 2022-08-18 10:50 UTC
### Apache NetBeans version

Apache NetBeans 14

### What happened

Modifying and saving a file with syntax error sometimes freezes Netbeans (it becomes completely unresponsive, and i have to kill the process from the operating system).
The exception in the provided log appears after changing the content of the file. It looks like the issue in this case is related to a syntax error in the file (calling a function on void in generateSignature function). When the indexing starts it throws an exception and saving the file afterwards causes the IDE to freeze completely.
[netbeans-log.tar.gz](https://github.com/apache/netbeans/files/9372208/netbeans-log.tar.gz)
 

### How to reproduce

1. Start netbeans
2. Change anything in the file
3. Save the file

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Debian 10 buster with KDE (4.19.249-2)

### JDK

oracle java 1.8.0_331, openjdk 1.8.0, openjdk 11.0.16, openjdk 17.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I first encountered this bug when Netbeans 13 came out and i tried to upgrade from 12.6. I wasn't able to catch a reproducible case so i just went back to 12.6 instead. Later when i switched to Netbeans 14, the bug appeared again in multiple projects, in seemingly random cases.

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by OnyxianSoul** [comment] 2022-09-12 13:48
I'm facing the same issue.

**Comment by negora** [comment] 2022-09-24 22:32
Same problem here.

I'm using Debian 11 (Bullseye) GNU/Linux and OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1).

**Comment by mbien** [comment] 2022-09-27 06:38
@llakazs @negora @OnyxianSoul are any "on save" actions enabled (Options -> Editor -> On Save)?

**Comment by llakazs** [comment] 2022-09-27 07:19
Yes, remove unused imports is on.
I turned off organize imports a few months ago. The bug appeared before and after that too, so it probably does not affect it.

**Comment by negora** [comment] 2022-09-27 08:30
In my case I've enabled the following options (for Java files):

* Remove trailing white space from: all lines.
* Remove unused imports.
* Organize imports.

I can try to disable some options. However, I think that the *bug* appears before saving: as soon as there is certain type of error, the code loses highlighting and you know, beforehand, that the save will freeze the IDE.

One type of error that seems to trigger this *bug* is when you have a Java class placed in a package whose fully qualified name doesn't match the name that appears in the `package` clause of the class. I'll try to reproduce the *bug* when I've some spare time.

**Comment by mbien** [comment] 2022-09-30 05:00
ok thanks for the info. going to close this issue as duplicate of #4054 since it has a reproducer there.

**Closed by mbien** 2022-09-30 05:00 UTC
Labels: kind:bug, duplicate, needs:triage
