### ISSUE TITLE
Code Template fails with NullPointer

### ISSUE THREAD

**Issue by atehrani** [apache/netbeans#4819] opened 2022-10-19 19:26 UTC
### Apache NetBeans version

Apache NetBeans 15

### What happened

When I try to use code templates using keywords, for example `sout` which should automatically expand to `System.out.println()` it fails with a NPE.
[messages.log](https://github.com/apache/netbeans/files/9823589/messages.log)

### How to reproduce

Use `sout` and see the NPE. This occurs when using this plugin https://funfried.github.io/externalcodeformatter_for_netbeans/

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Mac OS X version 12.6 running on x86_64

### JDK

19.0.1; OpenJDK 64-Bit Server VM 19.0.1+10-FR; Amazon.com Inc.

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-10-21 15:42
Closing as seems to be caused by third-party plugin, and accepted as such in the related issue.

**Closed by neilcsmith-net** 2022-10-21 15:42 UTC
Labels: kind:bug, needs:triage
