### ISSUE TITLE
[NB21] java.lang.NoClassDefFoundError: com/google/auto/service/AutoService

### ISSUE THREAD

**Issue by ctabin** [apache/netbeans#7328] opened 2024-04-23 19:32 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

Hi,

Since recently, when I open my project (multi-module project Java with maven 3.9.6), Netbeans shows the following Exception
```
Annotation: An error occurred during parsing of '/home/myhome/File.java'. Please report a bug against java/source and attach dump file '...'.
An error occurred during parsing of '/home/myhome/File.java'. Please report a bug against java/source and attach dump file '...'.
Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NoClassDefFoundError: com/google/auto/service/AutoService
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:738)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:818)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:912)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2300(JavacProcessingEnvironment.java:113)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1255)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1370)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1272)
	at org.netbeans.lib.nbjavac.services.NBJavaCompiler.processAnnotations(NBJavaCompiler.java:64)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1171)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:348)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:742)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:536)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:140)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
Caused by: java.lang.NoClassDefFoundError: com/google/auto/service/AutoService
	at com.google.auto.service.processor.AutoServiceProcessor.getSupportedAnnotationTypes(AutoServiceProcessor.java:89)
	at com.google.auto.service.processor.AutoServiceProcessor.getSupportedAnnotationTypes(AutoServiceProcessor.java:69)
	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.getSupportedAnnotationTypes(APTUtils.java:980)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:700)
	... 25 more
Caused by: java.lang.ClassNotFoundException: com.google.auto.service.AutoService
	... 29 more
```

This makes Netbeans stop working:
- no more highlight of variable
- no more code navigation
- no more intellisence

Note that my java file is a simple POJOs with nothing special in there. I also tried other classes: the same problem arise.

Here is what I tried:
- closing the whole project and reopen it
- change project group and come back
- remove the dir `~/.netbeans/21` to clear up any cache
- tried to add the google auto-service to my `pom.xml`
- reloading the pom in my project

Anyways, the error still arise and prevents me to work smoothly.

### Language / Project Type / NetBeans Component

Java Maven Project

### How to reproduce

I don't know how to reproduce it. All was working smoothly till now and nothing special changed.
The only thing I can guess is that I just pulled out the project (and there was multiple library updates in the main pom.xml) and open it in NetBeans priori to make a `mvn clean install`.
But, even after closing it, full rebuild of the project, still the same error occurs...

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

Linux Debian 12

### JDK

OpenJDK 21

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2024-04-24 03:03
How do you run the annotation processor? Anything special there?

I couldn't reproduce it either, no exceptions even without the dependency.
```java
package dev.mbien.mavenproject1;

import com.google.auto.service.AutoService;

public class Mavenproject1 {
    
    public interface FooService {
        String translate(String message);
    }
    
    @AutoService(FooService.class)
    public class FooServiceProvider implements FooService {
        @Override
        public String translate(String message) {
            return null; 
        }
    }
}
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>dev.mbien</groupId>
    <artifactId>mavenproject1</artifactId>
    <version>0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <dependencies>
        <!--
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <version>1.1.1</version>
            <scope>compile</scope>
        </dependency>
        -->
    </dependencies>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <exec.mainClass>dev.mbien.mavenproject1.Mavenproject1</exec.mainClass>
        <maven.compiler.release>21</maven.compiler.release>
    </properties>
</project>
```

**Comment by ctabin** [comment] 2024-04-24 07:12
Hi @mbien thanks for the reply.

Actually, I don't do anything. I just open my project in NetBeans and then open my POJO and... I see an exclamation mark in red down right and when I open it, it shows this stacktrace.
I do not run explicitly the annotation processing, nor build the project in NetBeans.

In our maven, we have some plugins like errorprone, spotbugs or checkstyle but that never caused any problem until now.

**Comment by mbien** [comment] 2024-04-24 07:26
whats up with this file?
```
Annotation: An error occurred during parsing of '/home/myhome/File.java'. Please report a bug against java/source and attach dump file '...'.
An error occurred during parsing of '/home/myhome/File.java'. Please report a bug against java/source and attach dump file '...'.
```

**Comment by ctabin** [comment] 2024-04-24 08:46
The file is just a (very) simple POJO. It happen on multiple different files, event simple ones.

Here is the cleaned up content showing that there is nothing special in this class:
```java

public class MyFunction extends AbstractFunction {
    public static final String CODE_YOUTH = "1";
    
    public static final Constraint MY_CONSTRAINT = new Constraint() {
        @Override
        public boolean isValid(Employee employee, LineContext context, Context input) {
            //...
        }
        
        @Override public String getName() { return "1"; }
    };
    
    public static interface DataReader {
        boolean withFranchise(Employee employee, Context slc);
    }
    
    private final DataReader reader;
    private final String cumulativeId;
    private final String avsMonthLineId;

    public MyFunction(DataReader reader, String cumulativeId, String lineId) {
        //...
    }
    
    @Override
    protected void internalCompute(Employee employee, LineContext context, Context input) {
        //...
    }
}
```

**Comment by neilcsmith-net** [comment] 2024-04-24 08:54
> remove the dir ~/.netbeans/21 to clear up any cache

But have you tried deleting the _cache_?!  `~/.cache/netbeans/21`.

**Comment by matthiasblaesing** [comment] 2024-04-24 16:12
From the error I would guess that the classpath is broken. It would help to create a minimal sample. I had a similar problem and in that case I had a bad path element in the annotation process path of my maven project. Creating a minimal sample will either show the problem in the setup or make it possible to investigate, so is useful in any case.

**Comment by ctabin** [comment] 2024-04-24 20:16
Hi,

It seems I've found the problem and it was related to my project: this is because we use ErrorProne with a custom plugin in our build:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <configuration>
    <compilerArgs>
      <arg>...</arg>
    </compilerArgs>
    <annotationProcessorPaths>
      <path>
        <groupId>ch.astorm</groupId>
        <artifactId>errorprone-plugin</artifactId>
        <version>1.9</version>
      </path>
      <path>
        <groupId>com.google.errorprone</groupId>
        <artifactId>error_prone_core</artifactId>
        <version>2.26.1</version>
      </path>
    </annotationProcessorPaths>
  </configuration>
</plugin>
```

In this `error-prone-plugin`, there is the dependency on `auto-service` that is marked as optional. After removed the `<optional>true</optional>`, recompiling the plugin and using the new version, I was able to open it in NetBeans without error \o/

This is just strange that we have no problem with the compilation and in other IDEs. Also removing the `~/cache/.netbeans` dir had unfortunately no effect. I even tried a full reinstallation with removal of `~/.cache/netbeans` and `~/.netbeans`, still the same error was thrown.

So, I close this issue seems it was related to my project and not within NetBeans directly.

**Comment by mbien** [comment] 2024-04-25 06:11
> In this error-prone-plugin, there is the dependency on auto-service that is marked as optional. After removed the `<optional>true</optional>`, recompiling the plugin and using the new version, I was able to open it in NetBeans without error \o/
> 
> This is just strange that we have no problem with the compilation and in other IDEs.

First of all thanks for investigating, I did suspect that this might have something to do with the annotation processor path. I think we should leave the issue open since there is some room to improve the exception handling there I believe. NB could likely skip over that annotation and print a warning instead letting classloader exceptions propagate and the code scan task fail.

**Comment by ctabin** [comment] 2024-04-25 07:56
> NB could likely skip over an annotation and print a warning instead letting classloader exceptions propagate and the code scan task fail.

That would be great :+1: Thanks for the follow-up.

**Comment by mbien** [comment] 2024-04-26 10:03
experimented a bit with errorprone plugins but couldn't reproduce it. I don't want to change the exception handling without a way to validate it. closing again.

**Closed by mbien** 2024-04-26 10:03 UTC
Labels: kind:bug, Java
