### ISSUE TITLE
Exception when using Lombok annotations

### ISSUE THREAD

**Issue by andresCorralM** [apache/netbeans#6893] opened 2023-12-29 11:39 UTC
### Apache NetBeans version

Apache NetBeans 20

### What happened

When opening a file with a class annotated with Lombok annotations Netbeans shows an exception. It appears on a marker at class level (see screenshot). The exception is attached as a screen shot. Sorry but I couldn't find the text anywhere. It's not on the Netbeans log.
It's clear that the lombook annotations are not being processed correctly since Netbeans doesn't see the getters and setters that lombook should be creating and shows errors in source files that try to use those.
![exception](https://github.com/apache/netbeans/assets/42398517/d3a9042a-7518-47ff-93d0-f3dffd701250)

### Language / Project Type / NetBeans Component

Java Maven project

### How to reproduce

Create a simple Maven project, with Java 11 as the Java version and just lombok 1.18.26 as a dependency and lombok-maven-plugin 1.18.20.0 as a Maven plugin. I can attach an example project if necessary.

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Windows 10 version 10.0 running on amd64

### JDK

11.0.16.1; Java HotSpot(TM) 64-Bit Server VM 11.0.16.1+1-LTS-1

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2023-12-29 15:12
Duplicate of #6802. TL;DR version: Use current lombok version and be prepared to update immediately. When using lombok you must be prepared, that your toolchain can break at any moment, as it integrates/messes deeply with the JDK.

**Closed by matthiasblaesing** 2023-12-29 15:12 UTC
Labels: kind:bug, needs:triage

**Comment by andresCorralM** [comment] 2023-12-29 18:49
Thanks for the answer. You learn something new everyday I guess
