### ISSUE TITLE
Source code auto formatting to the comments

### ISSUE THREAD

**Issue by haunhp1** [apache/netbeans#4633] opened 2022-09-14 02:41 UTC
### Apache NetBeans version

Apache NetBeans 15 release candidate

### What happened

I'm using v15 for PHP. It formats the source code automatically but doesn't affect on 1-line comment when the comment line has no white space at the beginning.
For example:

![image](https://user-images.githubusercontent.com/23661521/190045102-59fc8e6e-00d1-4444-8827-1dc840834ce0.png)

If I add a white space like this:
![image](https://user-images.githubusercontent.com/23661521/190045264-eb14faf0-df2a-416f-a640-fd2eef9beaed.png)

It will look good when saving:
![image](https://user-images.githubusercontent.com/23661521/190045328-a5d5323b-a71b-4129-9cf5-08b7225b8914.png)

The last comment line is still not good. The IDE doesn't format it. Why?

### How to reproduce

Edit any PHP file with a few lines of source code.
Or try this:

class Tester {

    public function __construct() {
        //this comment line will look good
// try to add a white space at the beginning of this line, it will look good once saved
// but not this! Why?
    }

}

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Microsoft Windows 10 Home Single Language x64, Version 10.0.19044 Build 19044, 

### JDK

Product Version: Apache NetBeans IDE 15, Java: 17.0.1; Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39 Runtime: Java(TM) SE Runtime Environment 17.0.1+12-LTS-39, System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by NotherGithubAccount** [comment] 2022-09-14 06:49
WFIW, I can confirm this behavior with OpenJDK on Debian 11.

**Comment by junichi11** [comment] 2022-10-31 13:35
Not a bug.
We can comment out by `Ctrl` + `/` temporary. (`//` is added to the top of the line.)
e.g. 
```php
function example(): void {
    $a = 1;
//    $b = 2;
    $c = 3;
}
```
If there is `//` at top of the line, it may be intentional.
So, the editor does not format anything.
This is the same behavior as the Java editor.

**Comment by neilcsmith-net** [comment] 2022-10-31 13:43
Thanks @junichi11 - closing.

**Closed by neilcsmith-net** 2022-10-31 13:43 UTC
Labels: kind:bug, PHP, needs:triage

**Comment by Chris2011** [comment] 2022-10-31 16:39
@haunhp1 I think, after you wrote the comment, you need to reformat the code again after this the comments should be on the correct position.
