### ISSUE TITLE
Faces app does not start in browser after 'run'

### ISSUE THREAD

**Issue by httpeter** [apache/netbeans#5261] opened 2023-01-10 09:37 UTC
### Apache NetBeans version

Apache NetBeans 16

### What happened

I opened Faces (JSF+Primefaces) app that I developed with NB15 on NB16 and wanted to run it. Tomcat8 starts up fine, code compiles but normally NB starts up my browser and opens the URL. Now it does not and the application is not present at it's normal localhost URL. Also NB16 shows the following error:

```
java.lang.NoSuchMethodError: java.net.URLEncoder.encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at org.netbeans.modules.tomcat5.deploy.TomcatManagerImpl.encodePath(TomcatManagerImpl.java:336)
	at org.netbeans.modules.tomcat5.deploy.TomcatManagerImpl.remove(TomcatManagerImpl.java:232)
	at org.netbeans.modules.tomcat5.deploy.TomcatManager.undeploy(TomcatManager.java:674)
	at org.netbeans.modules.j2ee.deployment.impl.TargetServer.deploy(TargetServer.java:649)
	at org.netbeans.modules.j2ee.deployment.devmodules.api.Deployment.deploy(Deployment.java:221)
	at org.netbeans.modules.maven.j2ee.execution.DeploymentHelper.perform(DeploymentHelper.java:185)
	at org.netbeans.modules.maven.j2ee.execution.CoSAlternativeExecutorImpl.execute(CoSAlternativeExecutorImpl.java:67)
	at org.netbeans.modules.maven.cos.CoSAlternativeExecutor.execute(CoSAlternativeExecutor.java:64)
	at org.netbeans.modules.maven.cos.CosChecker.checkRunMainClass(CosChecker.java:185)
	at org.netbeans.modules.maven.cos.CosChecker.checkRunConfig(CosChecker.java:139)
	at org.netbeans.modules.maven.execute.MavenCommandLineExecutor.run(MavenCommandLineExecutor.java:240)
	at org.netbeans.core.execution.RunClassThread.doRun(RunClassThread.java:132)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:81)
```

### How to reproduce

-

### Did this work correctly in an earlier version?

Apache NetBeans 15

### Operating System

OSX 10

### JDK

8

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Every time this problem occurs. On NB15 there are no problems.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment] 2023-01-10 15:25
NetBeans requires JDK 11+ as runtime which should have this method since it was added in Java 10.

Although this exception could be easily fixed by using the string variant of this method, you really should use JDK 11+ by now.

Adding contribution welcome label in case someone wants to patch it.

**Comment by matthiasblaesing** [comment] 2023-01-10 20:23
Duplicate of #5154 and #5134, fixed by:

https://github.com/matthiasblaesing/netbeans/commit/9b6e3b45722aa5b3e610ac4da59cdaa269273391

**Closed by matthiasblaesing** 2023-01-10 20:23 UTC
Labels: kind:bug, good first issue, Contribution welcome

**Comment by httpeter** [comment] 2023-01-17 10:02
> NetBeans requires JDK 11+ as runtime which should have this method since it was added in Java 10.
> 
> Although this exception could be easily fixed by using the string variant of this method, you really should use JDK 11+ by now.
> 
> Adding contribution welcome label in case someone wants to patch it.

@mbien Dear Michael,

Thanks for your swift and clear reply! Let me upgrade my JDK and try again!

Best regards,

Peter
