### ISSUE TITLE
CVS not able to installed in Netbeans 13 

### ISSUE THREAD

**Issue by selvalogic** [apache/netbeans#3709] opened 2022-03-05 12:21 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

CVS not able to installed in New Version. I have include  the following URL in Plugin Settings 
http://bits.netbeans.org/dev/nbms-and-javadoc/lastSuccessfulBuild/artifact/nbbuild/nbms/updates.xml.g
<img width="668" alt="NB 13 0 CVS Plugin" src="https://user-images.githubusercontent.com/3874468/156882700-41213909-d516-4f5a-af3c-18c8af5daafb.png">
z

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Windows 11

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment] 2022-03-05 12:39
Duplicate of #3684

**Closed by matthiasblaesing** 2022-03-05 12:39 UTC
Labels: kind:bug, needs:triage

**Comment by selvalogic** [comment] 2022-03-05 19:12
It is not duplicate, 

CVS works on Netbeans 12.6. But I am not able to install in New version 13.0

<img width="672" alt="NB12 6 CVS Working" src="https://user-images.githubusercontent.com/3874468/156896952-5b54daec-85b4-42f2-b87a-850f8f662eba.png">

**Comment by selvalogic** [comment] 2022-03-05 19:14
> Duplicate of #3684

It is not a duplicate one. 
CVS works on Netbeans 12.6. but I am not able to install CVS in new version Netbeans 13.0

Here I attached the Netbeans 12.6 CVS screenshot for your references. 




<img width="672" alt="NB12 6 CVS Working" src="https://user-images.githubusercontent.com/3874468/156897040-25cb4493-ad9e-433b-acd7-50bf36f3ab24.png">

**Comment by matthiasblaesing** [comment] 2022-03-05 19:15
I repeat: CVS is not a module in NetBeans. Point me to the location of the plugin in the code base and I stand corrected, but till then it is not there. So if it is an external plugin you need to determine where it comes from. Maybe it is fixable, maybe not, it depends on the distributor/developer of the plugin.

The minimum you'd have to provide is the error log (message.log), else no one can help you.

**Comment by selvalogic** [comment] 2022-03-05 19:34
> I repeat: CVS is not a module in NetBeans. Point me to the location of the plugin in the code base and I stand corrected, but till then it is not there. So if it is an external plugin you need to determine where it comes from. Maybe it is fixable, maybe not, it depends on the distributor/developer of the plugin.
> 
> The minimum you'd have to provide is the error log (message.log), else no one can help you.

Thanks. 

Yes I agree, CVS is not a module in Netbeans.  

Earlier in NB 12.6 I have added the following URL http://bits.netbeans.org/dev/nbms-and-javadoc/lastSuccessfulBuild/artifact/nbbuild/nbms/updates.xml.g in Plugin Setting and CVS was installed as external plugins.

CVS Plugins is not listed in Available Plugins. This is the Problem. Here No error log for this.

**Comment by matthiasblaesing** [comment] 2022-03-05 20:57
That explains it. For a time while NetBeans was transitioning from Oracle to the Apache Foundation the old binary servers were still availabile. bits.netbeans.org was one of them. At some point in time Oracle cut of the servers and thus the old binaries are not available anymore.

You might be able to rebuild the module from old sources, but Apache NetBeans does not offer that module. If it should be revived:

a) it needs to be checked if the old CVS code was donated
b) if it was donated, it needs to be cleaned up and restored into working state
c) if it was not donated, it needs to be reimplemented

If it was not donated, the plugin could be build externally and distributed under GPLv2/CDDL (as the original one). This all needs someone to do it.
