### ISSUE TITLE
can't refactor rename a method

### ISSUE THREAD

**Issue by dcourrier** [apache/netbeans#6938] opened 2024-01-09 17:39 UTC
### Apache NetBeans version

Apache NetBeans 20

### What happened

receive message:

Module Java Refactoring threw java.lang.IllegalStateException: java.lang.NullPointerException: Cannot read field "kind" because "tree.sym" is null. Please report a bug against Java Refactoring module and attach your var/log/messages.log.

### Language / Project Type / NetBeans Component

java class lib editor on ant project

### How to reproduce

Select method in a class.
click refactor from menu
click rename
supply new value & click rename

### Did this work correctly in an earlier version?

Apache NetBeans 13 or earlier

### Operating System

Windows 11

### JDK

windows jdk 20

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

every time

### Are you willing to submit a pull request?

No

**Comment by istinnstudio** [comment] 2024-01-17 20:44
This cannot be reproduced as it is just the basic refactoring function that basically works ok.  
Something additional is happening.
I am not sure, could be related to: https://github.com/apache/netbeans/issues/4145#issuecomment-1875192327

**Comment by mbien** [comment] 2024-02-14 12:25
the javac NPEs would need a reproducer if possible so that this can be filed against openjdk. Going to close this since there are many similar duplicates already tracked under https://github.com/apache/netbeans/labels/nb-javac

**Closed by mbien** 2024-02-14 12:25 UTC
Labels: kind:bug, Java, needs:triage, nb-javac
