### ISSUE TITLE
Repeating: Netbeans XX.X was last used XXX days ago

### ISSUE THREAD

**Issue by hiranchaudhuri1** [apache/netbeans#5117] opened 2022-12-16 10:49 UTC
### Description

Hello there.

I really appreciate Netbeans IDE since ages. And I am happy to see that current versions report about usused data and cache directories so the space can be freed up. Clicking that link to free up space is so comfortable.

Yet on my computer it seems to not work. The messages pop up almost every day, telling me how much space I could save. I am not saying that the root cause lies in Netbeans. My whole Windows home directory is synchronized to OneDrive and I do believe this is part of the problem.

However to be better informed I would need to know where Netbeans is finding the data and cache directories that are no longer required. With that information I could check and try to remove them manually. Hence I suggest that the notification message would list the absolute path of the obsolete data.

Hiran

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-12-16 11:02
The `Help / About` window should give you the information you're looking for?  Well, the directories you want are adjacent to those values anyway.

**Comment by hiranchaudhuri1** [comment] 2022-12-16 12:33
The path in Help/About points to the directory I want to keep. But yes, it is close.
However having to look it up there and figuring out the rest is not intuitive, and there is space in the notification itself. Would still appreciate if the paths in question could be added.

**Comment by lkishalmi** [comment] 2022-12-29 00:13
If someone can reproduce this on Windows, please take a peek:
https://github.com/apache/netbeans/tree/master/platform/janitor this is the module

This is the place where an exception might be swallowed: https://github.com/apache/netbeans/blob/5f2e1382bc66d465a544ab358171c1810b57834f/platform/janitor/src/org/netbeans/modules/janitor/Janitor.java#L236

**Comment by lkishalmi** [comment] 2023-07-07 01:24
Duplicate of: #5069

**Closed by lkishalmi** 2023-07-07 01:24 UTC
Labels: kind:feature, good first issue, os:windows
