### ISSUE TITLE
Java GUI Freeze

### ISSUE THREAD

**Issue by vegaskyo** [apache/netbeans#4508] opened 2022-08-16 02:23 UTC
### Apache NetBeans version

Apache NetBeans 14

### What happened

I create a small GUI windows with Java Swing. It's not even a big GUI, I just created a windows with a button and I encountered a problem. When I clicked **Preview** the window for the first time, it's totally ok, but then I close the GUI windows and clicked **Preview** again Netbeans went freeze. I tried to uninstalled and installed again but there's nothing change.

### Did this work correctly in an earlier version?

Apache NetBeans 13

### Operating System

Windows 10

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-08-16 09:32
Please can you test with [NetBeans 15-rc3](https://lists.apache.org/thread/vzx1jm5gz2w1rtof4swlvrclng0xsq8q)?  This might be related to #4231 Thanks!

**Comment by vishnuravva** [comment] 2022-08-16 16:18
while working with java gui the screen just freezes.Whats the solution for this ?

**Comment by DevCharly** [comment] 2022-08-17 14:06
This is a bug in NetBeans 14 that occurs only if FlatLaf look and feel is active. (see #4231)
It is fixed in NB 15. (see #4375)

There are several workarounds for this issue:

- use NetBeans 15 (e.g. [15-rc3](https://lists.apache.org/thread/vzx1jm5gz2w1rtof4swlvrclng0xsq8q)) (recommended)
- change NetBeans look and feel to any non-FlatLaf look (Tools > Options > Appearance > Look and Feel)
- do not use "Preview" in NetBeans GUI builder (when using FlatLaf)

Closing because duplicate of #4231

**Closed by DevCharly** 2022-08-17 14:06 UTC
Labels: kind:bug, needs:triage, pending-response

**Comment by vishnuravva** [comment] 2022-08-23 04:46
But is it available for Linux Ubuntu? And Thank you for your help and
solution.
