### ISSUE TITLE
Unpacking index for local repository error

### ISSUE THREAD

**Issue by articfox58** [apache/netbeans#4813] opened 2022-10-18 19:41 UTC
### Apache NetBeans version

Apache NetBeans 15

### What happened

I've done a new Java maven project, after NetBeans download packages it starts 'unpacking index for central repository'  then suddenly shows an error. The long backtrace starts with an IOException and the message 'not space left on device' (in spanish there)... that I put next... 
![error maven](https://user-images.githubusercontent.com/116110680/196517433-44076d45-ee1f-4a1a-ab9d-74641e380903.png)
![unpacking](https://user-images.githubusercontent.com/116110680/196775544-c1d3574f-5a14-41d0-91a4-4602f172027f.png)
![aparece error](https://user-images.githubusercontent.com/116110680/196775637-24636c5e-c7d9-4808-80a9-611925e27fc7.png)

### How to reproduce

In NetBeans go to ... File > New Project... > Java with Maven : Java Application
After created, Select the project and right click on it > Run Maven > Goals...

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Operating System: Arch Linux *** KDE Plasma Version: 5.26.0 *** KDE Frameworks Version: 5.99.0 *** Qt Version: 5.15.6 *** Kernel Version: 6.0.2-arch1-1 (64-bit) 

### JDK

OpenJDK 11

### Apache NetBeans packaging

Own source build

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by mbien** [comment] 2022-10-19 10:18
well.. do you have space on your dispositivo left? ;)

the cache is stored at:
`/home/[your_user]/.cache/netbeans`

Cache can be several GB large. If you don't use maven often or don't want the maven index, you can turn it off via:
`tools -> options -> java -> maven -> index -> completely disable indexing`

there is also a Janitor tool which cleans up old caches under:
`tools -> options -> miscellaneous -> janitor`

**Comment by articfox58** [comment] 2022-10-19 16:14
> well.. do you have space on your dispositivo left? ;)
> 
> the cache is stored at: `/home/[your_user]/.cache/netbeans`
> 
> Cache can be several GB large. If you don't use maven often or don't want the maven index, you can turn it off via: `tools -> options -> java -> maven -> index -> completely disable indexing`
> 
> there is also a Janitor tool which cleans up old caches under: `tools -> options -> miscellaneous -> janitor`

Thank you for your time and help.. 
Yes I have many space available on my device.. was the first checked..

**Comment by mbien** [comment] 2022-10-19 20:33
@articfox58 how much space do you have left?

**Comment by mbien** [comment] 2023-06-11 07:54
closing, sounds like a duplicate of #5727

**Closed by mbien** 2023-06-11 07:54 UTC
Labels: kind:bug, Java, Maven, needs:triage
