### ISSUE TITLE
Netbeans 13 integration with Wildfly 26.0.1 final Server

### ISSUE THREAD

**Issue by Kareemelagroudy** [apache/netbeans#3936] opened 2022-04-06 19:36 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

Hey, I'm creating some webapps that must be run on Wildfly server. The first time I run the project, It runs smoothly but it doesn't deploy afterwards (when modified or on 2nd, 3rd, .... times), I have to clean and build the project again in order to run it again
![Capture](https://user-images.githubusercontent.com/58118555/162054376-2f299e89-a49f-4929-bcca-efd04e6f8194.PNG)

### How to reproduce

The problem can be reproduced by modifying the project and running it again

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

JDK 18

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The problem occurs everytime I modify and rerun the project

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by asbachb** [comment] 2023-06-28 19:26
@Kareemelagroudy I could not reproduce this on NetBeans 18

Could you give some feedback is the issue is still persistent on NetBeans 18? Otherwise please close the issue.

**Closed** 2023-07-12 17:00 UTC
Labels: kind:bug, Java EE/Jakarta EE, needs:triage, enterprise
