### ISSUE TITLE
Integrated terminal without need of install Cigwin

### ISSUE THREAD

**Issue by antoniodiego** [apache/netbeans#4430] opened 2022-07-23 13:30 UTC
### Description

Several time users can wish to use terminal commands like commands of Git and can be annoying have to install cigwin every time they install the NetBeans.

Also, if it not possible to bundle a small subset of cigwin with NetNeans include the option of reveal project folders on Explorer, so the user can open the terminal through it

### Use case/motivation

Execute Git commands

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-07-23 14:02
Duplicate of #4245

**Closed by neilcsmith-net** 2022-07-23 14:02 UTC
Labels: kind:feature, needs:triage
