### ISSUE TITLE
Getting NullPointerException trying to create a new JPA Entity from a Database

### ISSUE THREAD

**Issue by steveg7753** [apache/netbeans#7193] opened 2024-03-26 01:59 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

Hi, I'm getting the following exception when I right click a folder and select "New/Entity Classes from Database...".  I'm running on Mac OS Monterey version 12.7.4:

java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.j2ee.persistence.spi.datasource.JPADataSourcePopulator.connect(javax.swing.JComboBox)" because "dsPopulator" is null
	at org.netbeans.modules.j2ee.persistence.wizard.fromdb.DatabaseTablesPanel.initializeWithDatasources(DatabaseTablesPanel.java:207)
	at org.netbeans.modules.j2ee.persistence.wizard.fromdb.DatabaseTablesPanel.initSubComponents(DatabaseTablesPanel.java:170)
	at org.netbeans.modules.j2ee.persistence.wizard.fromdb.DatabaseTablesPanel.ancestorAdded(DatabaseTablesPanel.java:1025)
	at java.desktop/javax.swing.AncestorNotifier.fireAncestorAdded(AncestorNotifier.java:86)
	at java.desktop/javax.swing.AncestorNotifier.componentShown(AncestorNotifier.java:193)
	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:188)
	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:187)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6458)
	at java.desktop/java.awt.Component.processEvent(Component.java:6406)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Window.processEvent(Window.java:2056)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1069)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1114)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1092)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:104)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:123)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:77)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:199)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1076)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$AWTQuery.showDialog(DialogDisplayerImpl.java:273)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$AWTQuery.run(DialogDisplayerImpl.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[messages.log](https://github.com/apache/netbeans/files/14751368/messages.log)

### Language / Project Type / NetBeans Component

Java Maven Project

### How to reproduce

- Right click a folder in the project view
- Click "New"
- Click "Entity Classes from Database"
- The modal appears with not databases listed and a red exclamation point at the bottom of the window.  click the exclamation and the exception is displayed.

### Did this work correctly in an earlier version?

Apache NetBeans 16 or earlier

### Operating System

Mac OS Monterey version 12.7.4

### JDK

JDK 17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Happens every time.

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2024-03-27 23:01
Duplicate of #7144

**Closed by matthiasblaesing** 2024-03-27 23:01 UTC
Labels: kind:bug, Java EE/Jakarta EE, needs:triage
