### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in javax.swing.text.BoxView.getOffset.

### ISSUE THREAD

**Issue by JQL** [apache/netbeans#6965] opened 2024-01-17 10:23 UTC
### Apache NetBeans version

Apache NetBeans 20

### What happened

While editing a Markdown File and saving it the error occurred (java.lang.ArrayIndexOutOfBoundsException).

### Language / Project Type / NetBeans Component

Markdown

### How to reproduce

Create and edit a Markdown file then save it.

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Linux version 5.4.0-150-generic running on amd64; UTF-8; en_GB (nb)

### JDK

17.0.7; OpenJDK 64-Bit Server VM 17.0.7+7-Ubuntu-0ubuntu118.04

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else
```

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.desktop/javax.swing.text.BoxView.getOffset(BoxView.java:1102)
	at java.desktop/javax.swing.text.BoxView.childAllocation(BoxView.java:696)
	at java.desktop/javax.swing.text.CompositeView.getChildAllocation(CompositeView.java:234)
	at java.desktop/javax.swing.text.BoxView.getChildAllocation(BoxView.java:454)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.calculateViewPosition(BasicTextUI.java:2111)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.layoutContainer(BasicTextUI.java:2087)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:757)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:755)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:754)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2024-01-17 16:50
Is this reproducible? What text was entered. What are steps to reproduce? The current provided steps are neither helpful nor correct. Tested on Ubuntu with bundled JDK and NB20, works for me.

**Comment by JQL** [comment] 2024-01-17 17:10
Matthias,

Now it happens whenever I save any Markdown file in the project.

Best regards,
John
***@***.***

**Comment by JQL** [comment] 2024-01-26 17:39
I tried deleting `~/.cache/netbeans/20/index` and this fixed the problem.

It seems that these indexes are being corrupted on a regular basis as this is the second time in about a month I've had to do this.

**Comment by matthiasblaesing** [comment] 2024-01-26 17:49
You are seeing a correlation, but I doubt, that there is a cause-chain we are seeing here. Indexing is its own problematic field, but there is no connection between markdown rendering and the indexing system.

**Comment by JQL** [comment] 2024-01-26 17:58
It's not the rendering but the saving of the file which caused the error message.  In over 40 years of chasing bugs in code I've found that coincidences merit checking.

**Comment by mbien** [comment] 2024-05-23 06:07
closing, feel free to reopen if there is a reproducer

**Closed by mbien** 2024-05-23 06:07 UTC
Labels: kind:bug, needs:triage, pending-response, UI
