### ISSUE TITLE
Syntax completion in Faces for CDI-Beans does not work

### ISSUE THREAD

**Issue by helper14** [apache/netbeans#7136] opened 2024-03-06 11:22 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

Syntax completion for CDI-Beans in Faces does not work if a module-info.java is present ( - without module-info.java it is working).

### Language / Project Type / NetBeans Component

Web Application

### How to reproduce

Create a template Web Application. Add an module-info.java. 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win10

### JDK

openJDK21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2024-03-06 11:44
Duplicate of #6659

**Closed by matthiasblaesing** 2024-03-06 11:44 UTC
Labels: kind:bug, needs:triage
