### ISSUE TITLE
Clipboard fail

### ISSUE THREAD

**Issue by rrangelo** [apache/netbeans#6661] opened 2023-11-05 20:54 UTC
### Apache NetBeans version

Apache NetBeans 19

### What happened

Hi! After a short time the clipboard integration stops working.
I can copy and paste only what I have done from within NetBeans, but not from outside of it. It happen on Windows.

### How to reproduce

1. Open NetBeans and a Browser
2. Enable Windows clipboard history (Windows key + V)
3. Open a project in NetBeans
4. Copy and paste multiple times in a row

### Did this work correctly in an earlier version?

Apache NetBeans 17

### Operating System

Windows

### JDK

GraalVM Community Edition

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by lkishalmi** [comment] 2023-11-06 00:08
Closing as a duplicate of #3962

**Closed by lkishalmi** 2023-11-06 00:08 UTC
Labels: kind:bug, needs:triage
