### ISSUE TITLE
Copy & Paste from NetBeans to external editors doesn't work.

### ISSUE THREAD

**Issue by chengthao** [apache/netbeans#5318] opened 2023-01-18 23:13 UTC
### Apache NetBeans version

Apache NetBeans 16

### What happened

Copying code from NetBeans IDE and pasting it to a text editor outside of NetBeans often do not work.  Once in a while, copy and paste works but not for most of the time.  

### How to reproduce

Under Windows 11, using NetBeans 15, 

- Create a Java project.  
- Create a Java class.  
- Write code some.  
- Copy the code and paste it to Notepad.  
- Nothing will be pasted into Notepad or any text editor.
- 

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Windows 11

### JDK

JDK 19

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2023-01-19 16:49
Thanks for the report.  This is a duplicate of #3962 Please follow up there, try some of the suggestions, and see if there's any further info you can provide.

**Closed by neilcsmith-net** 2023-01-19 16:49 UTC
Labels: kind:bug, needs:triage, os:windows
