### ISSUE TITLE
Provider org.apache.xpath.jaxp.XPathFactoryImpl not found 

### ISSUE THREAD

**Issue by gilbertoca** [apache/netbeans#6045] opened 2023-06-05 14:04 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

Download Netbeans 18 zip file, extracted and run it. It shows me a dialog to import my plugins, marked all of them, restarted. Netbeans started again, it opens, then I wait for the decompress and indexing remote maven repo, then I wait, wait .... 15min, cancel the indexing and restart again. Now it shows me notification with the exception in the tittle:

```
java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: Provider org.apache.xpath.jaxp.XPathFactoryImpl not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1268)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1267)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1270)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.xml/javax.xml.xpath.XPathFactoryFinder$2.run(XPathFactoryFinder.java:335)
	at java.xml/javax.xml.xpath.XPathFactoryFinder$2.run(XPathFactoryFinder.java:331)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.xml/javax.xml.xpath.XPathFactoryFinder.findServiceProvider(XPathFactoryFinder.java:331)
	at java.xml/javax.xml.xpath.XPathFactoryFinder._newFactory(XPathFactoryFinder.java:212)
	at java.xml/javax.xml.xpath.XPathFactoryFinder.newFactory(XPathFactoryFinder.java:137)
	at java.xml/javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:223)
	at java.xml/javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:113)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureInfo.isProject(FeatureInfo.java:182)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureProjectFactory.checkProjects(FeatureProjectFactory.java:301)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureProjectFactory.run(FeatureProjectFactory.java:292)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
--------------- linked to ------------------
javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: Provider org.apache.xpath.jaxp.XPathFactoryImpl not found
	at java.xml/javax.xml.xpath.XPathFactoryFinder.findServiceProvider(XPathFactoryFinder.java:346)
	at java.xml/javax.xml.xpath.XPathFactoryFinder._newFactory(XPathFactoryFinder.java:212)
	at java.xml/javax.xml.xpath.XPathFactoryFinder.newFactory(XPathFactoryFinder.java:137)
	at java.xml/javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:223)
	at java.xml/javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:113)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureInfo.isProject(FeatureInfo.java:182)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureProjectFactory.checkProjects(FeatureProjectFactory.java:301)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureProjectFactory.run(FeatureProjectFactory.java:292)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
Caused by: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: Provider org.apache.xpath.jaxp.XPathFactoryImpl not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1268)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1267)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1270)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.xml/javax.xml.xpath.XPathFactoryFinder$2.run(XPathFactoryFinder.java:335)
	at java.xml/javax.xml.xpath.XPathFactoryFinder$2.run(XPathFactoryFinder.java:331)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.xml/javax.xml.xpath.XPathFactoryFinder.findServiceProvider(XPathFactoryFinder.java:331)
	... 11 more
Caused: java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: Provider org.apache.xpath.jaxp.XPathFactoryImpl not found
	at java.xml/javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:119)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureInfo.isProject(FeatureInfo.java:182)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureProjectFactory.checkProjects(FeatureProjectFactory.java:301)
	at org.netbeans.modules.ide.ergonomics.fod.FeatureProjectFactory.run(FeatureProjectFactory.java:292)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1419)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2034)
```

 
![image](https://github.com/apache/netbeans/assets/3083703/4cb9fcc2-123d-44ef-8c77-35d4e6ed5aa2)

![image](https://github.com/apache/netbeans/assets/3083703/c3d189a0-bae8-42d2-ab11-b39bc380906c)

After some minutes the notification disappear.  

Regards,

Gilberto

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

OpenSUSE 15.4

### JDK

openjdk version "11.0.19" 2023-04-18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

messages.log
[messages.log](https://github.com/apache/netbeans/files/11748772/messages.log)

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2023-06-05 16:39
Please show the full `messages.log` for the run.

**Comment by gilbertoca** [comment] 2023-06-14 17:03
@matthiasblaesing  I've upload the messages.log file

**Comment by gilbertoca** [comment] 2023-06-14 20:29
It seems to work, no more exception:

![image](https://github.com/apache/netbeans/assets/3083703/9c5e7ec0-37fb-4ba7-8896-678ab99ce3ab)

I will upload the messages.log here, so you my need some information about that plugins:
[messages.log](https://github.com/apache/netbeans/files/11750263/messages.log)

Thanks

**Comment by matthiasblaesing** [comment] 2023-06-23 20:12
Thank you for the check @gilbertoca. I released a new version of the plantuml plugin, which does not bundle Xalan anymore. I fact an update of batik dropped it, so there was not even an override necessary:

https://plugins.netbeans.apache.org/catalogue/?id=58

I assume, that verification will be done in the next few days. Meanwhile you can download the new version manually. Closing this here, as the issue is not in NetBeans.

**Closed by matthiasblaesing** 2023-06-23 20:12 UTC
Labels: kind:bug, caused-by-plugin
