### ISSUE TITLE
Error in generate entity class from database

### ISSUE THREAD

**Issue by thilinajayamini** [apache/netbeans#7221] opened 2024-04-01 13:38 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

try to generate entity class from database under new-> java persistence. you will see the error 

### How to reproduce

try to generate entity class from database under new-> java persistence. you will see the error 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

windows 10

### JDK

21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

[messages.log](https://github.com/apache/netbeans/files/14823942/messages.log)

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2024-04-01 13:44
Duplicate of #7144

**Closed by matthiasblaesing** 2024-04-01 13:44 UTC
Labels: kind:bug, needs:triage
