### ISSUE TITLE
Formatting issue with  {@return foo}

### ISSUE THREAD

**Issue by naren2605** [apache/netbeans#7640] opened 2024-08-06 02:24 UTC
### Apache NetBeans version

Apache NetBeans 22

### What happened

formatting source file is not formatting content with  inline javadoc tags  like `@return` correctly

### How to reproduce

reformat source file with below sample

### issue details

The formatter messes up Javadoc like {@return foo}.

For example formatting this:

```java
    /**
     * {@return foo}
     */
    String bar() {
        return null;
    }
```
Actual:
```java
    /**
     *
     * {
     *
     * @return foo}
     */
    String bar() {
        return null;
    }
```

Expected:

```java
    /**
     * {@return foo}
     */
    String bar() {
        return null;
    }
```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

macOS

### JDK

openjdk 22.0.1 

### Apache NetBeans packaging

Apache NetBeans platform

### root cause analysis
- `@return` is always treated as block tag , since java 16 return can be both inline and block tag as mentioned in the the [spec](https://docs.oracle.com/en/java/javase/22/docs/specs/javadoc/doc-comment-spec.html#Where%20Tags%20Can%20Be%20Used) 
- this also happens with any inline tag which is not present in list mentioned [here](https://github.com/apache/netbeans/blob/master/java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java#L4825)

Fixing this will also close   [issue in oracle java vscode #194](https://github.com/oracle/javavscode/issues/194) , will be raising pr for this issue

### Are you willing to submit a pull request?

Yes

**Comment by mbien** [comment] 2024-08-09 16:19
this looks like a duplicate of https://github.com/apache/netbeans/issues/3774

**Comment by naren2605** [comment] 2024-08-12 04:32
> this looks like a (partial) duplicate of #3774 / https://issues.apache.org/jira/browse/NETBEANS-5838

as i understand @mbien/ @lahodaj   this provided would be closing formatting part mentioned in mentioned right? #3774

**Comment by mbien** [comment] 2024-08-12 04:48
@naren2605 I think so, yes.

**Closed** 2024-08-28 07:54 UTC
Labels: kind:bug, Java, JavaDoc
