### ISSUE TITLE
Janitor doesn't detect old caches correctly

### ISSUE THREAD

**Issue by iajn** [apache/netbeans#6063] opened 2023-06-09 23:02 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

Opening NetBeans 18 doesn't post the Janitor notifications about cleaning up old cache directories, even though there are multiple ones present:

![image](https://github.com/apache/netbeans/assets/10802138/dda52ef8-00c2-4238-ae23-31d9a50195a0)

Looking at the timestamps, 17, 18-rc4 and dev (plus 18 obviously) are still inside the default 30 day threshold, but 16 and 17-rc3 are not. So there should be prompts to delete those two caches. Running the Janitor manually just tells me to check the notifications, but there are no new messages.

Lowering the threshold to 7 days and running Janitor again gives me prompts to delete 18-rc4 and dev caches, but 16, 17-rc3 and 17 are still missing.

Activating the cache cleanup via the two prompts doesn't delete anything, but the caches modified date is updated:

![image](https://github.com/apache/netbeans/assets/10802138/970459c1-a128-475c-9895-d1274eac89cb)

Checking inside, only the alphabetically first directory (index in both caches) has its modified date updated. Peeking inside this, none of the files or directories had their modified date updated. So the only change is for the first directory in the cache. Running the Janitor again now gives no prompts.

The cache directory not actually being deleted could be related to https://github.com/apache/netbeans/issues/5069, although in the last screenshot the modified date of 14 seems unchanged.

Forgot to check before running the Janitor prompt actions, but afterwards I had only NB18 user directory present. Not sure if it matters.

Nothing suspicious in the IDE log.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

Azul Zulu JDK20

### Apache NetBeans packaging

Third-party package

### Anything else

Its possible the Janitor still worked on NB16, since I don't have NB15 or older cache directories present. But I can't be sure, I might've deleted them manually.

I'm using the Codelerity / Gj IT release of NetBeans.

### Are you willing to submit a pull request?

No

**Comment by lkishalmi** [comment] 2023-07-07 01:25
Duplicate of #5069

**Closed by lkishalmi** 2023-07-07 01:25 UTC
Labels: kind:bug, Contribution welcome, os:windows
