### ISSUE TITLE
Complete Code shortcut <CTRL>+<Space> no longer works on Mac OS

### ISSUE THREAD

**Issue by upachler** [apache/netbeans#4880] opened 2022-10-29 08:57 UTC
### Apache NetBeans version

Apache NetBeans 15

### What happened

When switching from NB 12 to NB 15, I noticed that the code completion shortcut <CTRL>+<SPACE> no longer works (tested with Java source code).

When activated via the shortcut, the 'Source' menu briefly flashes, indicating that the shortcut keystroke was recognized, but code completion is not triggered.

When activating the 'Complete Code' functionality via the mouse by clicking the respective menu item, the code completion works as expected (completing code or showing the selection for resolving ambiguities).

Interestingly, the method selection for Java source is still shown when I type 'this.' - the selection appears after I type '.'. When I press <CTRL>+Space while the cursor is located after the '.', the method selection does not appear (but it does when code completion is activated via the menu, as described above).

I am using mac os 12.6 Monterey and Java 11.0.12 LTS

### How to reproduce

* Create a new Java project in NB 15 (I chose Maven, but any should do)
* the generated mail class will have a line 'System.out.println("Hello World");'.
* There, delete the 'println("HelloWorld");' part
* locate the cursor right after 'Sytem.out.' (after the dot).
* Press <CTRL>+<Space>

expected:
a preview showing all method calls that may be inserted here

observed:
nothing happens (except for a brief flash of the 'Source' menu indicating that the keystroke itself was recognized)

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Mac OS 12.6 Monterey

### JDK

JDK 11.0.12

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-10-29 09:06
Sounds like a duplicate of #4212 Please try running NetBeans itself on an up-to-date JDK.

**Closed by neilcsmith-net** 2022-10-29 09:06 UTC
Labels: kind:bug, needs:triage

**Comment by upachler** [comment] 2022-10-30 14:40
@neilcsmith-net: Yes, you're absolutely right. Running on JDK 17.0.5 fixes the problem. Sorry I didn't see the old issue before, but I was only looking for open issues when I filed this one, not closed ones.
