### ISSUE TITLE
Navigate Hierarchy doesn't work (for class in try-with-resources block)

### ISSUE THREAD

**Issue by pedro-w** [apache/netbeans#4667] opened 2022-09-21 08:50 UTC
### Apache NetBeans version

Apache NetBeans 15

### What happened

The Navigate | Inspect | Hierarchy menu (aka shift-alt-F12) does not always work. It seems to fail when the class under the cursor is in a `try()` block - it shows the hierarchy of the enclosing class instead. 

### How to reproduce

Make a Java ant project with the following source

```
package javaapplication150;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class JavaApplication150 {

    public static void main(String[] args) throws IOException {
        try ( BufferedWriter writer = Files.newBufferedWriter(Path.of("a"))) {
            writer.flush();
        }
    }

}

```
Move cursor to the `BufferedWriter` text on line 11. Press shift-alt-F12. Hierarchy window will show the results for `JavaApplication150`

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

11.0.9.1; OpenJDK 64-Bit Server VM 11.0.9.1+1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Occurs every time the project is opened fresh. If the target class source is open in another tab it works (sometimes, I can't see a pattern to this)

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by pedro-w** [comment] 2022-09-21 08:54
IDE log attached 

[ide-log.log](https://github.com/apache/netbeans/files/9614892/ide-log.log)

**Comment by pedro-w** [comment] 2022-09-21 08:58
Note that it does work if the cursor is on the text `writer` on line 11 or line 12.

**Comment by neilcsmith-net** [comment] 2022-09-21 12:47
Confirmed.  Try adding `final` before the `BufferedWriter` - does that also fix it for you?

**Comment by pedro-w** [comment] 2022-09-21 13:22
>  Try adding final before the BufferedWriter - does that also fix it for you?
Yes, it does.
Unfortunately I don't have any previous installations so I can't say if other versions are affected.

**Comment by neilcsmith-net** [comment] 2022-09-22 11:20
Verified that `TreeUtilities` is returning `final` rather than `BufferedWriter` as the element at that position due to the overlapping positions discussed in #4648 

I assume this might be fixed by upstream fix in https://bugs.openjdk.org/browse/JDK-8293897  However, that's unlikely to reach us until NB 18.  @jlahoda any thoughts?

**Comment by mbien** [comment] 2024-05-25 08:21
quickly checked and this is working fine in NB 22 which means that this was resolved via a regular nb-javac update at some point.

closing, feel free to reopen if this is still a problem.

**Closed by mbien** 2024-05-25 08:21 UTC
Labels: kind:bug, Java
