### ISSUE TITLE
Variables window show no variables

### ISSUE THREAD

**Issue by rmrfchik** [apache/netbeans#4657] opened 2022-09-19 11:26 UTC
### Apache NetBeans version

Apache NetBeans 15

### What happened

Variables window is empty. Even UI is empty, not rendered. Possibly related stacktrace:
java.lang.ClassNotFoundException: org.netbeans.spi.viewmodel.NodeActionsProviderFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: org.netbeans.spi.viewmodel.NodeActionsProviderFilter starting from ModuleCL@3e07d79a[org.exbin.bined.netbeans] with possible defining loaders [ModuleCL@5ca12093[org.netbeans.spi.viewmodel]] and declared parents [org.netbeans.JarClassLoader@701c3bf3, ModuleCL@3b50b269[org.netbeans.modules.queries], ModuleCL@5ab7a307[org.netbeans.modules.options.api], ModuleCL@45abb5b2[org.netbeans.modules.settings], ModuleCL@78cd3630[org.openide.nodes], ModuleCL@2b139695[org.netbeans.api.annotations.common], org.netbeans.MainImpl$BootClassLoader@65b54208, ModuleCL@1e54c5e3[org.openide.loaders], ModuleCL@6eb98136[org.openide.actions], ModuleCL@715e2823[org.openide.dialogs], ...3 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
Caused: java.lang.NoClassDefFoundError: org/netbeans/spi/viewmodel/NodeActionsProviderFilter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:287)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:246)
Caused: java.lang.NoClassDefFoundError: org/netbeans/spi/viewmodel/NodeActionsProviderFilter while loading org.exbin.bined.netbeans.debug.BinedLocalsActionsProviderFilter; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:250)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:174)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:769)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.netbeans.spi.debugger.ContextAwareSupport.createInstance(ContextAwareSupport.java:75)
	at org.netbeans.debugger.registry.ContextAwareServiceHandler.invoke(ContextAwareServiceHandler.java:109)
	at jdk.proxy20/jdk.proxy20.$Proxy103.forContext(Unknown Source)
	at org.netbeans.api.debugger.Lookup$MetaInf$MetaInfLookupList$LazyInstance.getEntry(Lookup.java:1053)
	at org.netbeans.api.debugger.Lookup$LookupList$LookupLazyEntry.get(Lookup.java:1271)
	at org.netbeans.api.debugger.LazyArrayList.get(LazyArrayList.java:138)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.fillElements(Lookup.java:243)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:195)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:179)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:179)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.api.debugger.DebuggerEngine.lookup(DebuggerEngine.java:172)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.setUp(Lookup.java:178)
	at org.netbeans.api.debugger.Lookup$Compound$CompoundLookupList.<init>(Lookup.java:173)
	at org.netbeans.api.debugger.Lookup$Compound.lookup(Lookup.java:135)
	at org.netbeans.modules.debugger.ui.views.ViewModelListener.updateModelLazily(ViewModelListener.java:390)
	at org.netbeans.modules.debugger.ui.views.ViewModelListener.setUp(ViewModelListener.java:215)
	at org.netbeans.modules.debugger.ui.views.ViewModelListener$1.run(ViewModelListener.java:199)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### How to reproduce

Start debug session, hit breakpoint, open Variables window. Window is empty.

### Did this work correctly in an earlier version?

Apache NetBeans 14

### Operating System

Linux, Debian 11

### JDK

OpenJDK 64-Bit Server VM (build 11.0.15+10-post-Debian-1, mixed mode, sharing), OpenJDK

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment] 2022-09-19 18:19
can't reproduce this. All variables are there, no Exceptions in log.

**Comment by rmrfchik** [comment] 2022-09-20 09:10
I tried to find needed class (BinedLocalsActionsProviderFilter) like this:
find . -name \*jar -exec unzip -l {} \;
No named class is found.

**Comment by neilcsmith-net** [comment] 2022-09-20 09:28
Duplicate of #4584 That's from the BinEd plugin.  Please uninstall and/or use a clean userdir.

**Closed by neilcsmith-net** 2022-09-20 09:28 UTC
Labels: kind:bug, needs:triage, can not reproduce

**Comment by rmrfchik** [comment] 2022-09-20 09:53
I've removed /home/paul/.netbeans/15/modules/org-exbin-bined-netbeans.jar and all works fine. Thanks.

**Comment by Chris2011** [comment] 2022-11-04 21:32
Hey @rmrfchik please check with latest NetBeans 15 (I think NetBeans 16 is around the corner) and with newest Bined-netbeans-plugin 0.2.4 (https://bined.exbin.org/netbeans-plugin/)
