### ISSUE TITLE
Context Help not shown

### ISSUE THREAD

**Issue by ostermannBernd** [apache/netbeans#3989] opened 2022-04-15 13:51 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

Nearly all context help files are not shown. For instance:
 Services, Servers, properties of a server: click help button
Services, MySql Server, properties: click help button
Nothing is shown.

If no help is available then the help button should be removed.

### How to reproduce

Services, Servers, properties of a server: click help button
Services, MySql Server, properties: click help button

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Windows 10

### JDK

jdk1.8.0_311

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-04-15 14:00
Duplicate of #3827 which you yourself opened!

**Closed by neilcsmith-net** 2022-04-15 14:00 UTC
Labels: kind:bug, needs:triage
