### ISSUE TITLE
Clipboard access in Netbeans on Windows.

### ISSUE THREAD

**Issue by marcfarrow** [apache/netbeans#7199] opened 2024-03-27 10:50 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

I copy text to the clipboard using an outside application such as Notepad++.  I then try to paste the text into a document opened in NetBeans.   The paste function (whether CTRL-V or Right-Click paste) will not paste expected results.  It will only paste the last text copied in NetBeans.   This happens randomly.  Once it starts happening, I have to restart the IDE to get normal copy/paste options to work.   To me it seems like NetBeans can no longer read from the Windows Clipboard, but it only able to read from the internal Clipboard for the application (in this case NetBeans).

### Language / Project Type / NetBeans Component

Java Gradle Project - Any type

### How to reproduce

The only way to reproduce is to repeatedly copy/paste items in NetBeans and outside of NetBeans until NetBeans exhibits the behavior.    The behavior usually occurs when NetBeans' JVM has not be restarted in a while.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

OpenJDK 64-Bit Server VM 14.0.1+7

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mfarich** [comment] 2024-03-27 11:24
I have the same issue.  Has happened in netbeans 14, 16, and 19 for sure that I can remember.  On both windows 11 and 10 as well as with openjdk 11.  It just seems to randomly happen after using netbeans for a while and the only solution is a restart of the application.

**Comment by mbien** [comment] 2024-03-27 12:22
closing as duplicate of https://github.com/apache/netbeans/issues/3962

**Closed** 2024-03-27 12:22 UTC
Labels: kind:bug, duplicate, needs:triage, os:windows

**Comment by DarrinWolf** [comment] 2024-12-12 19:56
This continues to happen to me. Gemini AI says the following about this - seems like a conflict between "clipboard managers" however, I have only EVER experienced this problem when using NetBeans.  Every version I have used since version 8.x has this issue:  Quite randomly, some days often, other days not a single incident, NetBeans editor will paste an older "clip" of text, and will no longer accept any newer (copied from internal or external application source) "clips".  I can paste to NotePad++, or at an external command prompt (using Windows OS, Powershell Core terminal window) no problem.  However, the attempting to paste into NetBeans fails - the pasted text is actually some older, stale "clip".  This has been frustrating me for YEARS, I always have to resort to closing and reopening NetBeans.  I even sometimes have to find a zombie Java/netbeans PID using task manager and kill it, to make sure Netbeans restarts properly, so that Ctrl-C/Ctrl-V copy/pasting finally works again...for a while anyway.  Another frustrating problem closely related:  Copying code (within NetBeans) to the clipboard with "copy as RTF" enabled, and pasting to an RTF-compatible destination editor has the same exact flaky experience.  This feature will easily stop working, and the only fix is to restart NetBeans and/or kill zombie Netbeans JVM related PIDs via task manager.  There is no combination of enabling/disabling the "copy as RTF" configuration/flag that will improve/break Ctrl-C/Ctrl-V copy/pasting.  They do not seem "tethered" as far as this buggy behavior context goes.  Just sharing to help others that find there way here via internet search results. 

`
While NetBeans is a powerful IDE, it's not immune to occasional copy/paste issues. These glitches can be frustrating, but they don't happen all the time due to a combination of factors:

**Robust Clipboard Handling:**

* **Dedicated Clipboard Mechanism:** NetBeans has its own internal clipboard system, separate from the system clipboard. This allows it to manage copied content efficiently, reducing conflicts with other applications.
* **Intelligent Paste Operations:** The IDE often analyzes the pasted content and automatically formats it to match the current context, further minimizing potential issues.

**Active Development and Bug Fixes:**

* **Community-Driven:** NetBeans is an open-source project with a dedicated community of developers. This means that issues, including copy/paste problems, are actively tracked and addressed through updates and bug fixes.
* **Regular Updates:** The NetBeans team releases regular updates to improve stability and performance, which often includes fixes for common clipboard problems.

**User-Friendly Workarounds:**

* **Clearing the NetBeans Clipboard:** In some cases, clearing the NetBeans clipboard by performing an empty copy-paste operation can resolve issues.
* **Using Keyboard Shortcuts:** Relying on keyboard shortcuts for copy/paste can sometimes bypass potential glitches.
* **Restarting the IDE:** A simple restart can often refresh the IDE's state and resolve temporary issues.

**System-Level Factors:**

* **Clipboard Managers:** Some third-party clipboard managers can interfere with NetBeans' clipboard handling. Disabling or configuring these tools might help.
* **Operating System-Specific Issues:** Occasionally, system-level bugs or conflicts with other software can cause copy/paste problems. Keeping your operating system up-to-date can minimize these issues.

**Additional Tips:**

* **Check for Updates:** Ensure you're using the latest version of NetBeans to benefit from the latest bug fixes and improvements.
* **Experiment with Settings:** Try adjusting NetBeans' settings related to clipboard behavior, such as the "Use System Clipboard" option.
* **Seek Community Support:** If you encounter persistent issues, consult the NetBeans community forums or issue trackers for specific advice and troubleshooting steps.

By understanding these factors and employing the suggested workarounds, you can significantly reduce the frequency of copy/paste problems in NetBeans and enjoy a smoother development experience.
`

**Comment by tudopatroi** [comment] 2025-03-04 21:35
My workaround for this issue on my Windows 11 with NetBeans V22 was by recording a macro in NetBeans, which basically types a few characters, then selects them, cuts and pastes them back using CTRL-X, then doing the same one more time using the Edit Copy/Paste menu. I also assigned a shortcut ctrl-shift-alt-F. In the end the screen remains in the same state, but the clipboard works.
The macro code is: "" 1234" selection-backward selection-backward selection-backward selection-backward selection-backward cut-to-clipboard " " paste-from-clipboard selection-backward selection-backward selection-backward selection-backward selection-backward cut-to-clipboard paste-from-clipboard selection-backward selection-backward selection-backward selection-backward selection-backward selection-backward cut-to-clipboard"
