### ISSUE TITLE
Unable to copy and paste

### ISSUE THREAD

**Issue by philip-lourandos-afrocentric** [apache/netbeans#5483] opened 2023-02-13 07:20 UTC
### Apache NetBeans version

Apache NetBeans 16

### What happened

I've been seeing this odd behaviour. I am able to copy and paste values from other windows applications, but then something happens where I copy some text from the terminal/app but in netbeans when pasting(CTRL+V or right click paste) it will paste the last value that was copied from Netbeans

### How to reproduce

This seems to be intermittent 

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

19.0.2, liberica, AMD64

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2023-02-13 14:03
This is a duplicate of #3962 Please have a look through there and try some of the suggestions.  We're still unclear what the cause of this issue is, so help in replicating, etc. is very useful.  Thanks!

**Closed by neilcsmith-net** 2023-02-13 14:03 UTC
Labels: kind:bug, duplicate
