### ISSUE TITLE
Formatting of "uses" broken

### ISSUE THREAD

**Issue by rarila** [apache/netbeans#6465] opened 2023-09-18 16:11 UTC
### Apache NetBeans version

Apache NetBeans 19

### What happened

Formatting of "uses" seems to be broken.

Whatever option one selects in `Options/Editor/Formatting/PHP/Uses`, you'll end up with the standard formatting:

```php
<?php

namespace MyProject;

use Vendor\Package\Type;
use Vendor\Package\Type2;
use const Vendor\Package\CONSTANT;
use function Vendor\Package\fnc;
```

Also `Options/Editor/Formatting/PHP/Blank_Lines/Between_Use_Types` is ignored

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Win

### JDK

OpenJDK 20.0.2

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by junichi11** [comment] 2023-09-18 19:33
@rarila Please write an expected result and an actual result with your exact steps to reproduce it.

e.g.
Steps:
1. ...
2. ...
3. ...

Expected reuslt:

...

Actual result

...

**Comment by junichi11** [comment] 2023-09-18 19:38
@rarila 
NOTE: `Options/Editor/Formatting/PHP/Uses` is used with `Fix Imports` feature. They are not used with `Source > Format`.

**Comment by rarila** [comment] 2023-09-23 07:08
@junichi11
Sorry, I wasn’t clear. The problem occurs when using with ``Fix Imports``.

Ok, an step-by-step example (same effect with other settings, they are simply ignored):

### Settings and code:

``Options/Editor/Formatting/PHP/Uses`` = "[×] Put in PSR-12 Order"
``Options/Editor/Formatting/PHP/Blank_Lines/Between_Use_Types`` = "1"

```
<?php

namespace MyProject;

use Vendor\Package\Type;
use Vendor\Package\Type2;

use function Vendor\Package\fnc;

use const Vendor\Package\CONSTANT;
```

### Action:

Execute ``Fix Imports …`` command

### Expected result:

```
<?php

namespace MyProject;

use Vendor\Package\Type;
use Vendor\Package\Type2;

use function Vendor\Package\fnc;

use const Vendor\Package\CONSTANT;
```


### Actual result:

```
<?php

namespace MyProject;

use Vendor\Package\Type;
use Vendor\Package\Type2;
use const Vendor\Package\CONSTANT;
use function Vendor\Package\fnc;
```
No blank lines, no PSR-12 order

**Comment by junichi11** [comment] 2023-09-23 12:12
@rarila Please write the exact example code. (Please write all code.)
I can't reproduce it if I copy&paste your code then run "Fix imports...".

**Comment by rarila** [comment] 2023-09-23 13:28
@junichi11 Ok, now things get interesting. I already thought that can’t be that nobody noticed such a fundamental problem nor the tests do.

Posting the exact code makes no sense as it happens with any code.

The next thing I probably should try is testing a plain v19 without importing any settings from v18. Also having a look at the IDE log could probably help.

Stay tuned …

**Comment by junichi11** [comment] 2023-09-23 14:30
@rarila Well, write again! Please provide your exact code to reproduce it. Otherwise, we cannot do anything even if you have a problem. I mean an **EXAMPLE** code. I cannot understand why you don't do it.

**Comment by rarila** [comment] 2023-09-23 14:44
@junichi11 Simply because the code isn’t the problem.

Sofar I found out that the problem is somewhere in the ``nbproject`` folder:

The problem happens only on existing projects. In my investigations I now have copied a project without the nbproject folder and then created a new project from existing sources. With this project everything works now as expected.

Next thing I examine is what's the difference in the two project settings…

I’ll be back…

**Comment by rarila** [comment] 2023-09-23 15:20
Ok, problem "**solved**".

In existing projects there is the following line in ``nbproject\project.properties``:

``auxiliary.org-netbeans-modules-editor-indent.CodeStyle.usedProfile=project``

As soon as you remove it, all works as expected.

I don’t know what it is/was for, who has written it. At least something changed from v18 to v19 that makes this line a problem now,

**Comment by rarila** [comment] 2023-09-23 16:29
@junichi11 Do you know a way to clean up project files or is there any documentation of those files. Some of my projects may even been created with v8 so I guess there might be a lot of unused trash in there.

**Comment by junichi11** [comment] 2023-09-23 21:55
Not a bug. NetBeans should not change the option. (Project properties > Formatting > Use project specific options)

**Comment by junichi11** [comment] 2023-09-23 22:16
Closing because we cannot do anything.

**Closed by junichi11** 2023-09-23 22:16 UTC
Labels: invalid, PHP
