### ISSUE TITLE
A java.lang.NoClassDefFoundError has occurred.

### ISSUE THREAD

**Issue by danilomagrini** [apache/netbeans#7514] opened 2024-06-24 20:07 UTC
### Apache NetBeans version

Apache NetBeans 22

### What happened

A java.lang.NoClassDefFoundError has occurred.  If you are running the [latest](https://netbeans.apache.org/download) version of NetBeans you can [report this](https://netbeans.apache.org/nb/report-issue), including a copy of your messages.log file as an attachment.  The messages.log file is located in [this folder](file:///home/danilo/.netbeans/21/var/log/).

### Language / Project Type / NetBeans Component

Web Application with maven

### How to reproduce

I dont know

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Ubuntu 22.04

### JDK

jdk 17.0.10

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Editor Parsing Loop (22-0d0bfcf3faf364a2643238f2a44e1bb6eb8217bd)"]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
Caused: java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory
	at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:169)
	at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:57)
	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:197)
	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:95)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:94)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:128)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:172)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:122)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:278)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:197)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveAlways(DefaultArtifactResolver.java:152)
	at org.netbeans.modules.maven.embedder.MavenEmbedder.resolveArtifact(MavenEmbedder.java:424)
	at org.netbeans.modules.maven.j2ee.MavenJsfReferenceImplementationProvider.artifactPathFor(MavenJsfReferenceImplementationProvider.java:81)
	at org.netbeans.modules.web.jsf.editor.facelets.FaceletsLibrarySupport.parseLibraries(FaceletsLibrarySupport.java:361)
	at org.netbeans.modules.web.jsf.editor.facelets.FaceletsLibrarySupport._findLibraries(FaceletsLibrarySupport.java:325)
	at org.netbeans.modules.web.jsf.editor.facelets.FaceletsLibrarySupport.findLibraries(FaceletsLibrarySupport.java:270)
	at org.netbeans.modules.web.jsf.editor.facelets.FaceletsLibrarySupport.getNamespaceLibraryMapping(FaceletsLibrarySupport.java:173)
	at org.netbeans.modules.web.jsf.editor.JsfSupportImpl.getLibrary(JsfSupportImpl.java:224)
	at org.netbeans.modules.web.jsf.editor.HtmlSourceTask.run(HtmlSourceTask.java:121)
	at org.netbeans.modules.web.jsf.editor.HtmlSourceTask.run(HtmlSourceTask.java:47)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
[messages.log](https://github.com/user-attachments/files/15960737/messages.log)

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2024-06-24 20:09
Duplicate of https://github.com/apache/netbeans/issues/7449, https://github.com/apache/netbeans/issues/7436, https://github.com/apache/netbeans/issues/7354 and https://github.com/apache/netbeans/issues/7488. Fixed by https://github.com/apache/netbeans/pull/7464

**Closed by matthiasblaesing** 2024-06-24 20:09 UTC
Labels: kind:bug, needs:triage
