### ISSUE TITLE
Java Formatter incorrect indentation of try..catch inside switch.

### ISSUE THREAD

**Issue by jindrapetrik** [apache/netbeans#6666] opened 2023-11-07 19:04 UTC
### Apache NetBeans version

Apache NetBeans 19

### What happened

I am trying to format following code with menu Source->Format command:
```java
        int k = 5;
        switch (k) {
            case 1:
                try {
                    System.out.println("hello from try");
                } catch (Exception ex) {
                    System.out.println("in catch");
                }
                break;
            case 2:
                System.out.println("in 2");
                break;
        }
```

The result:
```java
        int k = 5;
        switch (k) {
            case 1:
                try {
                System.out.println("hello from try");
            } catch (Exception ex) {
                System.out.println("in catch");
            }
            break;
            case 2:
                System.out.println("in 2");
                break;
        }
```

The catch clause till break is one level lower than it should be.

### How to reproduce

Write try..catch statement inside switch case and hit Source->Format.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

19, 64bit

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment] 2023-11-09 14:45
Duplicate of #5323 I think.

**Closed by neilcsmith-net** 2023-11-09 14:45 UTC
Labels: kind:bug, needs:triage
