### ISSUE TITLE
Suggestions for adjusting the structure of Maven's modular project

### ISSUE THREAD

**Issue by lyh061619** [apache/netbeans#6814] opened 2023-12-07 15:33 UTC
### Description

The modules module is opened separately in Projects, causing a complete lack of tree structure and confusion. It supports opening sub modules directly in the modules directory instead of opening them separately. Opening Maven Moulds separately has no hierarchical relationship and looks very bad

The bad experience is shown in the following picture:
[
![m1](https://github.com/apache/netbeans/assets/15118571/5ea30662-8b3e-4201-a756-ae05041dc1ba)
](url)

A good experience is designed as follows:
![mw](https://github.com/apache/netbeans/assets/15118571/0c8f96a8-2917-408a-948b-245cc1644a83)

### Are you willing to submit a pull request?

No

**Comment by matthiasblaesing** [comment] 2023-12-07 16:53
This is a duplicate of #6215

**Closed by matthiasblaesing** 2023-12-07 16:53 UTC
Labels: kind:feature, needs:triage
