### ISSUE TITLE
A java.util.ServiceConfigurationError has occurred

### ISSUE THREAD

**Issue by cienegsan** [apache/netbeans#7402] opened 2024-05-25 16:07 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:339)
	at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:320)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:205)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:134)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:125)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:529)
	at java.base/java.lang.Class.forName(Class.java:508)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:669)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:632)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:625)
	at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2166)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.<clinit>(PolyglotContextImpl.java:100)
	at com.oracle.truffle.polyglot.HostException.<init>(HostException.java:58)
	at com.oracle.truffle.polyglot.PolyglotImpl.<clinit>(PolyglotImpl.java:92)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:173)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.ServiceLoader$ProviderImpl$2.run(ServiceLoader.java:793)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:798)
Caused: java.util.ServiceConfigurationError: org.graalvm.polyglot.impl.AbstractPolyglotImpl: Provider com.oracle.truffle.polyglot.PolyglotImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:809)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:725)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1397)
	at org.graalvm.polyglot.Engine$1.searchServiceLoader(Engine.java:747)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:733)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:707)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:707)
	at org.graalvm.polyglot.Engine.access$000(Engine.java:106)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:115)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:304)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:542)
	at org.netbeans.libs.graalsdk.impl.GraalEnginesProvider.lambda$enumerateLanguages$1(GraalEnginesProvider.java:153)
	at org.netbeans.libs.graalsdk.impl.GraalContext.executeWithClassLoader(GraalContext.java:117)
	at org.netbeans.libs.graalsdk.impl.GraalEnginesProvider.enumerateLanguages(GraalEnginesProvider.java:152)
	at org.netbeans.libs.graalsdk.impl.GraalEnginesProvider.factories(GraalEnginesProvider.java:61)
	at org.netbeans.api.scripting.Scripting$EngineManager.populateExtras(Scripting.java:148)
	at org.netbeans.api.scripting.Scripting$EngineManager.<init>(Scripting.java:133)
	at org.netbeans.api.scripting.Scripting.build(Scripting.java:120)
	at org.netbeans.api.scripting.Scripting.createManager(Scripting.java:65)
	at org.netbeans.modules.templates.ScriptingCreateFromTemplateHandler.getEngine(ScriptingCreateFromTemplateHandler.java:150)
	at org.netbeans.modules.templates.ScriptingCreateFromTemplateHandler.engine(ScriptingCreateFromTemplateHandler.java:162)
	at org.netbeans.modules.templates.ScriptingCreateFromTemplateHandler.accept(ScriptingCreateFromTemplateHandler.java:68)
	at org.netbeans.api.templates.CreateFromTemplateImpl.lambda$prepare$1(CreateFromTemplateImpl.java:134)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:193)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950)
	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:144)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:574)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:662)
	at org.netbeans.api.templates.CreateFromTemplateImpl.prepare(CreateFromTemplateImpl.java:135)
	at org.netbeans.api.templates.CreateFromTemplateImpl.lambda$build$0(CreateFromTemplateImpl.java:86)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.netbeans.api.templates.CreateFromTemplateImpl.build(CreateFromTemplateImpl.java:84)
	at org.netbeans.api.templates.FileBuilder.build(FileBuilder.java:267)
	at org.netbeans.api.templates.FileBuilder.createFromTemplate(FileBuilder.java:369)
	at org.openide.loaders.MultiDataObject.handleCreateFromTemplate(MultiDataObject.java:860)
	at org.openide.loaders.MultiDataObject.handleCreateFromTemplate(MultiDataObject.java:841)
	at org.netbeans.modules.java.JavaDataObject.handleCreateFromTemplate(JavaDataObject.java:117)
	at org.openide.loaders.DataObject$CreateAction.run(DataObject.java:1571)
	at org.openide.loaders.DataObjectPool$1WrapAtomicAction.run(DataObjectPool.java:236)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.openide.loaders.DataObjectPool.runAtomicAction(DataObjectPool.java:261)
	at org.openide.loaders.DataObject.invokeAtomicAction(DataObject.java:1025)
	at org.openide.loaders.DataObject.createFromTemplate(DataObject.java:957)
	at org.netbeans.modules.java.project.ui.NewJavaFileWizardIterator.instantiate(NewJavaFileWizardIterator.java:345)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1050)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:602)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:436)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:223)
	at org.openide.loaders.TemplateWizardIteratorWrapper.instantiate(TemplateWizardIteratorWrapper.java:135)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1605)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1546)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:67)
	at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2233)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)

### Language / Project Type / NetBeans Component

Java with ANT

### How to reproduce

Tryin to create a Class

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Windows 11

### JDK

22..1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

[messages.log](https://github.com/apache/netbeans/files/15444140/messages.log)

### Are you willing to submit a pull request?

Yes

**Comment by matthiasblaesing** [comment] 2024-05-25 18:20
Duplicate of #7245 and fixed in NB22 (currently in release vote). Use JDK 21 with NB21.

**Closed by matthiasblaesing** 2024-05-25 18:20 UTC
Labels: kind:bug, needs:triage
