### ISSUE TITLE
move class refactoring: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null

### ISSUE THREAD

**Issue by DavidGradwell** [apache/netbeans#5642] opened 2023-03-09 13:18 UTC
### Apache NetBeans version

Apache NetBeans 17

### What happened

Whilst trying to move a class from one package to another in the same project, I repeatedly get:

java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null. Please report a bug against Java Refactoring module and attach your var/log/messages.log.

If I proceed then the refactor fails.

### How to reproduce

Set up a Java Maven project with two source packages and several java source files within each.  Make sure it all compiles using Clean and Build.

Drag one source file from one package to the other and the problem occurs.

Going right click/refactor/move hits the same issue.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Mac OS Ventura 13.2.1

### JDK

Product Version: Apache NetBeans IDE 17 Java: 16-ea; OpenJDK 64-Bit Server VM 16-ea+27-1884 Runtime: OpenJDK Runtime Environment 16-ea+27-1884 System: Mac OS X version 10.16 running on x86_64; UTF-8; en_GB (nb) User directory: /Users/davidjlgradwell/Library/Application Support/NetBeans/17 Cache directory: /Users/davidjlgradwell/Library/Caches/NetBeans/17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

I have never encountered this problem before installing NetBeans 17, however I'm not sure when was the last time a refactor succeeded.

Also, the message "Please report a bug against Java Refactoring module and attach your var/log/messages.log." gives an incorrect location for the log file or such a file does not exist (search failed).

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2023-03-09 21:37
sounds like a duplicate of #3725

**Comment by mbien** [comment] 2023-03-09 21:39
thanks for the reproduction instructions!

**Comment by giri-gonzai** [comment] 2023-07-30 23:09
Anyone found any resolution or work around to this. This is a blocker for any refactor work. FYI: Even after stashing all the changes and then applying gradle clean and build results in the same error. The issue is somehow persisting into the being manifested itself in the code/build history and even after invalidating caches.

**Comment by mbien** [comment] 2023-08-10 03:21
@DavidGradwell I can't reproduce this issue with a NB 18 following the steps you posted. I can drag the files from package to package and got no exceptions.

**Closed** 2024-04-11 08:37 UTC
Labels: kind:bug, duplicate, Java, nb-javac
