### ISSUE TITLE
jshell doesn't initialize  

### ISSUE THREAD

**Issue by suhaila-5** [apache/netbeans#6692] opened 2023-11-13 19:52 UTC
### Apache NetBeans version

Apache NetBeans 19

### What happened

i was trying to run the j shell for a project that I works on  and the project is workers perfectly fine and  I was trying to use j shell  and this error keeps showing up and its very annoying I tried clean and built for the project and checked for any ide update and restarted the app many times and nothing worked   and this is the error message 
![image](https://github.com/apache/netbeans/assets/114446710/2e401f93-d349-4d1c-acae-dc657cd14871)
 
 ```

 Could not initialize JShell: Launching JShell execution engine threw: Failed remote launch: java.util.concurrent.ExecutionException: com.sun.jdi.connect.VMStartException: VM initialization failed for: C:\Program Files\Java\jdk-17.0.1\bin\java -classpath C:\Program Files\NetBeans-19\netbeans\java\modules\ext\nb-mod-jshell-probe.jar;D:\javaj\mavenproject1\target\classes --add-modules jdk.jshell,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED --add-exports mavenproject1/com.mycompany.mavenproject1=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_shmem,address=javadebug14027,suspend=y org.netbeans.lib.jshell.agent.AgentWorker 57728 @ com.sun.jdi.CommandLineLaunch (defaults: home=C:\Program Files\Java\jdk-17.0.1, options=, main=, suspend=true, quote=", vmexec=java) -- {home=home=C:\Program Files\Java\jdk-17.0.1, options=options=-classpath "C:\Program Files\NetBeans-19\netbeans\java\modules\ext\nb-mod-jshell-probe.jar;D:\javaj\mavenproject1\target\classes" --add-modules jdk.jshell,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED --add-exports mavenproject1/com.mycompany.mavenproject1=ALL-UNNAMED, main=main=org.netbeans.lib.jshell.agent.AgentWorker 57728, suspend=suspend=true, quote=quote=", vmexec=vmexec=java}
|  	caused by: Failed remote launch: java.util.concurrent.ExecutionException: com.sun.jdi.connect.VMStartException: VM initialization failed for: C:\Program Files\Java\jdk-17.0.1\bin\java -classpath C:\Program Files\NetBeans-19\netbeans\java\modules\ext\nb-mod-jshell-probe.jar;D:\javaj\mavenproject1\target\classes --add-modules jdk.jshell,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED --add-exports mavenproject1/com.mycompany.mavenproject1=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_shmem,address=javadebug14027,suspend=y org.netbeans.lib.jshell.agent.AgentWorker 57728 @ com.sun.jdi.CommandLineLaunch (defaults: home=C:\Program Files\Java\jdk-17.0.1, options=, main=, suspend=true, quote=", vmexec=java) -- {home=home=C:\Program Files\Java\jdk-17.0.1, options=options=-classpath "C:\Program Files\NetBeans-19\netbeans\java\modules\ext\nb-mod-jshell-probe.jar;D:\javaj\mavenproject1\target\classes" --add-modules jdk.jshell,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED --add-exports mavenproject1/com.mycompany.mavenproject1=ALL-UNNAMED, main=main=org.netbeans.lib.jshell.agent.AgentWorker 57728, suspend=suspend=true, quote=quote=", vmexec=vmexec=java}
|  	caused by: com.sun.jdi.connect.VMStartException: VM initialization failed for: C:\Program Files\Java\jdk-17.0.1\bin\java -classpath C:\Program Files\NetBeans-19\netbeans\java\modules\ext\nb-mod-jshell-probe.jar;D:\javaj\mavenproject1\target\classes --add-modules jdk.jshell,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED --add-exports mavenproject1/com.mycompany.mavenproject1=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_shmem,address=javadebug14027,suspend=y org.netbeans.lib.jshell.agent.AgentWorker 57728
|  	caused by: VM initialization failed for: C:\Program Files\Java\jdk-17.0.1\bin\java -classpath C:\Program Files\NetBeans-19\netbeans\java\modules\ext\nb-mod-jshell-probe.jar;D:\javaj\mavenproject1\target\classes --add-modules jdk.jshell,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED --add-exports mavenproject1/com.mycompany.mavenproject1=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_shmem,address=javadebug14027,suspend=y org.netbeans.lib.jshell.agent.AgentWorker 57728

```

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

widows 11 pro  developer insider preview build 23580

### JDK

jdk 17.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2023-12-17 05:10
I see in your log `C:\Program Files\Java\jdk-17.0.1`

so I tried to replicate it with NB 20 on win 11 and JShell seemed to be working fine.
I tested both on 17.0.9 (MS) and 21.0.1 (zulu)

![image](https://github.com/apache/netbeans/assets/114367/6191f902-9b7f-4ac6-9cd9-fd87fb4abc2c)

If you know how to reproduce this issue, please post the required steps, otherwise we might have to close this issue after a while.

**Comment by matthiasblaesing** [comment] 2023-12-17 07:32
I saw issues starting jshell because the module path was not properyly setup. Please try to run the invocation standalone:

```
C:\Program Files\Java\jdk-17.0.1\bin\java -classpath C:\Program Files\NetBeans-19\netbeans\java\modules\ext\nb-mod-jshell-probe.jar;D:\javaj\mavenproject1\target\classes --add-modules jdk.jshell,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED --add-exports mavenproject1/com.mycompany.mavenproject1=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_shmem,address=javadebug14027,suspend=y
```

The command was extracted from the output you provided, so you can adjust it if the project changed in between. I expect, that this will fail and that the error message will be more helpful.

**Comment by mbien** [comment] 2023-12-17 07:56
I think I can reproduce it now with: right click on `maven project -> Execute Java Shell`, I didn't realize this is about the execute action and not about the open action since no steps were provided which would help to reproduce this.

**Comment by suhaila-5** [comment] 2023-12-30 11:55
@mbien unfortunately I still couldn't solve this problem

**Comment by matthiasblaesing** [comment] 2023-12-30 21:23
The problem seems to be, that JShell is always initialized in "modular" mode. This requires a clean project setup and dependencies that work in modular mode. My minimal test setup, that reproduces the issue (@suhaila-5 why did you not follow my hint to pin-point the problem?!) is here:

[mavenproject1.zip](https://github.com/apache/netbeans/files/13799173/mavenproject1.zip)

Running `Execute JShell` there yields: 

```
|  Could not initialize JShell: Launching JShell execution engine threw: Failed remote launch: java.util.concurrent.ExecutionException: com.sun.jdi.connect.VMStartException: VM initialization failed for: /home/matthias/bin/jdk-21/bin/java -classpath /home/matthias/src/netbeans/nbbuild/netbeans/java/modules/ext/nb-mod-jshell-probe.jar:/tmp/mavenproject1/target/classes:/home/matthias/.m2/repository/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar:/home/matthias/.m2/repository/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar --add-modules jdk.jshell,jersey.client,jersey.core,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_socket,address=localhost:33139,suspend=y,includevirtualthreads=n org.netbeans.lib.jshell.agent.AgentWorker 36067 @ com.sun.jdi.CommandLineLaunch (defaults: home=/home/matthias/bin/jdk-21, options=, main=, suspend=true, quote=", vmexec=java, includevirtualthreads=n) -- {home=home=/home/matthias/bin/jdk-21, options=options=-classpath /home/matthias/src/netbeans/nbbuild/netbeans/java/modules/ext/nb-mod-jshell-probe.jar:/tmp/mavenproject1/target/classes:/home/matthias/.m2/repository/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar:/home/matthias/.m2/repository/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar --add-modules jdk.jshell,jersey.client,jersey.core,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED, main=main=org.netbeans.lib.jshell.agent.AgentWorker 36067, suspend=suspend=true, quote=quote=", vmexec=vmexec=java, includevirtualthreads=includevirtualthreads=n}
|  	caused by: Failed remote launch: java.util.concurrent.ExecutionException: com.sun.jdi.connect.VMStartException: VM initialization failed for: /home/matthias/bin/jdk-21/bin/java -classpath /home/matthias/src/netbeans/nbbuild/netbeans/java/modules/ext/nb-mod-jshell-probe.jar:/tmp/mavenproject1/target/classes:/home/matthias/.m2/repository/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar:/home/matthias/.m2/repository/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar --add-modules jdk.jshell,jersey.client,jersey.core,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_socket,address=localhost:33139,suspend=y,includevirtualthreads=n org.netbeans.lib.jshell.agent.AgentWorker 36067 @ com.sun.jdi.CommandLineLaunch (defaults: home=/home/matthias/bin/jdk-21, options=, main=, suspend=true, quote=", vmexec=java, includevirtualthreads=n) -- {home=home=/home/matthias/bin/jdk-21, options=options=-classpath /home/matthias/src/netbeans/nbbuild/netbeans/java/modules/ext/nb-mod-jshell-probe.jar:/tmp/mavenproject1/target/classes:/home/matthias/.m2/repository/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar:/home/matthias/.m2/repository/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar --add-modules jdk.jshell,jersey.client,jersey.core,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED, main=main=org.netbeans.lib.jshell.agent.AgentWorker 36067, suspend=suspend=true, quote=quote=", vmexec=vmexec=java, includevirtualthreads=includevirtualthreads=n}
|  	caused by: com.sun.jdi.connect.VMStartException: VM initialization failed for: /home/matthias/bin/jdk-21/bin/java -classpath /home/matthias/src/netbeans/nbbuild/netbeans/java/modules/ext/nb-mod-jshell-probe.jar:/tmp/mavenproject1/target/classes:/home/matthias/.m2/repository/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar:/home/matthias/.m2/repository/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar --add-modules jdk.jshell,jersey.client,jersey.core,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_socket,address=localhost:33139,suspend=y,includevirtualthreads=n org.netbeans.lib.jshell.agent.AgentWorker 36067
|  	caused by: VM initialization failed for: /home/matthias/bin/jdk-21/bin/java -classpath /home/matthias/src/netbeans/nbbuild/netbeans/java/modules/ext/nb-mod-jshell-probe.jar:/tmp/mavenproject1/target/classes:/home/matthias/.m2/repository/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar:/home/matthias/.m2/repository/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar --add-modules jdk.jshell,jersey.client,jersey.core,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_socket,address=localhost:33139,suspend=y,includevirtualthreads=n org.netbeans.lib.jshell.agent.AgentWorker 36067
```

Now running the last command manually yields:

```
matthias@enterprise:/tmp$ /home/matthias/bin/jdk-21/bin/java -classpath /home/matthias/src/netbeans/nbbuild/netbeans/java/modules/ext/nb-mod-jshell-probe.jar:/tmp/mavenproject1/target/classes:/home/matthias/.m2/repository/com/sun/jersey/jersey-client/1.18.1/jersey-client-1.18.1.jar:/home/matthias/.m2/repository/com/sun/jersey/jersey-core/1.18.1/jersey-core-1.18.1.jar --add-modules jdk.jshell,jersey.client,jersey.core,mavenproject1 --add-reads jdk.jshell=ALL-UNNAMED -Xdebug -Xrunjdwp:transport=dt_socket,address=localhost:33139,suspend=y,includevirtualthreads=n org.netbeans.lib.jshell.agent.AgentWorker 36067                                   
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jersey.client not found
matthias@enterprise:/tmp$ 
```

`com.sun.jersey:jersey-client:1.18.1` is not modular, so `jersey.client` is the "guessed" module name. Seems JShell does not like it.

The real problem from my POV though is, that this project is not modular, so should not have been invoked in modular mode.

**Comment by matthiasblaesing** [comment] 2024-01-02 17:34
@suhaila-5 please have a look at #6905. A testbuild is available from the checks page: https://github.com/apache/netbeans/actions/runs/7387734298 or directly: https://github.com/apache/netbeans/actions/runs/7387734298/artifacts/1143554624.

Thank you.

**Comment by matthiasblaesing** [comment] 2024-01-10 20:05
@suhaila-5 can I assume, that your reaction to my comment means, that you tested the build and it fixed the issue?

**Closed** 2024-01-13 10:42 UTC
Labels: kind:bug, Java, pending-response
