### ISSUE TITLE
copy/paste bug in Netbeans

### ISSUE THREAD

**Issue by vedha-vikash-pixel** [apache/netbeans#4737] opened 2022-10-05 18:53 UTC
### Apache NetBeans version

Apache NetBeans 15

### What happened

I tried to copy code from a browser and paste it to Netbeans  but the problem was it was not copying . I could only drag and drop it into the editor of the IDE. 
Moreover I could not copy from the Netbeans and paste it outside the IDE as well . I think there is definitely a problem with copy/paste feature in the IDE.

### How to reproduce

The problem does not happen all the time . It only happens sometimes and henceforth could not be reproduced all the time . But there is always a particular  time that this issue can be reproduced .

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 10

### JDK

16

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by Ohhama1** [comment] 2022-10-05 23:28
情けなき話、こののち、何をすべきでしょうか？

**Comment by mbien** [comment] 2022-10-06 05:09
sounds like a duplicate of #3962

closing until proven wrong :)

**Closed by mbien** 2022-10-06 05:09 UTC
Labels: kind:bug, needs:triage

**Comment by NewLifeDreamer** [comment] 2023-01-17 18:03
The same problem.
After launching "Create New File" wizard (for creating a new class etc. in Java) usual operations - copy & paste are not working any more - not possible to copy a piece of a text from a web browser to IDE. Only restarting of the IDE helps.
Windows 11 Home, i5-11400H, 16 GB RAM, Intel SSD, GeForce RTX 3050 Ti Laptop GPU 4 GB
