### ISSUE TITLE
Context menu "Open Required Projects >" opens an defunct sub-menu

### ISSUE THREAD

**Issue by cstamas** [apache/netbeans#7720] opened 2024-09-02 13:50 UTC
### Apache NetBeans version

Apache NetBeans 22

### What happened

Opening a Maven project, I just wanted to "Open All Required Projects" but cannot. In any FlatLaf version it does NOT work. It works in GTK+ or other ones (but Nimbus/Metal are unusable due HiDPI not applied).

https://github.com/user-attachments/assets/34404655-adc5-4422-ae70-93cabb91e86b

### Language / Project Type / NetBeans Component

Java/Maven

### How to reproduce

This is consistently happening.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Fedora 40 WS, Intel CPU, AMD GPU, Wayland

### JDK

Bundled with NB 22

### Apache NetBeans packaging

Third-party package

### Anything else

I used flatpak package of NB 22 https://flathub.org/apps/org.apache.netbeans

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2024-09-02 16:59
https://github.com/apache/netbeans/blob/33d11303269b338a95e47681e3a1f66d704fd09d/ide/projectui/src/org/netbeans/modules/project/ui/actions/OpenSubprojects.java#L159-L164

this would be the entry point for the lazy init logic. I checked and all UI calls are made on EDT. A few fields like `initialized` should be changed to `volatile` there, since the `subProjects` Set is initialized in the background, but worst what could happen is that this gets initialized multiple times - this would not explain why item selection is not working.

**Comment by mbien** [comment] 2024-09-02 17:59
@cstamas unfortunately I can't reproduce it. But I cleaned up the lazy init logic a bit. It will create the sub-menu only once now - previously it re-created it a few times. Curious if this fixes the issue.

this should create a devbuild for testing
https://github.com/apache/netbeans/actions/runs/10671342404?pr=7723

**Comment by cstamas** [comment] 2024-09-02 18:13
In the meantime just to exclude any flatpak peculiarity (sandboxing and yada yada), I downloaded ZIP from NB DL page and ran it on JDK 21.0.4 and _very same issue_ happens.

**Comment by cstamas** [comment] 2024-09-02 18:17
Yup, it works now!

![image](https://github.com/user-attachments/assets/d6703dc7-0015-44d9-80a2-ec31de6220ea)

**Comment by mbien** [comment] 2024-09-02 19:25
perfect! So the wayland-flatlaf (+HighDPI?) combo has problems when the menu changes between two `getPopupMenu()` calls.

The menu re-creation in the initialization code was a bit of a red flag, since a comment did claim that this should create the menu only once.

(and good to know that the music didn't affect the context menu ;))

**Comment by mbien** [comment] 2024-09-03 12:46
fix got merged to delivery, so it should be in NB23 rc3 once its built.

closing since github seems to only automatically close issues when things are merged directly to master.

**Closed by mbien** 2024-09-03 12:46 UTC
Labels: kind:bug, Look and Feel, UI, os:linux
