### ISSUE TITLE
Lombok Annotation are  not processes  in the Apache Netbeans 20 Release 

### ISSUE THREAD

**Issue by danielmwai** [apache/netbeans#6802] opened 2023-12-06 12:18 UTC
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

Lombok annotations  are  not  processed  in the  IDE anymore in the  error is as  shown  below  `Annotation processor lombok.launch.AnnotationProcessorHider$AnnotationProcessor failed with an exception: qualid
  lombok.javac.JavacImportList.getFullyQualifiedNameForSimpleName(JavacImportList.java:48)
  lombok.core.TypeResolver.typeRefToFullyQualifiedName(TypeResolver.java:59)
  lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:247)
  lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:96)
  lombok.javac.JavacNode.traverse(JavacNode.java:132)
  lombok.javac.JavacAST.traverseChildren(JavacAST.java:133)
  lombok.javac.JavacNode.traverse(JavacNode.java:95)
  lombok.javac.JavacAST.traverseChildren(JavacAST.java:133)
  lombok.javac.JavacNode.traverse(JavacNode.java:90)
  lombok.javac.JavacAST.traverse(JavacAST.java:129)
  lombok.javac.JavacTransformer.transform(JavacTransformer.java:80)
  lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:324)
  lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:151)
  lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:201)
  lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:99)
  org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.process(APTUtils.java:1004)
  com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1011)
  com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:927)
  com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2300(JavacProcessingEnvironment.java:113)
  com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1255)
  com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1370)
  com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1272)
  org.netbeans.lib.nbjavac.services.NBJavaCompiler.processAnnotations(NBJavaCompiler.java:64)
  com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:117...`   
![Screenshot from 2023-12-06 15-06-22](https://github.com/apache/netbeans/assets/2469990/8c5335d4-7246-4f12-85cb-2ccf138aa8b7)

### How to reproduce

Using the  annotation  on a class  file  import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author nzaniela
 */

@Slf4j
public class QwertyKeyPad   --

  on a  method  log  the  ide  treats  it  an  as error /  cant process  

            public void loadingResized(DataCompute de) {
                  // ---
                log.info(" Data Computed ",  comp.getSize());   //this  gives  an  error  on the  ide  but  compilation  is  OK
            }

### Did this work correctly in an earlier version?

Apache NetBeans 19

### Operating System

Fedora 38

### JDK

11, 17 , 21

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

**Comment by NicolaIsotta** [comment] 2023-12-06 13:41
Have you tried updating Lombok to 1.18.30 ?

**Comment by matthiasblaesing** [comment] 2023-12-06 17:14
@NicolaIsotta has the right suggestion. This is a duplicate of https://github.com/projectlombok/lombok/issues/3468 and https://github.com/projectlombok/lombok/issues/3393.

The TL;DR version is: The price for using lombok is high because it regularly breaks on newer JDKs. And thus I strongly resist people wanting to use lombok @work. We have some legacy code and for that the situation was improved by specifying the lombok version as a property and I override that in my `settings.xml` to point to a recent version of lombok that makes it work again, without having to modify the project.

**Closed as completed by matthiasblaesing** 2023-12-06 17:14 UTC
Labels: kind:bug, already fixed

**Comment by hello-earth-gh** [comment] 2023-12-21 17:37
just as a reference - I had a slightly different problem, although searching got me here anyway. After upgrading to Netbeans 20 my projects started having problem with Lombok - compiling just fine but becoming all red in the editor.
The problem was that somehow Netbeans failed to see the extra stuff generated by Lombok - especially the getters and the setters. I had to follow the advice here https://stackoverflow.com/a/54168043/57033 to get it going. (need to add lombok specific path in maven-compiler-plugin)
