### ISSUE TITLE
php code complete locks up IDE

### ISSUE THREAD

**Issue by OS4** [apache/netbeans#5313] opened 2023-01-18 13:00 UTC
### Apache NetBeans version

Apache NetBeans latest daily build

### What happened

The auto complete feature for PHP functions and other language features lock the IDE. Variables seem to be fine.

### How to reproduce

Start typing a language feature or user defined function, e.g. is_str
 ~  is_string pops up in an auto complete bubble
Select is_string
 ~  is_string is not displayed and the text is_str is deleted
Start typing a language feature or user defined function, e.g. is_str
 ~  is_string pops up in an auto complete bubble
Select is_string
 ~  The IDE locks solid.

### Did this work correctly in an earlier version?

Apache NetBeans 12.6 or earlier

### Operating System

Ubuntu 22.10 on Intel i7 64 bit

### JDK

openjdk version "18.0.2-ea" 2022-07-19 OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu2) OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-2, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Occurs every time

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by junichi11** [comment] 2023-12-31 02:42
I can't reproduce it.

Are there exceptions in your IDE log?

![nb-php-gh-5313](https://github.com/apache/netbeans/assets/738383/07610cc3-78bb-4feb-b2ff-a764c2e5fb9f)

```
Product Version: Apache NetBeans IDE 20
Java: 19.0.2; OpenJDK 64-Bit Server VM 19.0.2+7-Ubuntu-0ubuntu322.04
Runtime: OpenJDK Runtime Environment 19.0.2+7-Ubuntu-0ubuntu322.04
System: Linux version 6.2.0-39-generic running on amd64; UTF-8
```

**Comment by OS4** [comment] 2024-01-18 13:44
I can confirm that it is working as expected. Product Version: Apache NetBeans IDE DEV (Build dev-73237de9420b5847640cae2bc5fff940d7d5b346). I removed the cache and working directory and loaded the projects afresh, and now it all works.

**Comment by junichi11** [comment] 2024-01-18 14:18
OK. Closing.

**Closed by junichi11** 2024-01-18 14:18 UTC
Labels: kind:bug, PHP, can not reproduce
