### ISSUE TITLE
NB21 Java, Goto Declaration no longer working

### ISSUE THREAD

**Issue by hbitteur** [apache/netbeans#7327] opened 2024-04-23 17:55 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

CTRL + left click on a Java element (field, function, ...) used to move to the statement where this element is declared.
CTRL + B used to provide the same behavior on the current item.
This no longer works with Netbeans 21

### Language / Project Type / NetBeans Component

Java Gradle project

### How to reproduce

Select any item in a Java source code

### Did this work correctly in an earlier version?

Apache NetBeans 20

### Operating System

Windows 10 x86_64

### JDK

java version "21.0.2" 2024-01-16 LTS Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58) Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Always

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2024-04-24 02:42
Is the dependency you want to jump to accessible to netbeans? For example if it is another project, is that project open too?

What happens if you create a fresh hello world project and try to use the go-to action there? Anything in the log?

**Comment by hbitteur** [comment] 2024-04-27 07:38
Sorry for this late answer, I was away from my laptop.

I should have been more explicit in my post.
The problem is not the _failure_ of a feature (e.g. Netbeans not being able to access some dependency as you suggested) but the **_triggering_** of this feature.

As if the keymap had been modified (which I didn't). I just double-checked in `Tools | Options | Keymap`, and the "Go to Declaration" action is still mapped to `CTRL`+`B`.

In previous Netbeans versions (20 for example), we also had the ability to hold down the `CTRL` key while moving the mouse over some Java source code.
For example, just by hovering above say the word "`String`" in the Java statement "String fooBar;", a small popup window would appear to display something like:
``` Java
java.lang
public final class String extends [Object](https://github.com/apache/netbeans/issues/*1) implements [Serializable]
...
The String class represents character strings. All string literals in Java programs, such as "abc", are implemented as instances of this class.
...
```
Then a left click on this "String" word would open the String class source code.

In Netbeans 21, none of these triggers do anything.

**Comment by mbien** [comment] 2024-04-27 09:19
> In previous Netbeans versions (20 for example), we also had the ability to hold down the CTRL key while moving the mouse over some Java source code.

@hbitteur right. this didn't change. You mean that if you hold down `ctrl` and hover over types or fields, you don't see the hand symbol or the text becoming a link but `right click -> navigate -> go to decl` still works?

**Comment by hbitteur** [comment] 2024-04-27 14:15
No, I cannot navigate at all!

Here is the result of a right-click in NetBeans 20 (while on a String element): 

![image](https://github.com/apache/netbeans/assets/22053634/eeb0ac8e-2cc7-4e4c-8c72-baea3f53fd81)

And here is the result of a right-click in NetBeans 21 (still on a String element):

![image](https://github.com/apache/netbeans/assets/22053634/e47d56b8-83e5-4f2f-b32a-d67053a59a72)

As you can see, the popups are significantly different. A bunch of menu items are missing, all related to Java by the way.
In particular, there is nothing like a "Navigate" item in the NB21 popup. So I cannot trigger any navigation.

**Comment by geertjanw** [comment] 2024-04-27 14:28
What do you conclude from there being no Java functionality at all in the 2nd image?

**Comment by hbitteur** [comment] 2024-04-28 13:14
> What do you conclude from there being no Java functionality at all in the 2nd image?

I conclude that NetBeans has stopped supporting Java! :-)

The problem is I have tried both NB20 and NB21 on the same Java/Gradle projects.
The former works, the latter does not.
Do I need to perform any special action/configuration/whatever to wake up NB21 on a Java project?

I must be missing something enormous. But what precisely?
What else could I say on this Sunday rainy afternoon?

**Comment by matthiasblaesing** [comment] 2024-04-28 13:55
@hbitteur  I also noticed NetBeans "Goto" functions not working sometimes. But when that was the case it were unprimed projects, so classpath and such were not yet updated. After building them, normal operation picked up again.

If building does not help, please share a minimal reproducer, so that others can investigate.

**Comment by mbien** [comment] 2024-04-28 14:09
can you attach messages.log? Since you have menu entries missing some modules might have not loaded properly (https://github.com/apache/netbeans/issues/7091).

**Comment by hbitteur** [comment] 2024-04-29 18:46
Here is the content of `messages.log` file:
[messages.log](https://github.com/apache/netbeans/files/15153528/messages.log)

**Comment by mbien** [comment] 2024-04-30 10:49
@hbitteur thanks! Several java modules didn't load. e.g:
```
	org.netbeans.libs.nbjavacapi [21.1 21-b15c9b7692b2764be5a997d056e2283b72ae9131]
...
	org.netbeans.modules.java.source.queries [1.41 21-b15c9b7692b2764be5a997d056e2283b72ae9131]
	org.netbeans.modules.java.source.queriesimpl [1.40 21-b15c9b7692b2764be5a997d056e2283b72ae9131]
...
```
so it does appear to have the symptoms of https://github.com/apache/netbeans/issues/7091 which would make this a duplicate

Good news is that it is fixed in 22rc2, feel free to give it a try if you want, download links are in https://github.com/apache/netbeans/discussions/7281

going to link https://github.com/apache/netbeans/pull/7334 with this issue too

**Closed** 2024-05-06 18:50 UTC
Labels: kind:bug, duplicate, Java
