### ISSUE TITLE
Can't rename classes in newly created maven project

### ISSUE THREAD

**Issue by mbien** [apache/netbeans#3526] opened 2022-01-28 13:24 UTC
### Apache NetBeans version

Latest release candidate

### What happened

see title, log:
```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.refactoring.spi.impl.ParametersPanel$12
java.lang.IllegalArgumentException: file:/tmp/mavenproject1/src/test/java is not a valid classpath entry; it must end with a slash.
	at org.netbeans.modules.java.classpath.SimplePathResourceImplementation.verify(SimplePathResourceImplementation.java:90)
	at org.netbeans.modules.java.classpath.SimplePathResourceImplementation.verify(SimplePathResourceImplementation.java:43)
	at org.netbeans.modules.java.classpath.SimplePathResourceImplementation.<init>(SimplePathResourceImplementation.java:108)
	at org.netbeans.spi.java.classpath.support.ClassPathSupport.createResource(ClassPathSupport.java:54)
	at org.netbeans.spi.java.classpath.support.ClassPathSupport.createClassPath(ClassPathSupport.java:124)
	at org.netbeans.modules.testng.DefaultPlugin.getOppositeLocation(DefaultPlugin.java:242)
	at org.netbeans.modules.testng.DefaultPlugin.getTestLocation(DefaultPlugin.java:183)
	at org.netbeans.modules.testng.GoToOppositeAction.appliesTo(GoToOppositeAction.java:335)
	at org.netbeans.modules.refactoring.java.ui.RenamePanel$2.run(RenamePanel.java:158)
	at org.netbeans.modules.refactoring.java.ui.RenamePanel$2.run(RenamePanel.java:113)
	at org.netbeans.api.java.source.JavaSource$MultiTask.run(JavaSource.java:504)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
	at org.netbeans.api.java.source.JavaSource.runUserActionTaskImpl(JavaSource.java:454)
	at org.netbeans.api.java.source.JavaSource.runUserActionTask(JavaSource.java:425)
	at org.netbeans.modules.refactoring.java.ui.RenamePanel.initialize(RenamePanel.java:184)
	at org.netbeans.modules.refactoring.spi.impl.ParametersPanel$12.run(ParametersPanel.java:641)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

### How to reproduce

1) create new maven project ("Java Applicaiton")
2) put cursor over class name, press CTRL+R

rename dialog with "please wait..." appears, exception in log.

### Did this work correctly in an earlier version?

- [X] This used to work!

### Operating System

linux

### JDK

17.0.2

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

`java.lang.IllegalArgumentException: file:/tmp/mavenproject1/src/test/java is not a valid classpath entry; it must end with a slash.`

Indicates that it is adding the test folder to the cp, but there is no test folder in the new project template.

creating empty `./src/test/java` fixes it.

reproducible in 13rc2

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by mbien** [comment] 2022-01-28 13:33
pinging @sdedic since it might be caused by the updates to maven templates (I haven't checked).

**Comment by neilcsmith-net** [comment] 2022-01-28 15:10
Seems to be lack of a `src/test/java` folder, or expectation it's there. Just adding that fixes it. Same bug is reproducible in 12.6 too.  Would be great to get fixed in 13 though.

**Comment by mbien** [comment] 2022-01-28 15:17
good to know that it is already reproducible in 12.6. This means its not the fault of the new maven templates.

We should probably try to fix it in a way so that it doesn't require the empty folders. I am just wondering if other functions are also affected by not having the folder. (maybe add the folders anyway?)

**Comment by ebresie** [comment] 2022-01-28 19:32
Is this a Java 17-sim?  I see reference to small [change in 17 release notes]([url](https://www.oracle.com/java/technologies/javase/17-relnote-issues.html#JDK-8262277)).

**Comment by neilcsmith-net** [comment] 2022-01-31 10:09
Closing as issue fixed for 13-rc3.

@mbien added folders is a useful conversation for elsewhere.  May benefit from test and resources folders being in initial template.  Both seem to cause users confusion at times.

**Closed by neilcsmith-net** 2022-01-31 10:09 UTC
Labels: kind:bug, Java, Maven, priority:high
