### ISSUE TITLE
Faces syntax validation fails for EE-10

### ISSUE THREAD

**Issue by helper14** [apache/netbeans#7137] opened 2024-03-06 11:35 UTC
### Apache NetBeans version

Apache NetBeans 21

### What happened

Faces syntax validation fails for EE-10 web application projects

### Language / Project Type / NetBeans Component

Web Application, JSF, syntax validation

### How to reproduce

Create a new template web application project. Set Server to version 7 and EE to version 10. Create a new template JSF page.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Win10

### JDK

openJDK21

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

![netbeans21-screenshot](https://github.com/apache/netbeans/assets/83238864/589b6d81-420b-439d-a0fa-c9c5f7890c32)

### Are you willing to submit a pull request?

No

**Comment by rgrin08** [comment] 2024-03-26 09:24
And the completion does not work.
The same with a template client.

**Comment by matthiasblaesing** [comment] 2024-04-01 10:28
My tests showed that the problem is reproducible if GF 5.X is registered as a server. The GF integration registers an XML catalog, that resolves some of the XML schemas required for JavaEE/JakartaEE support. For JakartaEE 10 one of the schemas is `jakartaee_web_services_client_2_0.xsd`. The GF catalog "resolves" it, but at least version 5 does not actually carry the schema, so the resolved input is bogus and the XML parser thus fails to parse the JSF component descriptors.

#7218 reworks the catalog logic for GF and Payara (direct GF fork) integrations and now only resolves schemas after ensuring the local file is actually present.

Please @helper14 @rgrin08 please test the nightly build available from the checks page of the references PR (https://github.com/apache/netbeans/pull/7218/checks, "Artifacts" dropdown) or directly: https://github.com/apache/netbeans/suites/22293481261/artifacts/1374035463.

The nightly build will be available for the next five days.

**Closed** 2024-04-09 19:00 UTC
Labels: kind:bug, Java EE/Jakarta EE, enterprise
