### ISSUE TITLE
Failed to create maven enterprise application

### ISSUE THREAD

**Issue by dcourrier** [apache/netbeans#3723] opened 2022-03-07 18:21 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

Select create new project
choose Java with Maven
choose enterprise application
get:
```
cd C:\NBProjects\AA; JAVA_HOME=C:\\jdk1.8.0_291 M2_HOME=C:\\apache-maven-3.8.1 cmd /c "\"C:\\apache-maven-3.8.1\\bin\\mvn.cmd\" -DarchetypeGroupId=io.github.juneau001 -DarchetypeArtifactId=webapp-jakartaee9 -DarchetypeVersion=1.1 -DarchetypeRepository=https://repo.maven.apache.org/maven2 -DgroupId=com.courrier -DartifactId=AA-ejb -Dversion=1.0 -Dbasedir=C:\\NBProjects\\AA -Darchetype.interactive=false -DarchetypeCatalog=local -Dmaven.ext.class.path=C:\\NetBeans-13\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar --batch-mode org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate"
Scanning for projects...

--------------------------< com.courrier:AA >---------------------------
Building AA-1.0 1.0
--------------------------------[ war ]---------------------------------

>>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ AA >>>

--- maven-dependency-plugin:2.6:copy (default) @ AA ---

<<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ AA <<<


--- maven-archetype-plugin:3.1.2:generate (default-cli) @ AA ---
Generating project in Batch mode
Archetype not found in any catalog. Falling back to central repository.
Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
----------------------------------------------------------------------------
Using following parameters for creating project from Archetype: webapp-jakartaee9:1.1
----------------------------------------------------------------------------
Parameter: groupId, Value: com.courrier
Parameter: artifactId, Value: AA-ejb
Parameter: version, Value: 1.0
Parameter: package, Value: com.courrier.AA-ejb
Parameter: packageInPathFormat, Value: com/courrier/AA-ejb
Parameter: package, Value: com.courrier.AA-ejb
Parameter: version, Value: 1.0
Parameter: groupId, Value: com.courrier
Parameter: artifactId, Value: AA-ejb
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  3.858 s
Finished at: 2022-03-07T11:59:54-06:00
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project AA: Unable to add module to the current project as it is not of packaging type 'pom' -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### How to reproduce

Select create new project
choose Java with Maven
choose enterprise application
supply project name (I supplied AA)
click next
click finish

### Did this work correctly in an earlier version?

No

### Operating System

Windows

### JDK

JDK 16.0.1

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Always fails, Does so on NB 8.2 & NB 12.6

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by OndroMih** [comment] 2022-11-06 10:22
This is because the archetype used by Netbeans generates a WAR maven module in the root project and not a parent POM module. This is a duplicate of https://github.com/apache/netbeans/issues/3552, which contains more details. This issue should be closed in favor of #3552.

**Closed** 2023-03-31 08:38 UTC
Labels: kind:bug, Maven, needs:triage, enterprise
