### ISSUE TITLE
Make NetBeans Terminal Work On Windows

### ISSUE THREAD

**Issue by Oualitsen** [apache/netbeans#4245] opened 2022-06-18 23:46 UTC
### Description

The current state of NetBeans terminal is fine with Linux and MacOS. but it requires cygwin to work on windows.
Inetellij IDEA and VSCode Work just fine with windows (cmd and powershell).
I think the terminal is very useful to have working properly for any IDE for a developer and it needs to be accessed very fast. Adding a button on the bottom main frame of the IDE will help new commers to get started very fast.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by antoniodiego** [comment] 2022-07-23 14:06
👏👏

**Comment by anthonyvdotbe** [comment] 2022-08-09 11:04
This should probably be closed as a duplicate of #3959

**Closed** 2022-11-14 22:02 UTC
Labels: duplicate, kind:feature, os:windows
