### ISSUE TITLE
Netbeans v14 Exception on startup: ~/.config

### ISSUE THREAD

**Issue by aplatypus** [apache/netbeans#4275] opened 2022-06-23 07:11 UTC
### Apache NetBeans version

Apache NetBeans 14

### What happened

This exception was displayed first time I ran Netbeans v14:

```
A java.nio.file.FileAlreadyExistsException exception has occurred.
Please report this at https://netbeans.apache.org/nb/report-issue,
including a copy of your messages.log file as an attachment.
The messages.log file is located in your /home/william/.config/netbeans/v14.00/4ams/v17.00/user-02/var/log folder.
```
```
java.nio.file.FileAlreadyExistsException: /home/william/.config
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:753)
[catch] at org.eclipse.jgit.util.SystemReader$Default.getXDGConfigHome(SystemReader.java:120)
	at org.eclipse.jgit.util.SystemReader$Default.openJGitConfig(SystemReader.java:131)
	at org.eclipse.jgit.util.SystemReader.getJGitConfig(SystemReader.java:348)
	at org.eclipse.jgit.util.SystemReader.getSystemConfig(SystemReader.java:373)
	at org.eclipse.jgit.util.SystemReader.getUserConfig(SystemReader.java:321)
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:162)
	at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:55)
	at org.netbeans.libs.git.jgit.Utils.getRepositoryForWorkingDir(Utils.java:79)
	at org.netbeans.libs.git.jgit.JGitRepository.getRepository(JGitRepository.java:53)
	at org.netbeans.libs.git.jgit.JGitRepository.increaseClientUsage(JGitRepository.java:41)
	at org.netbeans.libs.git.GitClient.<init>(GitClient.java:311)
	at org.netbeans.libs.git.GitRepository.createClient(GitRepository.java:189)
	at org.netbeans.libs.git.GitRepository.createClient(GitRepository.java:141)
	at org.netbeans.modules.git.client.GitClient.<init>(GitClient.java:195)
	at org.netbeans.modules.git.Git.getClient(Git.java:194)
	at org.netbeans.modules.git.Git.getClient(Git.java:190)
	at org.netbeans.modules.git.Git.getClient(Git.java:186)
	at org.netbeans.modules.git.ui.repository.RepositoryInfo.refresh(RepositoryInfo.java:184)
	at org.netbeans.modules.git.ui.repository.RepositoryInfo.getInstance(RepositoryInfo.java:159)
	at org.netbeans.modules.git.FilesystemInterceptor$GitFolderEventsHandler.scanGitFolderTimestamps(FilesystemInterceptor.java:933)
	at org.netbeans.modules.git.FilesystemInterceptor$GitFolderEventsHandler.initializeFiles(FilesystemInterceptor.java:1036)
	at org.netbeans.modules.git.FilesystemInterceptor$GitFolderEventsHandler.access$2500(FilesystemInterceptor.java:842)
	at org.netbeans.modules.git.FilesystemInterceptor$GitFolderEventsHandler$1.run(FilesystemInterceptor.java:854)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

```

### How to reproduce

* I installed netbeans v14 from zip file download

### Did this work correctly in an earlier version?

Apache NetBeans 12.6

### Operating System

Ubuntu 22.04 LTS

### JDK

openjdk version "17.0.1" 2021-10-19 LTS

### Apache NetBeans packaging

Apache NetBeans binary zip

### Anything else

Attaching messages.log
* [messages.log](https://github.com/apache/netbeans/files/8964875/messages.log)

The indicated directory does exist -- This exception doesn't make any sense.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-06-24 10:20
This appears to be a duplicate of #4197 that you already reported.

**Closed by neilcsmith-net** 2022-06-24 10:20 UTC
Labels: kind:bug, needs:triage
