### ISSUE TITLE
can not open a project or any file chooser (Comparison method violates its general contract!)

### ISSUE THREAD

**Issue by baosetsuna123** [apache/netbeans#6295] opened 2023-08-03 18:19 UTC
### Apache NetBeans version

Apache NetBeans 18

### What happened

<img width="352" alt="image" src="https://github.com/apache/netbeans/assets/135978806/a4498cde-d4b9-46d4-bdec-8276dbdcbde3">
<img width="468" alt="image" src="https://github.com/apache/netbeans/assets/135978806/4c4dcbad-c6d5-43fd-935a-a30b161201de">

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

18

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

Yes

**Comment by baosetsuna123** [comment] 2023-08-03 18:21
This bug occurs when i click on the Menu File/Open Projects

**Comment by neilcsmith-net** [comment] 2023-08-03 18:29
This is a duplicate of #5687 Not sure what we can do, it's a JDK bug. However there's a workaround you can try in that issue.

It's also related to #6289

**Comment by mbien** [comment] 2023-08-03 23:23
looks like it is tracked under https://bugs.openjdk.org/browse/JDK-8305072

**Comment by neilcsmith-net** [comment] 2023-08-04 07:38
Thanks @mbien Had read that, and thought I'd linked it previously, but can't find on any of the reports.

That bug is marked as resolved and incomplete. Judging from the number of reports we're getting, we should perhaps help get it reopened?!

**Comment by mbien** [comment] 2023-08-04 15:18
> That bug is marked as resolved and incomplete. Judging from the number of reports we're getting, we should perhaps help get it reopened?!

the last comment on the bug asked the user how to create two folders with the same name on windows so that they can reproduce it. It might not have gotten a reply - don't know. But since I don't use windows either, I wouldn't be of help there.

**Comment by mbien** [comment] 2023-08-19 06:35
for workarounds see #6361

**Comment by mbien** [comment] 2024-04-29 12:50
fixed in JDK 23 -> https://github.com/openjdk/jdk/pull/18126

**Closed by mbien** 2024-04-29 12:50 UTC
Labels: kind:bug, duplicate, os:windows, JDK bug
