### ISSUE TITLE
No libraray found for namespace jakarta.faces.html

### ISSUE THREAD

**Issue by richard-grin** [apache/netbeans#5470] opened 2023-02-11 10:49 UTC
### Apache NetBeans version

Apache NetBeans 17 release candidate

### What happened

The new namespaces of JSF 6.0 (in Jakarta EE 10) are not known by NetBeans in the JSF pages.

### How to reproduce

Create a new Maven project for a Web application and add a new JSF page that uses one of the namespaces. For example:
```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      **xmlns:h="jakarta.faces.html"
      xmlns:f="jakarta.faces.core"**>
```
However, it is possible to do a Clean and build of the project and the project can be launched and it works.

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11 Family 64-bit, version 21H2

### JDK

17

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by richard-grin** [comment] 2023-02-11 10:50
Precision: NetBeans release candidate 1

**Comment by richard-grin** [comment] 2023-02-11 10:58
Weird: the error message appears only if the 2 lines for the namespaces are followed by this line (or perhaps another namespace):
`xmlns:p="http://primefaces.org/ui"`

**Comment by NicolaIsotta** [comment] 2023-02-11 11:46
Probably related to #4976

**Comment by mbien** [comment] 2023-02-15 08:55
I assume this is no regression, it already didn't work in NB 16, right?

**Comment by richard-grin** [comment] 2023-02-15 10:47
Sure. NB 16 did not support Jakarta EE 10.

**Comment by morvael** [comment] 2023-02-24 08:49
The issue remains in released NB 17 (not RC).

**Comment by tmsanchez** [comment] 2023-03-08 13:53
I'll be working on this issue and will putting my findings here

**Comment by NicolaIsotta** [comment] 2023-03-08 14:22
> I'll be working on this issue and will putting my findings here

Have look at my comment https://github.com/apache/netbeans/issues/4976#issuecomment-1324948303 , I think [ConfigManager class](https://github.com/apache/netbeans/blob/master/enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/mojarra/ConfigManager.java) may be the cause

**Comment by tmsanchez** [comment] 2023-03-08 14:36
got it I'll take a look.

I was also debugging and red hints dissapear if following lines are added to NS_MAPPING constant in NameSpacesUtils class

        NS_MAPPING.put("jakarta.faces.html", "http://java.sun.com/jsf/html");                                          //NOI18N
        NS_MAPPING.put("jakarta.faces.core", "http://java.sun.com/jsf/core");       //NOI18N
        NS_MAPPING.put("jakarta.faces.facelets", "http://java.sun.com/jsf/core");       //NOI18N

https://github.com/apache/netbeans/blob/master/enterprise/web.jsfapi/src/org/netbeans/modules/web/jsfapi/api/NamespaceUtils.java

above class i n JSP API nbmodule

![imagen](https://user-images.githubusercontent.com/486370/223741306-22fa6521-ab4d-4225-8135-2c04cc257c13.png)

**Comment by kesha-han** [comment] 2023-04-05 00:30
Hi, I wonder when the bug could be fixed.  Before it is fixed, could you send me the module jar of web.jsfapi or .class of NamespaceUtil.java to let it just work without error tips? @tmsanchez  I got errors when building NB 17 source codes.

**Comment by tmsanchez** [comment] 2023-04-06 10:58
I'm still working on it, I hope to have a good progress this weekend.

**Comment by morvael** [comment] 2023-05-08 09:31
How is it going?

**Comment by morvael** [comment] 2023-05-18 07:25
> > I'll be working on this issue and will putting my findings here
> 
> Have look at my comment [#4976 (comment)](https://github.com/apache/netbeans/issues/4976#issuecomment-1324948303) , I think [ConfigManager class](https://github.com/apache/netbeans/blob/master/enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/mojarra/ConfigManager.java) may be the cause

It seems there is no support for new schemes in the referenced DbfFactory class :(

**Comment by morvael** [comment] 2023-05-18 10:20
The rest should be pretty straightforward (provided one finds every reference to old namespaces and versions in NB codebase), because the code already went through adding support for new namespaces (when going from sun to jcp). So this will be more of the same. But how to change external libraries of NB project - I have no idea. Newest version of DbfFactory from Mojarra looks like a completely different class.

**Comment by AndrewG10i** [comment] 2023-06-06 05:18
NB18 - the issue still present, will be really nice to have it fixed in nearest releases! 0:-) Thank you in advance!

**Comment by asbachb** [comment] 2023-06-19 17:38
Should be fixed with https://github.com/apache/netbeans/pull/6096

Inviting you to pull the PR and validate.

**Closed** 2023-07-16 13:13 UTC
Labels: kind:bug, Java EE/Jakarta EE, enterprise
