### ISSUE TITLE
nbm-maven-plugin does not work with Java 21

### ISSUE THREAD

**Issue by jdsmithsos** [apache/netbeans#7040] opened 2024-02-07 21:25 UTC
### Apache NetBeans version

Apache NetBeans 20

### What happened

I recently upgraded Netbeans to 20, and Java to 21.
When building the multi-module project, the first few modules build without error.
Then a module build fails with the following error:
```
[ERROR] Failed to execute goal org.apache.netbeans.utilities:nbm-maven-plugin:4.8:manifest (default-manifest) on project SaloonsAdminLogging: Execution default-manifest of goal org.apache.netbeans.utilities:nbm-maven-plugin:4.8:manifest failed: Unsupported class file major version 65 -> [Help 1]
```

The build output looks like this:

```
[INFO]
[INFO] --- nbm:4.8:manifest (default-manifest) @ SaloonsAdminLogging ---
[INFO] NBM Plugin generates manifest
[INFO] Adding on module's Class-Path:
[INFO]     org.slf4j:slf4j-api:jar:1.7.30
[INFO]     org.apache.logging.log4j:log4j-slf4j-impl:jar:2.13.3
[INFO]     org.apache.logging.log4j:log4j-api:jar:2.13.3
[INFO]     org.apache.logging.log4j:log4j-core:jar:2.13.3
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SaloonsAdmin-parent 1.11.0-SNAPSHOT:
[INFO]
[INFO] MyProject-parent ................................ SUCCESS [  1.491 s]
[INFO] MyProject-branding .............................. SUCCESS [  1.590 s]
[INFO] ControlsFXWrapper .................................. SUCCESS [  3.356 s]
[INFO] GoogleWrapper ...................................... SUCCESS [  1.000 s]
[INFO] ApacheCommonsWrapper ............................... SUCCESS [  0.599 s]
[INFO] MyProjectLogging ................................ FAILURE [  1.343 s]
[INFO] MyProjectDomain ...................................... SKIPPED
```

Where the ControlsFXWrapper, GoogleWrapper, and ApacheCommonsWrapper all use the nbm-maven-plugin.  But these modules don't have actual code, they just expose packages for the other modules to use.

So the issue is when nbm-maven-plugin encounters the first module that actually has code, the build of the module fails.

I downloaded NetBeans 20, but this build error doesn't require NetBeans 20.  It is occurring on the command line.

In the project pom.xml, I am using:

NetBeans version:  RELEASE180
nbm-maven-plugin version:  4.8, which I upgraded from 4.7 during this process.

I know that NetBeans 20 is supporting Java 21, but when will the nbm-maven-plugin???

Thanks for any help you can provide with this issue.

### Language / Project Type / NetBeans Component

Java Maven

### How to reproduce

Execute a Maven build using Java 21, which uses the nbm-maven-plugin.

Here is the Maven and Java info:

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\SmithOptimalSolutions\tools\maven\apache-maven-3.9.6
Java version: 21.0.2, vendor: Oracle Corporation, runtime: C:\SmithOptimalSolutions\tools\java\jdk-21.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### Did this work correctly in an earlier version?

No / Don't know

### Operating System

Windows 11

### JDK

openjdk version "21.0.2" 2024-01-16

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by jdsmithsos** [comment] 2024-02-14 21:02
Yes, I upgraded to 4.8, which doesn't work, then upgraded to 14.0, which also doesn't work.

**Comment by mbien** [comment] 2024-02-15 00:19
the `nbm-maven-plugin` 14.0 should support JDK 21 already. I can reproduce this issue with 4.8 - which is expected, but not while using 14.0 which is the latest version.

> In the project pom.xml, I am using:
> 
> NetBeans version: RELEASE180

NB 18 was not tested on JDK 21. You can check this via the old download page or readme: https://netbeans.apache.org/front/main/download/nb18/

make sure all your other maven plugins are updated too
```
mvn dependency:resolve-plugins
```
will print a list of all used plugin versions. Feel free to post the output of it.

Running maven with `-e` will show full strack traces on exceptions.

**Comment by mbien** [comment] 2024-02-15 14:59
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
    at org.objectweb.asm.ClassReader.<init> (ClassReader.java:199)
    at org.objectweb.asm.ClassReader.<init> (ClassReader.java:180)
    at org.objectweb.asm.ClassReader.<init> (ClassReader.java:166)
    at org.apache.maven.shared.dependency.analyzer.asm.DependencyClassFileVisitor.visitClass (DependencyClassFileVisitor.java:60)
```
This would be ASM complaining.

i looked at the dependency list of the `SaloonsAdminLogging` project and it looks good. It has `org.ow2.asm:asm:jar:9.5` which supports JDK 21 and `org.apache.maven.shared:maven-dependency-analyzer:jar:1.13.2` - so nothing got downgraded.

The only older asm lib is in the surefire plugin, 7.2 is definitively not JDK 21 compatible - but this shouldn't influence the nbm plugin.

So I can't explain what is going on there, but this is still worth a try:
try to declare the asm dependency explicitly for the `nbm-maven-plugin`:
```xml
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <version>14.0</version>
                <extensions>true</extensions>
                <dependencies>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                        <version>9.5</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by jdsmithsos** [comment] 2024-02-15 15:39
Aha!  
Actually, I didn't need to add the asm dependency.
When I went into the pom to add asm, I saw that there was already a dependency there, which was added way back when for whatever reason to get the nbm-maven-plugin to work.
I commented out the maven-dependency-analyzer, and the build no longer fails with the

Unsupported class file major version 65

error.


                <plugin>
                    <groupId>org.apache.netbeans.utilities</groupId>
                    <artifactId>nbm-maven-plugin</artifactId>
                    <version>14.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <brandingToken>${brandingToken}</brandingToken>
                        <cluster>${brandingToken}</cluster>
                        
                        <verifyRuntime>warn</verifyRuntime>
                    </configuration>
					
                </plugin>

**Comment by mbien** [comment] 2024-02-16 01:37
ok yeah that would be the reason why it downgraded asm. `nbm-maven-plugin` 14.0 depends on a newer version (which depends on asm 9.5).

overwriting dependencies with direct dependency declaration will downgrade things if you are not careful - even though I expected something like that, finding the cause is not always easy.

you can check it here:
https://repo1.maven.org/maven2/org/apache/netbeans/utilities/nbm-maven-plugin/14.0/nbm-maven-plugin-14.0.pom where everything is correct

**Comment by mbien** [comment] 2024-02-16 09:14
I did also learn that
```
mvn dependency:resolve-plugins
```
is not a good way to debug plugin dependency trees since it will list its original dependencies, better method would be:
```
mvn -X nbm:nbm
```
this would show the asm downgrade right away

Good luck with the rest of the JDK 21 upgrade, don't forget the surefire plugins etc NetBeans will also mark possible dependency updates directly in the pom which might help.

closing the issue.

**Closed by mbien** 2024-02-16 09:14 UTC
Labels: kind:bug, Maven, Platform
