### ISSUE TITLE
md opened as binary

### ISSUE THREAD

**Issue by sysmat** [apache/netbeans#3797] opened 2022-03-17 07:37 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

***.md** file extension is recognized an icon is ok, but NB only have option **open as binary**

### Did this work correctly in an earlier version?

Apache NetBeans 12.5

### Operating System

windows

### JDK

17

### Apache NetBeans packaging

Apache NetBeans platform

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by vieiro** [comment] 2022-03-17 07:43
Duplicate of #3714 .
This is not an issue, it's a feature request.

**Comment by neilcsmith-net** [comment] 2022-03-17 15:36
@sysmat can you share a copy of the file?  Cannot reproduce.

**Comment by neilcsmith-net** [comment] 2022-03-17 15:38
@vieiro this doesn't sound like a duplicate of that feature request.  It sounds like a possible bug, but not one I can reproduce on my setup.

**Comment by mbien** [comment] 2022-03-17 22:28
do you have/had the plugin BinEd installed?

**Comment by sysmat** [comment] 2022-03-18 05:59
- utf-8 encoding
- CR LF(windows)

[README.md](https://github.com/apache/netbeans/files/8301959/README.md)


![NB13_MD](https://user-images.githubusercontent.com/69830/158945831-4456055d-1dfb-4cf3-b382-e5dbf9d67738.png)

**Comment by neilcsmith-net** [comment] 2022-03-18 10:30
Verified with BinEd plugin as @mbien stated. Not a bug in NetBeans. Please uninstall BinEd and report an issue to the plugin author.

**Closed by neilcsmith-net** 2022-03-18 10:30 UTC
Labels: kind:bug, pending-response

**Comment by sysmat** [comment] 2022-03-18 10:47
I don't have BinEd and can't find it in netplugins search

**Comment by neilcsmith-net** [comment] 2022-03-18 10:59
Please try with a clean userdir and without importing settings then.  It might be that it's left something behind.  That action and display comes from that plugin.

**Comment by Chris2011** [comment] 2022-03-18 11:08
> I don't have BinEd and can't find it in netplugins search

I'm pretty sure that you have it. The plugin had an other name before, just search for "bin" or "hex" and make sure you checked the checkbox for "Show details"

**Comment by sysmat** [comment] 2022-03-18 11:27
![NB13_plugins](https://user-images.githubusercontent.com/69830/158995146-e6f86255-0667-4ef3-af0d-c81a78f60c4a.png)

**Comment by Chris2011** [comment] 2022-03-18 11:31
As I said, you need to check the checkbox "Show details" over the list and use the search field on the right to search for hex or bin if the list is to long. What you see in the list is just the categories.

**Comment by sysmat** [comment] 2022-03-18 11:43
- yes, my mistake, I have it and deactivated + restart
- icon of file is still visbale, but file can't be opened, not even as plain text
- when on *.md file and right-click no toggle options , so it can not be edited in NB 13

**Comment by Chris2011** [comment] 2022-03-18 11:48
I can reproduce it. There are no actions on the file. Just mine from my plugins, also no error/exception. What happens, when you try to have a clean user dir for NB 13? Just rename the user dir to 13.0-bak or so and try it again.

**Comment by mbien** [comment] 2022-03-18 15:12
looks like my suspicion was correct, you had BinEd installed.

BinEd registers its open action in a [fairly creative way](https://github.com/exbin/bined-netbeans-plugin/blob/master/src/main/java/org/exbin/bined/netbeans/Installer.java#L57-L66) to all available file loaders. It persists even after uninstalling.

you have to reset your config or remove/fix manually the files in "~/.netbeans/13/config/Loaders/text/" x-markdown-nb specifically for md files, but there might be others.

i really like BinEd, but we should consider removing it from the plugin portal until this is fixed. This seems to cause too much trouble, I saw someone else with the same issue on slack recently + it happened to me too.

**Comment by sysmat** [comment] 2022-03-19 08:34
- after removing `Roaming\NetBeans\13\config\Loaders\text\x-markdown-nb` now it works; @mbien thx

**Comment by hajdam** [comment] 2022-10-11 08:01
Any recommendation how to fix the issue for bined plugin - better approach to register action for all file types? It seems that netbeans uses "-nb" postfix for dynamically registered file types or is there better access to internal repository?

**Comment by Chris2011** [comment] 2022-10-11 10:18
In general we don't have this prefix in other mimetypes and also we shouldn't. I dunno why -nb was added but in general we don't have it.

**Comment by Chris2011** [comment] 2022-11-04 21:31
Hey @sysmat please check with latest NetBeans 15 (I think NetBeans 16 is around the corner) and with newest Bined-netbeans-plugin 0.2.4 (https://bined.exbin.org/netbeans-plugin/)

**Comment by sysmat** [comment] 2022-11-05 09:12
- I'm using NB 15, but now without binary view plugin, and MD editor works fine
- I'll try bined
