### ISSUE TITLE
Fails to run on MacOS

### ISSUE THREAD

**Issue by johnhewett** [apache/netbeans#4009] opened 2022-04-20 09:14 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

My mac crashed the first time I ran netbeans 13 (previous versions had run but not for some time). I don't believe netbeans caused the crash. Now when I try to run netbeans it bounces for about a second and then disappears. I could not find anything in the system logs that seems relevant. A small file is created in the app package with name "exiting", contents of file 
"Warning: No caches found -
"
but there do appear to be caches on my system created by netbeans 13

### How to reproduce

Difficult without causing your machine to crash

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

catalina 10.15.7

### JDK

1.8.0_321

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

Occurs consistently. I could probably trace the problem if the message in "exiting" detailed which cache it was looking for and where

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-04-20 09:58
Running on JDK 8 is not officially supported.  I wonder if this is related to the signing of the installer package.  You could try running the binary zip distribution against that JDK instead, or try the (unofficial) community macOS installer with bundled JDK runtime - https://netbeans.apache.org/download/nb13/nb13.html#_community_installers

**Comment by neilcsmith-net** [comment] 2022-04-20 10:03
Incidentally, the cache folder should be as here - https://github.com/apache/netbeans/blob/master/nb/ide.launcher/unix/netbeans#L45

I would possibly try deleting both the user and cache dirs.

**Comment by johnhewett** [comment] 2022-04-20 13:56
I tried installing from the community installer and running that, deleting the cache at ~/Library/Caches/NetBeans/13 and neither made any difference. What did you mean by the user cache dir?

**Comment by geertjanw** [comment] 2022-04-20 13:58
Can you use JDK 11 or 17 instead, please?

**Comment by johnhewett** [comment] 2022-04-20 14:37
Deleting ~/Application Support/NetBeans/13/.... seems to have done the trick. In my case there wouldn't have been any files worth keeping in that location. Other users might lose information which they would rather keep.

**Comment by neilcsmith-net** [comment] 2022-04-20 15:05
> What did you mean by the user cache dir?

> Deleting ~/Application Support/NetBeans/13/.... seems to have done the trick.

Yes, that!  User dir, not user cache dir.  Looks like it got corrupted somehow.  Will close this.  Open another ticket if the corruption occurs again and you have steps that might reproduce.  Or a discussion if you're not sure how to reproduce.

**Closed by neilcsmith-net** 2022-04-20 15:05 UTC
Labels: kind:bug, needs:triage
