### ISSUE TITLE
Spring boot projects freezing in Netbeans 12.5 & 13

### ISSUE THREAD

**Issue by kle-pra** [apache/netbeans#3913] opened 2022-04-01 07:45 UTC
### Apache NetBeans version

Apache NetBeans `13` & `12.5`

### What happened

When editing Spring Boot project in Netbeans (12.5, 13 tested), Netbeans just freezes/crashes, you have to kill the process.  

This started recently, I don't recall this problem in the past version (< 12.5?)

Problems only seems to be with Spring Boot projects, with Java EE (Payara application server) projects this problem doesn't occur.

I am using Ubuntu version, but colleagues on Windows are experiencing the same problem. 

### How to reproduce

Open some Spring Boot project (I tested with version 2.6.4+ ), started editing Java files, it freezes after a few minutes.

### Did this work correctly in an earlier version?

Apache NetBeans 12.0 or earlier I don't remember ever having this problem. 

### Operating System

Ubuntu 20.04, but same problems on Windows

### JDK

JDK 8, JDK 11

### Apache NetBeans packaging

Apache NetBeans binary zip

### Code of Conduct

Yes

**Comment by sysmat** [comment] 2022-04-01 09:00
Same here:
- NetBeans 13
- OS: Win 10
- jdk: 17

**Comment by matthiasblaesing** [comment] 2022-04-01 17:24
Please check the message log whether there are relevant entries. Please provide steps to reproduce.

**Comment by kle-pra** [comment] 2022-04-04 07:27
Here is a simple Spring Boot project provided.

[netbeans-bug-springboot.zip](https://github.com/apache/netbeans/files/8407553/netbeans-bug-springboot.zip)

Steps to reproduce:

1. Open in Netbeans 13 & Build project
2. Start editing file  `NetbeansBugDemoApplciation` (I was just copying/pasting/deleting log.info over and over to simulate working with a file) and after (a few minutes?) it freezes.

There is nothing relevant in the messages log:
```
nb/var/log 
❯ tail -f messages.log 
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.openide.awt.Toolbar]: Too long AWTTask: 1,498 ms for org.openide.awt.MenuBar$MenuBarFolder@75c01b31(FolderList{MultiFileObject@48dcc792[Menu]})
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
INFO [org.netbeans.ui.indexing]: Indexing started, time from last indexing 0 ms.
INFO [org.netbeans.ui.indexing]: Indexing finished, indexing took 4 ms.
INFO [org.netbeans.core.netigso.Netigso]: bundle org.eclipse.osgi@3.9.1.v20140110-1610 256
INFO [org.netbeans.core.netigso.Netigso]: bundle org.eclipse.osgi@3.9.1.v20140110-1610 stopped
INFO [null]: Last record repeated again.

```

**Comment by kle-pra** [comment] 2022-04-11 18:25
Maven project, sample project to reproduce error is included in my previous post.

**Comment by syco** [comment] 2022-04-15 18:57
Hi,
Same here with a spring boot maven project on
```txt
Product Version: Apache NetBeans IDE 13
Java: 17.0.2; OpenJDK 64-Bit Server VM 17.0.2+8-Debian-1deb11u1
Runtime: OpenJDK Runtime Environment 17.0.2+8-Debian-1deb11u1
System: Linux version 5.10.0-13-amd64 running on amd64; UTF-8; en_GB (nb)
```
That seems to be the common factor.
Thanks

**Comment by syco** [comment] 2022-06-23 15:25
Hi, just want to say that we can add netbeans 14 to the list.
I've deleted all my configs, downloaded netbeans 14, but it still happens.

Thanks

**Comment by kle-pra** [comment] 2022-06-24 10:26
As suggested above, I made 2 thread dumps with jstack, one when netbeans is running and one after it crashed. v12.5 is used here:

[netbeans-ok.txt](https://github.com/apache/netbeans/files/8975404/netbeans-ok.txt)
[netbeans-notok.txt](https://github.com/apache/netbeans/files/8975403/netbeans-notok.txt)

Hope this helps with solving the issue.

**Comment by neilcsmith-net** [comment] 2022-06-24 10:44
@kle-pra thanks, but please provide with `v14` if you can. It looks like deadlock with the Micronaut hyperlink handler may still exist somewhere, as that should have been fixed in `v12.5`.  Workaround may be to disable the Micronaut module.

**Comment by syco** [comment] 2022-06-24 12:54
I did it twice, just to compare if the error or the lock is the same.

[netbeans0-notok.txt](https://github.com/apache/netbeans/files/8976249/netbeans0-notok.txt)
[netbeans0-ok.txt](https://github.com/apache/netbeans/files/8976250/netbeans0-ok.txt)
[netbeans1-notok.txt](https://github.com/apache/netbeans/files/8976251/netbeans1-notok.txt)
[netbeans1-ok.txt](https://github.com/apache/netbeans/files/8976252/netbeans1-ok.txt)

Thanks for looking into this, if you need other logs, just let me know how/where to get them.

**Comment by matthiasblaesing** [comment] 2022-07-05 18:08
This is reproduce, although it took time on my notebook. I activated more `On Save` actions (in the Options `Editor` -> `On Save`). It shows as a classic EDT block, i.e. the main window does not repaint anymore.

From that stacktraces @syco provided, I think we see a deadlock, because the EDT holds either a read or write lock on the document and tries to invoke the ParserManager, while the Thread named `ModuleActions` is the already executing a task in the ParserManager and then tries to write lock the document.

When I managed to reproduce this, in the output I see the most probably right hint:

> WARNING [org.netbeans.modules.parsing.impl.TaskProcessor]: ParserManager.parse called in AWT event thread by: org.netbeans.modules.micronaut.hyperlink.MicronautJavaHyperlinkProvider.getPropertyName(MicronautJavaHyperlinkProvider.java:151)

@dbalek could you please have a look at this? Is there a way to not jump into the `ParserManager` when the hyperlink provider is used? Maybe gathering the information can be moved of the EDT and then used from the EDT.

**Comment by matthiasblaesing** [comment] 2022-07-05 18:09
As this is a hard lock, I added this to the NB15 milestone, with the option to kill the hyperlink provider as a stop gap measure.

**Comment by neilcsmith-net** [comment] 2022-07-15 14:51
@matthiasblaesing given lack of response from @dbalek do you want to put forward a PR to disable this hyperlink provider before we branch?

**Comment by matthiasblaesing** [comment] 2022-07-15 19:25
I'm preparing a PR.

**Comment by matthiasblaesing** [comment] 2022-07-15 20:32
I created the PR, not having a deadlock is difficult to prove - I'd like a review on this.

**Comment by neilcsmith-net** [comment] 2022-07-16 08:20
Adding for reference link to old JIRA issue from 12.5 - https://issues.apache.org/jira/browse/NETBEANS-5913  Here the Micronaut handler was deadlocked with something else, but only one side of the problem was resolved AFAIK.  Possibility for other deadlock was noted, eg. in comment from @sdedic there -

> Well, the Hyperlink API also holds read_lock on the document while calling out to providers. The lock is not documented (AFAIK) and can also cause problems - IMHO sholuld be fixed as well.
>
> Consistency can't be guaranteed as input is an offset + no lock is held, so document may mutate before read_lock is obtained. So we can only ensure weak consistency by e.g. not painting the hyperlink if a concurrent doc change occurs

**Closed** 2022-07-16 13:21 UTC
Labels: kind:bug, priority:high

**Comment by matthiasblaesing** [comment] 2022-07-16 13:23
@syco I merged the PR to master - you should still test it - it is just that monday the release branch will be branched of and its easier when the changes are already in.
