### ISSUE TITLE
Support PHP 8.1 Enum

### ISSUE THREAD

**Issue by snipershady** [apache/netbeans#3839] opened 2022-03-23 13:24 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

Netbeans identify this Enum with Syntax Error

```
enum Suit {
    case Clubs;
    case Diamonds;
    case Hearts;
    case Spades;
}
```

or 

```
enum Status: int
{
	case ConversationStarted = 0;
	case PresentationRequested = 1;
	case InvitorRequested = 2;
	case ConversationEnded = 3;
}
```

### How to reproduce

Write a new enum in a project based on PHP 8.1

### Did this work correctly in an earlier version?

No

### Operating System

Debian 11

### JDK

openjdk 11

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by neilcsmith-net** [comment] 2022-03-23 14:03
NetBeans does not support all features of PHP 8.1 yet.

**Comment by KacerCZ** [comment] 2022-03-23 14:22
Duplicate of #3614.

PHP 8.1 support is tracked at https://issues.apache.org/jira/browse/NETBEANS-5599
Not all features are implemented in NetBeans 13.

**Closed by KacerCZ** 2022-03-23 14:22 UTC
Labels: PHP, kind:feature

**Comment by neilcsmith-net** [comment] 2022-03-23 14:34
@KacerCZ well, that issue is marked closed.  Can you open an issue for remaining PHP 8.1 features here?  Otherwise we're just going to be closing duplicates even more often! :smile:
