### ISSUE TITLE
Missing "Show opened documents list" widget with FlatLaf theme

### ISSUE THREAD

**Issue by jherkel** [apache/netbeans#6587] opened 2023-10-18 19:22 UTC
### Apache NetBeans version

Apache NetBeans 20 release candidate

### What happened

I tried netbeans rc1 and I have a problem with "Show opened documents list" action. When I clicked to the icon, nothing has displayed. The first time I could see a window for maybe half a second but after that time the window has hidden.  
I also tried GTK theme and I can see this widget so I think there is something wrong with the FlatLaf theme.

### How to reproduce

1) Select FlatLaf Light (but the same issue I can see with all FlatLaf themes)
2) Click to icon for "Show opened documents list" action.

### Did this work correctly in an earlier version?

Apache NetBeans 18

### Operating System

Fedora 39 - Wayland

### JDK

OpenJDK 21 64bit

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by mbien** [comment] 2023-10-18 19:55
Do other popups work? Anything in the log?

can't reproduce this in fedora/virtualbox

![image](https://github.com/apache/netbeans/assets/114367/ea1ff1b6-12b4-4bb4-a343-1f62bebdfd1b)

**Comment by jherkel** [comment] 2023-10-18 21:42
I checked logs but I can see only some errors from parser and indexer. If
you mean, for example, code completion as example of popup then yes I can
see it.

Jakub

**Comment by neilcsmith-net** [comment] 2023-10-19 08:36
Can replicate on my laptop which has Wayland. My main machine is X11 (dual monitor setup doesn't work on Wayland) and doesn't show this issue.

It appears to be a JDK regression.  NetBeans 19 and 20-rc1 show this issue running on JDK 21, but neither have a problem on JDK 20.  Please can you verify this?

@mbien which JDK are you using there?

**Comment by neilcsmith-net** [comment] 2023-10-19 09:07
cc @DevCharly any idea what FlatLaf is doing differently with popups that might cause this?  This change in the JDK looks like it might be a culprit?  https://github.com/openjdk/jdk/commit/3d550f748521443dc2e148aa4f786060419f1113

**Comment by neilcsmith-net** [comment] 2023-10-19 09:15
Could you try with JDK 21 too?

**Comment by mbien** [comment] 2023-10-19 09:42
yes I am testing as we speak:
reproducible with both:
`amazon-corretto-21.0.0.35.1-linux-x64` and
`amazon-corretto-21.0.1.12.1-linux-x64`

I sometimes see the popup flickering for a split second but it disappears right away.

`sort by project `and window decoration switches do not influence the result for me

**Comment by trixon** [comment] 2023-10-21 04:13
> NetBeans 19 and 20-rc1 show this issue running on JDK 21, but neither have a problem on JDK 20. Please can you verify this?

Yes, I can confirm that.

**Comment by DevCharly** [comment] 2023-10-21 14:07
> cc @DevCharly any idea what FlatLaf is doing differently with popups that might cause this?

Yes, FlatLaf always uses so-called heavy-weight popups (`JWindow`) to get that nice drop-shadow for all popups (menus, tooltips, combobox lists, etc).
Other Lafs use light-weight popups (`JPanel`) as long as the popup fits into the owner window. Otherwise they also use heavy-weight popups. So this issue also occurs in Metal or GTK Laf if the NB "document list" popup does not fit into the NB main window.

> This change in the JDK looks like it might be a culprit? [openjdk/jdk@3d550f7](https://github.com/openjdk/jdk/commit/3d550f748521443dc2e148aa4f786060419f1113)

Yes, this is the cause. I've debugged it.
The popup `JWindow` gains focus, therefore the main window looses focus and the [popup is hidden](https://github.com/openjdk/jdk/commit/3d550f748521443dc2e148aa4f786060419f1113#diff-06394e306da8bd8cd5afb8887820511ffd26a05cbabb6aabedc92301f02f76ddR503-R511). This is a regression in JDK 21.

So why do other popups (menu, tooltips, etc) work in NB with Java 21? Because they do not receive focus.

The NB "document list" popup internally uses a `JTable` and for keyboard navigation is seems that the focus is transferred to the table.

I'm working on a fix/hack for FlatLaf that removes that bad window focus listener 😒

**Comment by mbien** [comment] 2023-10-21 19:39
test build https://github.com/apache/netbeans/suites/17486031545/artifacts/999291196

tested on 21+35, 21.0.1 and 20.0.2 and the fix solves the issue for me (fedora test setup). Thanks @DevCharly!

**Comment by DevCharly** [comment] 2023-10-21 23:17
BTW I've reported the issue in Java 21 to "Java bug database"

**Closed** 2023-10-23 08:48 UTC
Labels: kind:bug

**Comment by DevCharly** [comment] 2023-11-05 15:29
> BTW I've reported the issue in Java 21 to "Java bug database"

https://bugs.openjdk.org/browse/JDK-8319103
