### ISSUE TITLE
Payara server does not work with JDK 17

### ISSUE THREAD

**Issue by elvisfabiane** [apache/netbeans#3773] opened 2022-03-13 02:50 UTC
### Apache NetBeans version

Apache NetBeans 13

### What happened

We are in the middle of a migration process and when trying to start the Payara server on JDK 17 I cannot select . 

### How to reproduce

Add new server, select Payara, when starting it the IDE asks for the platform, at this moment none appears.

### Did this work correctly in an earlier version?

No

### Operating System

Window 11

### JDK

17 LTS

### Apache NetBeans packaging

Apache NetBeans provided installer

### Anything else

The team anxiously waited for the version, possibly this would be fixed in version 13. This is having a significant impact on the company, as we are migrating to version 17 and we don't have an IDE that runs correctly with Payara and JDK 17.

### Are you willing to submit a pull request?

Yes

### Code of Conduct

Yes

**Comment by matthiasblaesing** [comment] 2022-03-14 19:03
Duplicate of #3758

**Closed by matthiasblaesing** 2022-03-14 19:03 UTC
Labels: kind:bug, needs:triage
